### ISSUE TITLE
추가문의입니다.

### ISSUE THREAD

**Issue by loosvhe** [neolord0/hwplib#10]
혹시 페이지별로 텍스트 추출이 가능한가요?

**Comment by neolord0** [comment]
일단, 결론부터 말씀 드리자면, 페이지별로 텍스트를 추출하는 것은 현재로써는 불가능합니다.
한글 파일 구조에는 어디서부터 어디까지가 몇 번쨰 페이지인지 정확히 표현되어 있지 않습니다.
한글 내에 있는 문단과 문단 안에 있는 컨트롤(표, 글상자) 들을 그려봐야 적확히 페이지를 정의할 수 있습니다. 이 쪽 부분은 아직 정확히 알지 못합니다. 도전해 보곤 싶지만 이 분야에서 유명한 폴라리스 오피스를 만든 인프라웨어라는 회사도 한글과 100%  동일한 결과을 만들지 못하는 것을 보면 어려운 거 같습니다.

**Comment by neolord0** [comment]
페이지 끝 부분에 특정 글자를 넣어서 자르시는게...
지금으로선 최선의 방법일 꺼 같습니다.

**Comment by yjcpark** [comment]
하 저도 저 페이지 구분이 없다는 점을 알고는있는데... 생각을 좀 더 해봐야겠네요^^ 답변 감사합니다.

**Comment by loosvhe** [comment]
저도 페이지 구분이 없는 점을 알고는 있었는데... 하 좀 더 생각을 해봐야겠네요^^ 답변감사합니다.

**Comment by neolord0** [comment]
임의의 한글 문서가 아닌... 특정한 한글 문서를 만들어서 페이지 별로 추출하고 싶다면, 한 페이지마다 구역(섹션)으로 나눠주고 구역별로 읽으면 될 수도 있습니다만.. @@;
