### ISSUE TITLE
표 셀 안의 문장을 가운데 정렬 하면 문자가 겹치는 문제

### ISSUE THREAD

**Issue by hyun001** [neolord0/hwplib#102]
<img width="742" alt="스크린샷 2020-11-26 오후 4 00 34" src="https://user-images.githubusercontent.com/63301376/100317991-a289b880-3000-11eb-807d-d00f198cb5f8.png">

문단을 위 스크린샷 처럼 가운데 정렬을 했습니다.

<img width="743" alt="스크린샷 2020-11-26 오후 4 00 57" src="https://user-images.githubusercontent.com/63301376/100318038-b6cdb580-3000-11eb-8fc4-07e60027c514.png">

이 상태에서 글자를 추가하면 문자가 밑으로 줄바꿈이 되지 않고 겹치는 문제가 있습니다.
추가로 문자가 마우스로 드래그가 안됩니다.

<img width="741" alt="스크린샷 2020-11-26 오후 4 04 15" src="https://user-images.githubusercontent.com/63301376/100318943-37d97c80-3002-11eb-9a21-a4feac5d77ff.png">

가운데 정렬을 하는 코드를 제거하면 위처럼 정상적으로 출력됩니다.

예제의 Inserting_Table.java의 setParaHeader에 아래의 가운데 정렬을 하는 코드를 추가했습니다.

**Inserting_Table.java**
```
public void setParaHeader(Paragraph p, HWPFile hwpFile) {
        ParaHeader ph = p.getHeader();

        //* 가운데 정렬
        ParaShape paraShape = hwpFile.getDocInfo().addNewParaShape();
        paraShape.getProperty1().setAlignment(Alignment.Center);
        int shapeId = hwpFile.getDocInfo().getParaShapeList().size() - 1;
        ph.setParaShapeId(shapeId);

        ph.setLastInList(true);
        // 셀의 스타일을이미 만들어진 스타일으로 사용함
        ph.setStyleId((short) 1);
        ph.getDivideSort().setDivideSection(false);
        ph.getDivideSort().setDivideMultiColumn(false);
        ph.getDivideSort().setDividePage(false);
        ph.getDivideSort().setDivideColumn(false);
        ph.setCharShapeCount(1);
        ph.setRangeTagCount(0);
        ph.setLineAlignCount(1);
        ph.setInstanceID(0);
        ph.setIsMergedByTrack(0);
}
```
셀 안의 내용을 어떻게 하면 가운데 정렬을 정상적으로 할 수 있을까요?

**Comment by neolord0** [comment]
한글은 한개의 문단(Paragraph)이 여러 개의 줄로 표현 될때.. 문단(Paragraph) 아래에 LineSeg에 라인에 대한 정보를 넣어줍니다.
<img width="450" alt="스크린샷 2020-11-27 오전 8 27 27" src="https://user-images.githubusercontent.com/24711108/100397844-4ae65e00-308f-11eb-980d-43d1659e3939.png">
위와 같이 4개의 줄로 나열될 경우... 
<img width="494" alt="스크린샷 2020-11-27 오전 8 56 19" src="https://user-images.githubusercontent.com/24711108/100397870-6d787700-308f-11eb-9c58-b95208991c20.png">
LineSegItemList에 4개의 LineSegItem 이 들어간 것을 볼 수 있습니다.

이렇게 넣어주어야.. 4줄로 나옵니다. 
문제는 문단이  몇줄로 출력 되는지, 어디서 어떻게 출력되는 지 계산하기 힘든 부분입니다. 
한글에서는 그리기를 빠르게 하려고 이런

**Comment by neolord0** [comment]
새로운 ParaShape에 가로 정렬(setAlignment()) 이외에 나머지 값들이 설정되지 않아서.. 그런 거 같습니다.
hwpFile.getDocInfo().addNewParaShape() 함수는 ParaShape 객체만을 생성할 뿐.. 기본 값을 설정하지 않습니다.


   public void setParaHeader(Paragraph p, HWPFile hwpFile) {
        ...

       //* 가운데 정렬
        ParaShape sourceParaShape = hwpFile.getDocInfo().getParaShapeList().get(1);
        ParaShape paraShape = addAndCopyParaShape(sourceParaShape);
        paraShape.getProperty1().setAlignment(Alignment.Center);
        int shapeId = hwpFile.getDocInfo().getParaShapeList().size() - 1;
        ph.setParaShapeId(shapeId);
       
          ....
   }

   private ParaShape addAndCopyParaShape(ParaShape source) {
        ParaShape target = hwpFile.getDocInfo().addNewParaShape();
        target.getProperty1().setValue(source.getProperty1().getValue());
        target.setLeftMargin(source.getLeftMargin());
        target.setRightMargin(source.getRightMargin());
        target.setIndent(source.getIndent());
        target.setTopParaSpace(source.getTopParaSpace());
        target.setBottomParaSpace(source.getBottomParaSpace());
        target.setLineSpace(source.getLineSpace());
        target.setTabDefId(source.getTabDefId());
        target.setParaHeadId(source.getParaHeadId());
        target.setBorderFillId(source.getBorderFillId());
        target.setLeftBorderSpace(source.getLeftBorderSpace());
        target.setRightBorderSpace(source.getRightBorderSpace());
        target.setTopBorderSpace(source.getTopBorderSpace());
        target.setBottomBorderSpace(source.getBottomBorderSpace());
        target.getProperty2().setValue(source.getProperty2().getValue());
        target.getProperty3().setValue(source.getProperty3().getValue());
        target.setLineSpace2(source.getLineSpace2());
        return target;
    }

**Comment by hyun001** [comment]
감사합니다 해결됐습니다!
추가로 질문이 있습니다.
혹시 페이지를 추가하는 기능이 있나요?
다수의 테이블을 생성하여 한페이지에 하나의 테이블만 삽입하려고 합니다.

**Comment by neolord0** [comment]
한글은 페이지 객체는 없고.. 섹션 속에 문단(Paragraph)들 중에 페이지 나눠질 문단을 선택해서..
Paragraph.getHeader().getDivideSort().setDividePage(true); 로 주면 그 문단을 기점으로 페이지가 나눠집니다.

**Comment by hyun001** [comment]
답변 감사합니다. 해결됐습니다.
