### ISSUE TITLE
혹시 HWPFile 복사가 가능할까요?

### ISSUE THREAD

**Issue by GoatHead** [neolord0/hwplib#103]
안녕하세요. 개발자님 덕분에 좋은 라이브러리 사용하고 있습니다. 감사합니다.

다름이 아니라

1. *.hwp 파일을 통해 양식을 불러오고
2. 불러온 양식에 텍스트를 치환하고
3. 텍스트가 치환된 파일을 작성하는 프로그램을 만들고 있는데,

이 과정에서 여러 파일을 만들 때 처음 HWPReader를 사용하여 양식으로 불러온 HWPFile을 메모리 상에서 복사하면서 치환 작업을 하고 싶은데, HWPFile에는 setter가 없어서 불가능하더라구요. 혹시 라이브러리 내에서 지원하는 다른 방법이 있을까요?

**Comment by neolord0** [comment]
음.. HWPFile 전체를 복사하는 기능은 아직 구현되어 있지 않고요, 많은 코드를 추가하지 않는 한 불가능합니다. 
불러오는 양식이 복잡하지 않으면.. 이 부분을 직접 코드로 만들어서 처리하는게 어느 정도 비슷한 성능이 나올 듯 합니다만.. 그 역시 많은 코딩이 필요합니다.  

HWPFile 전체를 복사하는 기능은 구현이 어려운 부분은 아닌데요 
코딩량이 많아서 당장은 구현하기 힘들 거 같습니다.  
일단 작업 리스트에는 올려 넣겠습니다.

**Comment by GoatHead** [comment]
> 음.. HWPFile 전체를 복사하는 기능은 아직 구현되어 있지 않고요, 많은 코드를 추가하지 않는 한 불가능합니다.
> 불러오는 양식이 복잡하지 않으면.. 이 부분을 직접 코드로 만들어서 처리하는게 어느 정도 비슷한 성능이 나올 듯 합니다만.. 그 역시 많은 코딩이 필요합니다.
> 
> HWPFile 전체를 복사하는 기능은 구현이 어려운 부분은 아닌데요
> 코딩량이 많아서 당장은 구현하기 힘들 거 같습니다.
> 일단 작업 리스트에는 올려 넣겠습니다.

넵 지원 감사드립니다!

**Comment by neolord0** [comment]
객체 복사 기능 완료 했습니다.
받아서 테스트 해보세요..

**Comment by GoatHead** [comment]
감사드립니다 ^^
