### ISSUE TITLE
줄/칸 추가하기 기능이 있나요?

### ISSUE THREAD

**Issue by urlence** [neolord0/hwplib#105]
![스크린샷 2020-12-03 오전 11 44 06](https://user-images.githubusercontent.com/63301376/100956916-e62e7600-355c-11eb-9abe-406c49756cd5.png)

테이블 행의 서식을 유지하며 행을 추가하고 싶습니다.
한글의 줄/칸 추가하기 기능을 이용하면 행이 복사되면서 추가되는데 
이 기능이 있나요?

**Comment by neolord0** [comment]
이 기능은 현제 테이블의 상태와 선택된 셀에 따라 다른 결과를 얻을 수 있는 디자이너의 복잡한 기능입니다.
hyun001님이 이 기능을 구현 하려면,  추가 하기 전에 저장된 파일과 추가한 후에 저장된 파일을 비교하여 분석한 뒤에 직접 프로그래밍 해야 합니다.

**Comment by hyun001** [comment]
답변 감사합니다.

추가로 특정문자열에 URL링크삽입 하는 기능이 있나요? (하이퍼링크)

**Comment by neolord0** [comment]
말로 설명하기 힘들어서.. 샘플을 작성했습니다.
kr.dogfoot.hwplib.sample.Inserting_HyperLink.java 참고하시길..

**Comment by urlence** [comment]
감사합니다!!
