### ISSUE TITLE
특정 위치에 테이블 추가 하는법

### ISSUE THREAD

**Issue by urlence** [neolord0/hwplib#106]
특정 위치에 테이블을 추가하고 싶습니다.

현재는 문서내의 모든 문단을 읽어서 
지정한 문자가 있는곳에 테이블을 추가하고 있습니다.

**문서의 문단을 읽어 "HERE" 이라는 텍스트가 있는 문단 반환**
```
public static Paragraph findParagraph(HWPFile hwpFile, String text) throws UnsupportedEncodingException {
        List<Section> sectionList = hwpFile.getBodyText().getSectionList();

        for (Section section : sectionList) {
            for (Paragraph paragraph : section) {
                StringBuffer stringBuffer = new StringBuffer();
                ForParagraphList.paragraph(paragraph, TextExtractMethod.OnlyMainParagraph, stringBuffer);
                if (stringBuffer.toString().equals(text + "\n")) return paragraph;
            }
        }

        return null;
    }
```

**해당 문단에 표 컨트롤 생성**
```
public static ControlTable addTableControl(Paragraph paragraph) {
        paragraph.getText().addExtendCharForTable();
        return (ControlTable) paragraph.addNewControl(ControlType.Table);
    }
```

문제는 표를 추가한뒤 HERE이라는 문자는 삭제를 해야하는데 
하나의 문단에 표와 문자 두가지가 들어있다보니 paragraph.deleteText()를 사용 할 수가 없습니다.

이 경우, HERE이라는 문자만 삭제할 수 있는 방법이 있을까요?
아니면 위와같은 방법 외에 특정위치에 테이블을 삽입할 수 있는 기능이 있나요?

**Comment by neolord0** [comment]
문단에서 일반 텍스트 들은  Paragraph.getText().getCharList() 에 ...  HWPCharNormal 객체로 한글자 씩 저장됩니다.
ArrayList<HWPChar> charList = Paragraph.getText().getCharList(); 
이 리스트를 순회하면서.. 글자를 삭제하시면 됩니다.

이렇게, "나중에 끼워넣기" 하는 데는, 다른 분은 일반적으로 누름틀(필드의 일종)을 사용하시던 데.. 고민해보세요.

**Comment by urlence** [comment]
답변 감사합니다
