### ISSUE TITLE
안녕하세요. 표에 그림 넣는 예제 문의드립니다. 

### ISSUE THREAD

**Issue by dgahn** [neolord0/hwplib#107]
안녕하세요. 먼저, 한글 라이브러리를 만들어 주신 것에 감사합니다. 제목 그대로 표에 그림을 넣고 싶은데 어떻게 넣어야 할지 감이 안와서 예제를 만들어 주실 수 있으시면 부탁드립니다. 감사합니다.

**Comment by neolord0** [comment]
샘플 올렸습니다.
kr.dogfoot.hwplib.sample.Inserting_Table_WithImageBack 참고하세요..

**Comment by dgahn** [comment]
감사합니다. 해당 예제 참고하도록 하겠습니다.
