### ISSUE TITLE
셀 왼쪽 여백 질문

### ISSUE THREAD

**Issue by urlence** [neolord0/hwplib#108]
표의 셀에서 왼쪽 여백을 주려고 합니다.
sample의 Inserting_Table.java로 테스트 중입니다.

```
private void setTableRecordFor2By2Cells() {
        Table tableRecord = table.getTable();
        tableRecord.getProperty().setDivideAtPageBoundary(DivideAtPageBoundary.DivideByCell);
        tableRecord.getProperty().setAutoRepeatTitleRow(false);
        tableRecord.setRowCount(2);
        tableRecord.setColumnCount(2);
        tableRecord.setCellSpacing(0);
        tableRecord.setLeftInnerMargin(10);
        tableRecord.setRightInnerMargin(0);
        tableRecord.setTopInnerMargin(0);
        tableRecord.setBottomInnerMargin(0);
        tableRecord.setBorderFillId(getBorderFillIDForTableOutterLine());
        tableRecord.getCellCountOfRowList().add(2);
        tableRecord.getCellCountOfRowList().add(2);
    }
```

 **tableRecord.setLeftInnerMargin(10);** 을 지정해도 왼쪽 여백이 들어가지 않습니다.
또한 **lh.getProperty().setApplyInnerMagin(true);** 을 추가해도 여백이 들어가지 않습니다.
**setListHeaderForCell** 함수의 lh.setLeftMargin(10);을 설정해도 작동하지 않습니다.

셀에 왼쪽여백을 주려면 어떻게 해야되나요?

**Comment by neolord0** [comment]
Table tableRecord; 부분은 테이블 전체에.. 여백이 들어가는 부분이고요.
![image1](https://user-images.githubusercontent.com/24711108/101735155-ca027a00-3b04-11eb-958c-0bf304f573ee.png)
한글에서 열어보면.. 이렇게 세팅이 됩니다. 너무 작아서.. 표현되지 않은 듯 합니다.

**Comment by urlence** [comment]
감사합니다.
