### ISSUE TITLE
kr.dogfoot.hwplib.reader.HWPReader.fromURL 에러관련 문의 입니다.

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#11]
바쁘신데 또 요청을 하게 되네요. ^^;;

파일을 못 여는 부분은 거의 처리가 된거 같은데요.
파일 오픈시 에러가나서 텍스트 변환이 안되는 파일들입니다.

java.lang.Exception: List header must be located.
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009694::00::1::1
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008185::00::1::1

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space		
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009614::00::1::1
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009696::00::1::1	

java.lang.Exception: Shape Component must come after CtrlHeader for gso control.
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170929853::01::1::1
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170930124::00::1::1

java.lang.Exception: Decompressed bytes size is wrong.		
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170911931::00::1::1
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171002562::00::1::1

java.lang.NullPointerException	
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008074::00::1::1

java.io.FileNotFoundException: no such entry: "Section1", had: [Section0]	
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008205::00::1::1

org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x75636F4420505748, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document
	http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20140423439::00::1::1

혹시 위 파일들도 에러 처리하여 텍스트 변환이 가능한지 확인 부탁드립니다.

수고하세요.

**Comment by neolord0** [comment]
java.lang.Exception: List header must be located.
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009694::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008185::00::1::1
단순한 오류 수정 했습니다.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009614::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171009696::00::1::1
압축 푸는 부분의 오류 수정 했습니다.

java.lang.Exception: Shape Component must come after CtrlHeader for gso control.
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170929853::01::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170930124::00::1::1
단순한 오류 수정 했습니다.

java.lang.Exception: Decompressed bytes size is wrong.
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170911931::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171002562::00::1::1
압축 푸는 부분의 오류 수정 했습니다.

java.lang.NullPointerException
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008074::00::1::1
객체 연결선 컨트롤이 없어서 문제가 됐습니다. 이 부분은 추가했습니다.

java.io.FileNotFoundException: no such entry: "Section1", had: [Section0]
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20171008205::00::1::1
이건 수정하고 보니.. 잘 됩니다. 위와 같은 문제인 듯 합니다.

org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x75636F4420505748, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20140423439::00::1::1
이 파일은 HWP 3.0 파일(한글97용)로 이 라이브러리로는 안 열립니다.

**Comment by osc91** [comment]
감사합니다. 
수고하셨습니다. ^^
