### ISSUE TITLE
하이퍼링크 설정 시 파라미터가 잘립니다.

### ISSUE THREAD

**Issue by urlence** [neolord0/hwplib#110]
```
ControlField field = (ControlField) p.addNewControl(ControlType.FIELD_HYPERLINK.getCtrlId());
field.getHeader().setCommand("http://www.some.com/thing?uuid=085eeeae-eaf7-4ed0-829a-061a4ae30195" +";1;0;0;");
```
위처럼 하이퍼링크를 설정하니 http://www.some.com/thing 까지만 설정이 되고 뒤에 붙는 파라미터는 잘려서 설정이 됩니다.
파라미터까지 붙여서 설정할 수 있는 방법이 있을까요?

**Comment by neolord0** [comment]
한글에서 "http://www.some.com/thing?uuid=085eeeae-eaf7-4ed0-829a-061a4ae30195"이 링크를 하이퍼링크 필드에 넣은 후
저장하여 보니 Command에 "http\://www.some.com/thing\?uuid=085eeeae-eaf7-4ed0-829a-061a4ae30195;1;0;0;"
이렇게 들어가네요..

아마도 ..scheme 뒤,  querystring 앞에 "\"이 들어가는 거 같습니다.

**Comment by urlence** [comment]
해결됐습니다 감사합니다 !
