### ISSUE TITLE
문단 복사 관련 질문드립니다.

### ISSUE THREAD

**Issue by seopchan** [neolord0/hwplib#113]
[layout.hwp.zip](https://github.com/neolord0/hwplib/files/5786004/layout.hwp.zip)
[1.hwp.zip](https://github.com/neolord0/hwplib/files/5786006/1.hwp.zip)
[2.hwp.zip](https://github.com/neolord0/hwplib/files/5786007/2.hwp.zip)
[3.hwp.zip](https://github.com/neolord0/hwplib/files/5786008/3.hwp.zip)

layout.hwp 파일에 각 1 ,2, 3번 파일을 복사하여 넣는 작업을 하고 있습니다.
1, 2, 3 파일에는  한글의 개요 번호가 설정되어있는데 각 파일을 복사할 때마다 개요 번호를 증가하고싶습니다.

1. 문제1
2. 문제2
3. 문제3
-> 위와 같은 형식으로 저장을 원합니다.

1. 문제1 ~ 문제3
-> 현재 코드의 동작은 1번 개요 안에 모든 내용이 들어갑니다.

해서 제가 찾은 것은 ControlNewNumber인데 우선 이것이 개요 번호를 설정해주는 객체가 맞는지 궁금합니다.
아니라면 어떠한 방법으로 개요 번호를 설정할 수 있는지 알려주신다면 정말 감사하겠습니다.

```
try{
                HWPFile sourceHWPFile = HWPReader.fromURL(questionUrl);
                HWPFile targetHWPFile;
                if(count == 0) {
                    targetHWPFile = HWPReader.fromURL(layoutUrl);
                } else {
                    targetHWPFile = HWPReader.fromFile("/tmp/" + tempFileName);
                }

                if (sourceHWPFile != null && targetHWPFile != null) {
                    ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

                    ParagraphListInterface targetFirstSection = sectionList.get(0);
                    Section targetSection = sourceHWPFile.getBodyText().getSectionList().get(0);
                    for (int i=0 ; i<targetSection.getParagraphCount(); i++) {
                        Paragraph sourceParagraph = targetSection.getParagraph(i);
                        ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                        paraAdder.add(sourceHWPFile, sourceParagraph);
                    }
                    HWPWriter.toFile(targetHWPFile, "/tmp/" + tempFileName);
                }
            } catch (Exception e) {
                throw new Error(e);
            }
```

두 번째 문제는 ControlNewNumber 객체에 대한 테스트를 하면서 발생되었습니다.
해당 객체가 개요 번호에 관련된 객체인지 확인하기 위해 위 코드의 sourceParagraph에 ControlNewNumber를 추가했습니다.
아래의 코드를 실행하면 NullPointerException이 발생하는데 해당 내용도 확인해주시면 감사하겠습니다.

```
for (int i=0 ; i<targetSection.getParagraphCount(); i++) {
                        Paragraph sourceParagraph = targetSection.getParagraph(i);
                        ControlNewNumber c = new ControlNewNumber();
                        c.getHeader().setNumber(2);
                        sourceParagraph.getControlList().add(c);
                        ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                        paraAdder.add(sourceHWPFile, sourceParagraph);
                    }

```

**Comment by neolord0** [comment]
이 문제 해결 하셨나요 ?
시간이 없어서.. 이번 주에 보려고 했는데..

ControlNewNumber 는 문단 앞에 붙는 번호를 초기화(reset)하는 걸로 알고 있습니다.
ControlNewNumber 없이도 자동적으로 문단 모양에서 번호를 설정하면 되는 걸로 알고 있습니다.

그리고 두번째 문제는..
문단에 컨트롤을 추가하려면.. 문단에 컨트롤 리스트에 컨트롤을 추가하고, 문단 텍스트에 컨트롤 문자를 추가해 줘야 합니다.
 
kr.dogfoot.hwplib.sample.Inserting_Table 예제를 보시면..

    private void createTableControlAtFirstParagraph() {
        Section firstSection = hwpFile.getBodyText().getSectionList().get(0);
        Paragraph firstParagraph = firstSection.getParagraph(0);

        // 문단에서 표 컨트롤의 위치를 표현하기 위한 확장 문자를 넣는다.
        firstParagraph.getText().addExtendCharForTable();

        // 문단에 표 컨트롤 추가한다.
        table = (ControlTable) firstParagraph.addNewControl(ControlType.Table);
    }

이런 식으로 문단에 표 컨트롤을 추가하려면 두 군데에 추가해 줘야 합니다.
// 문단에서 표 컨트롤의 위치를 표현하기 위한 확장 문자를 넣는다.
// 문단에 표 컨트롤 추가한다.

**Comment by seopchan** [comment]
답변 주셔서 감사합니다. 해당 문제는 잘 해결하였습니다.

몇 가지 질문이 더 생겼습니다.
1~3번 파일에 있는 문단 번호를 지우려고 했지만 LevelNumbering의 NumberFormat을 null로 바꾸는 것이 최선이었습니다.
혹시 문단 번호를 부여하는 객체가 어떤 것인지, 어떻게 지울 수 있는지 알 수 있을까요?

또 paraAdder.add()를 동작할 때 의도하지 않은 빈 줄이 문단 위에 추가가 됩니다.
추가가 되는 부분을 찾아보려고 했으나 쉽지 않네요.
이 부분도 도움을 받을 수 있을까요?

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    문단 번호 정보는 라이브러리에서 Numbering 객체로 만들어집니다.
이 객체는  HWPFile.getDocInfo().getNumberIngList() 리스트 안에 있습니다.
이 객체는 문단에서 문단모양 객체(ParaShape) 객체를 통해 연결됩니다.
Paragraph.getHeader().getParaShapeID()로 문단에 적용된 문단 모양 객체의 ID을 구해서. 
HWPFile.getDocInfo().getParaShapeList()에서 문단 모양객체를 구합니다. (ID = index +1)
이렇게 구한 ParaShape 에서 문단 번호 아이디(setParaHeadID()) 를 0으로 설정하면.. 문단 번호가 적용안됩니다.

한글의 문단에서는 기본적으로 한 줄이 생기는 구조로.. 
문단에 글자를 생기지 않게 하려면..Paragraph.deleteText() 하면 되지 않을 까.. 생각됩니다. 
 

-------- 원본 메일 ---------

    
        보낸사람: Seopchan_Kim <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 21.01.15 16:10 GMT +0900
        제목: Re: [neolord0/hwplib] 문단 복사 관련 질문드립니다. (#113)
        
        
    
    
        
답변 주셔서 감사합니다. 해당 문제는 잘 해결하였습니다.
몇 가지 질문이 더 생겼습니다.
1~3번 파일에 있는 문단 번호를 지우려고 했지만 LevelNumbering의 NumberFormat을 null로 바꾸는 것이 최선이었습니다.
혹시 문단 번호를 부여하는 객체가 어떤 것인지, 어떻게 지울 수 있는지 알 수 있을까요?
또 paraAdder.add()를 동작할 때 의도하지 않은 빈 줄이 문단 위에 추가가 됩니다.
추가가 되는 부분을 찾아보려고 했으나 쉽지 않네요.
이 부분도 도움을 받을 수 있을까요?

**Comment by seopchan** [comment]
답변 주셔서 정말 감사합니다.

setParaHeadID()를 0으로 해주었으나 잘 적용이 되지 않아
Paragraph.getParagraph(0).getHeader().setParaShapeId(0)으로 동작하니 문단 번호가 사라졌습니다.

두 번째 내용은 targetHWP에 Paragraph.deleteText()를 해보았으나 NullPointerException이 발생합니다...

targetHWP파일의 paragraphCount를 확인했을 때 targetHWP파일을 아무 내용 없이 만들더라도
1개의 paragraph가 있는 것이 문단 복사를 할 때 빈 줄로 적용이 되는 것 같습니다.

그래서 targetHWP파일에서 targetHWPFile.getBodyText().getSectionList().get(0).getParagraphList().clear();로
문단을 지우려고 했으나 그대로 빈 줄이 생겨있습니다...

**Comment by neolord0** [comment]
첫번째 문제는... 
Paragraph.getParagraph(0).getHeader().setParaShapeId(0) 방식은.. 
0 번 문단 모양에 문단 번호가 설정되지 않았을 때만 그렇게 되는 거 같습니다.
0 번 문단 모양을 알 수 없는 상황에서 좀 걱정됩니다. 
차라리,  님이 처음에 했던 LevelNumbering의 NumberFormat을 null로 하는게 더 좋을 거 같습니다.

두 번째 문제는, 
layout.hwp 에 1.hwp, 2.hwp, 3.hwp 순으로 붙이는데..
layout.hwp이 빈 문단(빈 줄) 하나이고 , 1.hwp, 2.hwp, 3.hwp들이  빈 문단(빈 줄)으로 끝나던데요..

이 상황에서 합치면. 
빈문단(빈 줄) =>  "layout.hwp" 
1.hwp 내용
빈문단(빈 줄) => "1.hwp" 
2.hwp 내용
빈문단(빈 줄) => "2.hwp" 
3.hwp 내용
빈문단(빈 줄) => "3.hwp" 
이런 식으로 구성될 것입니다.

layout.hwp에  포함된 "빈문단"은 삭제해 봤더니, 첫 번째 문단에 포함된 쪽(Page)과 단(Column)에 대한 정보가 사라지는 군요.
이 부분은 좀 더 고민해 봐야겠습니다.

나머지 빈 줄은 1.hwp, 2.hwp, 3.hwp 내용에서 직접 삭제하거나, 마지막 Paragraph는 복사하지 않은 게 좋을 합니다.

**Comment by seopchan** [comment]
말씀해주신 내용 잘 참고해보도록 하겠습니다. 감사합니다.

 >layout.hwp에 포함된 "빈문단"은 삭제해 봤더니, 첫 번째 문단에 포함된 쪽(Page)과 단(Column)에 대한 정보가 사라지는 군요.
 >이 부분은 좀 더 고민해 봐야겠습니다.

위 내용은 저도 더 해결 방법을 찾아보도록 하겠습니다.

**Comment by neolord0** [comment]
문단에 문단을 병합하는 함수를 만들었습니다.
==> paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);

소스를 다시 받아서.. 테스트 해보세요.
 

package kr.dogfoot.hwplib.sample;

import kr.dogfoot.hwplib.object.HWPFile;
import kr.dogfoot.hwplib.object.bodytext.ParagraphListInterface;
import kr.dogfoot.hwplib.object.bodytext.Section;
import kr.dogfoot.hwplib.object.bodytext.paragraph.Paragraph;
import kr.dogfoot.hwplib.reader.HWPReader;
import kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder;
import kr.dogfoot.hwplib.writer.HWPWriter;

import java.io.File;

public class Test1 {
    public static void main(String[] args) throws Exception {
        HWPFile targetHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "layout.hwp");

        if (targetHWPFile != null) {
            ParagraphListInterface targetFirstSection = targetHWPFile.getBodyText().getSectionList().get(0);
            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "1.hwp");
                Section sourceSection = sourceHWPFile.getBodyText().getSectionList().get(0);

                for (int index = 0; index < sourceSection.getParagraphCount(); index++) {
                    Paragraph sourceParagraph = sourceSection.getParagraph(index);

                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    if (index == 0) {
                        Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                        paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                    } else {
                        paraAdder.add(sourceHWPFile, sourceParagraph);
                    }
                }
            }

            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "2.hwp");
                for (Paragraph sourceParagraph : sourceHWPFile.getBodyText().getSectionList().get(0)) {
                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }

            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "3.hwp");
                for (Paragraph sourceParagraph : sourceHWPFile.getBodyText().getSectionList().get(0)) {
                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }

            HWPWriter.toFile(targetHWPFile, "sample_hwp" + File.separator +"layout-add-paragraph.hwp");
        }
    }
}

**Comment by seopchan** [comment]
확인이 늦어졌습니다.
수정해주신 코드로 적용해보았고 이상없이 너무 잘 동작합니다!!!

바쁘실텐데 도움 주셔서 정말 감사합니다!!

**Comment by seopchan** [comment]
[아카이브.zip](https://github.com/neolord0/hwplib/files/5891645/default.zip)
위 첨부파일에 있는 문서들을 복사할 때 

>java.lang.NullPointerException
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.FaceNameAdder.equal(FaceNameAdder.java:51)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.FaceNameAdder.equalByHangulId(FaceNameAdder.java:137)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.equalFaceNameIds(CharShapeAdder.java:56)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.equal(CharShapeAdder.java:39)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.findFromTarget(CharShapeAdder.java:31)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.processById(CharShapeAdder.java:20)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.addAndCopy(StyleAdder.java:70)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.StyleAdder.processById(StyleAdder.java:22)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:17)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at kr.dogfoot.hwplib.src.Question_Merger.handleRequest(Question_Merger.java:106)

getBaseFontName에서 error가 발생합니다. 혹시 문서에 문제가 있는 것일까요??

**Comment by seopchan** [comment]
[1706.hwp.zip](https://github.com/neolord0/hwplib/files/5891686/1706.hwp.zip)
[1763.hwp.zip](https://github.com/neolord0/hwplib/files/5891687/1763.hwp.zip)

한글파일 분석이 쉽지 않아 많은 질문 드리는 점 죄송합니다..
위 첨부 파일에 있는 '-', '·' 등의 Bullet을 복사할 때 문제가 생기는 것 같습니다.

>java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.BulletAdder.processById(BulletAdder.java:19)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.setParaHead(ParaShapeAdder.java:104)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.addAndCopy(ParaShapeAdder.java:81)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.ParaShapeAdder.processById(ParaShapeAdder.java:21)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParaHeaderCopier.copy(ParaHeaderCopier.java:16)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyHeader(ParagraphCopier.java:53)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:42)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)
	at kr.dogfoot.hwplib.src.Question_Merger.handleRequest(Question_Merger.java:106)

**Comment by seopchan** [comment]
```
HWPFile hwpFile = HWPReader.fromFile(prop.getProperty("TEMP_TARGET") + "/" + fileName);

Section s = hwpFile.getBodyText().getSectionList().get(0);
s.getParagraph(0).getHeader().setParaShapeId(0);

Paragraph p = hwpFile.getBodyText().getSectionList().get(0).getParagraph(0);
p.getText().getCharList().remove(2);

HWPWriter.toFile(hwpFile, prop.getProperty("FILE_TARGET") + "/" + fileName);
```
[25.hwp.zip](https://github.com/neolord0/hwplib/files/5915384/25.hwp.zip)
[4043.hwp.zip](https://github.com/neolord0/hwplib/files/5915385/4043.hwp.zip)

위 파일을 HWPReader로 읽어 다시 .hwp로 저장을 하면 문서 내의 이미지가 깨지는 현상이 발생합니다...

**Comment by seopchan** [comment]
[hwp.zip](https://github.com/neolord0/hwplib/files/5915446/hwp.zip)

위 파일들에서 아래와 같은 문제가 발생합니다.
그리기 객체 관련한 문제로 보이는데 이미지에 문제가 있는 것일까요...

>"errorMessage": "java.lang.NullPointerException",
    "errorType": "java.lang.NullPointerException",
    "stackTrace": [
      "kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.ctrlHeader(GsoCommonPartCopier.java:36)",
      "kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCommonPartCopier.copy(GsoCommonPartCopier.java:25)",
      "kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:25)",
      "kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.container(GsoCopier.java:315)",
      "kr.dogfoot.hwplib.tool.paragraphadder.control.GsoCopier.copy(GsoCopier.java:52)",
      "kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyControlList(ParagraphCopier.java:95)",
      "kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)",
      "kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:45)",
      "kr.dogfoot.hwplib.src.Question_Merger.handleRequest(Question_Merger.java:107)",
      "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)",
      "java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)",
      "java.base/java.lang.reflect.Method.invoke(Unknown Source)"
    ]

너무나 많은 질문을 드리게 되었네요...

**Comment by neolord0** [comment]
님이 어떻게 테스트 하셨는지 몰라서... 답해 들이기 힘드네요..
일단, 이 이슈를 닫고.. 질문마다 이슈를 만들어 주시고요.
이슈마다 해당하는 질문에서 테스트하신 소스랑.. 한글 파일을 올려주세요.
너무 해갈려서..
