### ISSUE TITLE
문단 객체 순서별로 가져오는 방법

### ISSUE THREAD

**Issue by JunChulKwon** [neolord0/hwplib#114]
안녕하세요. 좋은 라이브러리 만들어주셔서 감사합니다. 해당 라이브러리로 여러 테스트를 진행하고 있는데 궁금증이 생겨 글 남깁니다.

파일을 읽고 파일 내용을 그대로 html로 만들고자 구현을 하고 있는데요. 
글자를 가져오는 방법, 이미지를 가져오는 방법, 표를 가져오는 방법은 얼추 알겠는데 문단의 글자, 표, 이미지 등 표시 순서대로 문단을 가져오는 방법이 없는 것 같아 문의 드립니다. 문단 전체의 글과 표를 가져오는 방법에서 표를 별개로 체크해서 글자와 표의 문단 순서를 가져오는 건 알겠는데 문단 중간에 삽입되어 있는 이미지의 경우 가져오는건 문제없지만 어떻게 자신의 순서를 찾아 들어갈 수 있는지 궁금하네요.

**Comment by neolord0** [comment]
문단에 중간에 삽입된 컨트롤(이미지, 표, 글상자)들은 문단 Text에 확장 컨트롤 문자를 추가하여 자신의 위치 또는 순서를 나타냅니다.
"AB 표 CD 이미지 EF"로 된 문단은 
Paragraph.getText()의 글자 리스트에 
    Normal Character -"A"
    Normal Character -"B" 
    Extend Control Character - "표"
    Normal Character -"D" 
    Normal Character -"C" 
    Extend Control Character - "이미지"
    Normal Character -"E"  
    Normal Character -"F" 
로 나열되고, 
Paragraph.getControlList() 에는
    표, 이미지 컨트롤
이 들어가야 합니다.

그런데, 이건 그리는 순서에 가까우며 화면에 그려지는 순서와는 다를 수 있습니다.
표를 포함한 컨트롤 들이 자체적으로 좌표를 가질 수 있는데, 이걸 순서와 무관하게 좌표에 의해 위치가 설정됩니다.

화면에 보이는 데로.. html로 만들길 원하시면... 한글 파일을 전체를 그려서 위치를 알아야 합니다만..
이 부분은 아직 지원하고 있지 않습니다.

**Comment by JunChulKwon** [comment]
답변 감사합니다!
