### ISSUE TITLE
테이블 행을 복사하는 방법

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#115]
안녕하세요 한글문서 구조 스터디 중 궁금한게 생겨서 질문드립니다.

![image](https://user-images.githubusercontent.com/39794244/104560437-35ea7c00-5689-11eb-95c2-4af69395ad27.png)

위와 같은 테이블이 구성되어 있습니다.

해당 테이블의 Column이 3개로 구성 된 2행을 복사하여 4행을 만들고 싶습니다.

하지만 테이블 Row 생성 시 Column을 7개 생성해서 4행을 구성해야 hwp파일이 읽어들입니다.

눈에보이는 셀은 최대 5개이지만 내부적으로 ColumnCount는 7개를 지칭하고있기 때문에인거 같습니다.

행 복사를 하여 붙여넣으려면 어떠한 방법이 있나요?

**Comment by sgh9196** [comment]
> 안녕하세요 한글 문서 구조 스터디 중 궁금한게 생겨서 질문드립니다.
> 
> ![영상](https://user-images.githubusercontent.com/39794244/104560437-35ea7c00-5689-11eb-95c2-4af69395ad27.png)
> 
> 위와 같은 테이블이 구성되어 있습니다.
> 
> 테이블의 Column이 3 개로 구성 된 2 행을 복사하여 4 행을 만들고 싶습니다.
> 
> 하지만 테이블 행 생성시 열을 7 개 생성하여 4 행을 구성해야합니다.
> 
> 최대 5 개이지만 내부적으로 ColumnCount는 7 개를 지칭하고 있기 때문에 최대 5 개입니다.
> 
> 어떤 방법이 있나요?

**Comment by sgh9196** [comment]
자답입니다. 해당 이슈 table row 생성 시 merge 기능 사용하여 해결했습니다. 감사합니다.

**Comment by neolord0** [comment]
^^; 해결하셨다니...
