### ISSUE TITLE
embeddedBinaryDataList에 담긴 이미지 리스트

### ISSUE THREAD

**Issue by JunChulKwon** [neolord0/hwplib#116]
안녕하세요. 지난번 문단 순서대로 나열 방법에 대해 문의했던 사람입니다.
문단 글, 테이블, 이미지를 순차적으로 가져오는 방법에 대해 이해를 하고 다시 진행을 하고 있습니다.

근데 이미지의 경우 GsoControl().getType()에서 case가 picture일 경우 embeddedBinaryDataList에서 순차적으로 이미지를 뽑아 나열하는 방식으로 이미지를 뽑아냈습니다.

이 경우 한글파일 내에서 그려져 있는 순서의 이미지가 아닌 무작위성 이미지 파일이 들어가 있기에 이미지 순서를 그대로 만들어내지 못했습니다.
이 경우가 그리는 순서와 화면에 그려지는 순서가 다르다고 말씀을 주셨던 부분이 맞는 걸까요?

그리고 한글 파일을 전체 그려 위치를 알아야 한다고 말씀을 주셨는데요.  한글파일의 데이터를 불러와서 어떻게 전체를 그려야 하는지 궁금하네요.

감사합니다.

**Comment by neolord0** [comment]
음... 결론부터 말씀드리자면.. embeddedBinaryDataList의 이미지 순서와 화면상의 순서를 다릅니다.
embeddedBinaryDataList 순서는 한글 프로그램에서 이미지의 생성일거라고 생각됩니다.
A라는 그림을 만들고  그 위에 B를 만들었다면, 화면상에는 B-A지만 리스트상에는 A-B로 나올 거라고 생각됩니다.

한글을 그릴 려면.. 어떻게 해야 하냐고 질문하셨는데..  
원론대로 한글 파일을 읽어서, 그 파일안에 객체와 속성을 이해하고, 그 이해된 내용을 이미지 등으로 표현하는 건데요.
말로 설명하기가 쉽지.. 어려운 과정입니다. 
이 라이브러리의 기능은 앞에 30%정도(파일을 읽고, 객체와 속성을 이해)라고 생각됩니다.
이 기능의 구현은 SI 같은 단기 프로젝트가 아닌 장기적인 패키지 개발에 속합니다.
  
빠르게 구현하고 싶다면 한컴이나, 한글 뷰어 업체(사이넵 등)에 의뢰하는 게 좋을 듯 합니다.

**Comment by JunChulKwon** [comment]
제가 생각했던 그대로의 내용이네요!
친절한 가이드 너무 감사합니다!!
