### ISSUE TITLE
모든 테이블 조회

### ISSUE THREAD

**Issue by Chodongin** [neolord0/hwplib#117]
안녕하세요, 라이브러리 개발해주셔서 감사합니다.

개발해주신 코드를 이용하여 모든 텍스트를 긁어오는데
표의 텍스트는 긁어오지 않아서 

혹시 표의 텍스트들도 긁어 오려면
어떤 기능을 사용해야 하는지 알려주시면 
감사 드리겠습니다.

**Comment by neolord0** [comment]
kr.dogfoot.hwplib.tool.textextractor.ForControl 클레스를 참고하세요. 
컨트롤에서 텍스트 추출하는 클래스 이빈다.

**Comment by Chodongin** [comment]
답변 감사합니다.
