### ISSUE TITLE
HwpSummaryInformation 읽기 및 쓰기

### ISSUE THREAD

**Issue by riot999** [neolord0/hwplib#118]
안녕하세요. 
라이브러리 잘 사용하고 있습니다. 감사합니다.
질문이 있어 글 올립니다.

관련 클래스를 찾아봐도 보이지 않아 문의 드립니다.

메뉴에서 "문서 정보"(\005HwpSummaryInformation)의 경우 MSDN의 프로퍼티셋 형식을 가지고 있다고 알고 있습니다.
혹시 해당 부분에 대하여 읽고 쓰기를 지원하는지,
만약 지원한다면 어떤 클래스를 사용하여야 하는지 문의드립니다.

감사합니다.

**Comment by neolord0** [comment]
전에 어떤 분이 질문한 내용이 있어서요..
읽는 부분은 이렇게 하면 됩니다.  쓰는 부분은 참조하셔서 구현하시면 될 거 같습니다만.
한글 프로그램에서 정보를 넣어줘야 하는데..사용하지 않는 거 같습니다. 
 
'' java
import java.io.FileInputStream;
import java.io.IOException;

import org.apache.poi.hpsf.MarkUnsupportedException;
import org.apache.poi.hpsf.NoPropertySetStreamException;
import org.apache.poi.hpsf.Property;
import org.apache.poi.hpsf.PropertySet;
import org.apache.poi.poifs.filesystem.DirectoryEntry;
import org.apache.poi.poifs.filesystem.DocumentEntry;
import org.apache.poi.poifs.filesystem.DocumentInputStream;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;

public class GettingSummaryInfo {
	public static void main(String[] args) {
		try {
		    FileInputStream stream = new FileInputStream("22.hwp");
		    POIFSFileSystem poifs = new POIFSFileSystem(stream);
		    DirectoryEntry dir = poifs.getRoot();
		    DocumentEntry entry = (DocumentEntry)dir.getEntry("\u0005HwpSummaryInformation");
		    DocumentInputStream dis = new DocumentInputStream(entry);
		    PropertySet ps = new PropertySet(dis);
		    for(Property p : ps.getProperties()) {
		    	switch((int)p.getID()) {
		    	case 0x2:
		    		System.out.println("Title = " + p.getValue());
		    		break;
		       	case 0x3:
		    		System.out.println("Subject = " + p.getValue());
		    		break;
		       	case 0x4:
		    		System.out.println("Author = " + p.getValue());
		    		break;
		       	case 0x5:
		    		System.out.println("Keywords = " + p.getValue());
		    		break;
		       	case 0x6:
		    		System.out.println("Comments = " + p.getValue());
		    		break;
		       	case 0x7:
		    		System.out.println("Template = " + p.getValue());
		    		break;
		       	case 0x8:
		    		System.out.println("Last Saved By = " + p.getValue());
		    		break;
		       	case 0x9:
		    		System.out.println("Revision Number = " + p.getValue());
		    		break;
		       	case 0xA:
		    		System.out.println("Total Editing Time = " + p.getValue());
		    		break;
		       	case 0xB:
		    		System.out.println("Last Printed = " + p.getValue());
		    		break;
		       	case 0xC:
		    		System.out.println("Create Time/Date = " + p.getValue());
		    		break;
		       	case 0xD:
		    		System.out.println("Last saved Time/Date = " + p.getValue());
		    		break;
		       	case 0xE:
		    		System.out.println("Number of Pages = " + p.getValue());
		    		break;
		       	case 0xF:
		    		System.out.println("Number of Words = " + p.getValue());
		    		break;
		       	case 0x10:
		    		System.out.println("Number of Characters = " + p.getValue());
		    		break;
		       	case 0x11:
		    		System.out.println("Thumbnail = " + p.getValue());
		    		break;
		       	case 0x12:
		    		System.out.println("Name of Creating Application = " + p.getValue());
		    		break;
		       	case 0x13:
		    		System.out.println("Security = " + p.getValue());
		    		break;
		    	}
		    }
		    stream.close();
		    poifs.close();
		} catch (IOException ex) {
		    ex.printStackTrace();
		} catch (NoPropertySetStreamException ex) {
		    ex.printStackTrace();
		} catch (MarkUnsupportedException ex) {
		    ex.printStackTrace();
		}
		System.out.println("end");
	}
}
