### ISSUE TITLE
안녕하세요 테이블관련 질문사항이있어 글 올립니다.

### ISSUE THREAD

**Issue by disk4052** [neolord0/hwplib#119]
안녕하세요 글쓰기 앞서 이런 좋은 라이브러리를 만들어주셔서 정말 감사합니다.

다름아니라 표안에 표를 넣고싶은 작업을 하고있는데,

바깥 표의 한쪽 Cell의 paragraph를 가지고와서 거기에 표를 추가했는데 셀안에 표가 추가되는게 아닌 그냥 같은위치에 표가 겹쳐서 두개 생성되더라구요.

혹시 제가 한 방식이 잘못되었나요??

**Comment by neolord0** [comment]
음.. 방식은 맞는 거 같은데요..
위치를 넣어주게... 잘 못된 듯 합니다.
위치 기준을 "페이지"로 되었다면, "문단" 기준으로 설정해 보세요.

ControlTable.getHeader().getProperty()에.. 
setHorzRelTo() // 가로 위치의 기준을 설정한다
setVertRelTo() // 세로 위치의 기준을 설정한다.
이 부분을 살펴보세요..

잘 안 되시면.. 테스트하신 소스를 보내주세요...

**Comment by disk4052** [comment]
ControlTable.getHeader().getProperty()에서

setLikeWord(false);
setVertRelToParaLimit(false);

둘중하나 true로 바꾸니까 제대로 작동하네요.

감사합니다 !!
