### ISSUE TITLE
텍스트 추출시 개요 목록 관련 문의 입니다.

### ISSUE THREAD

**Issue by darby96** [neolord0/hwplib#12]
안녕하세요.
한글 hwp 텍스트 추출관련 라이브러리를 찾다가 알게되어서 라이브러리 제공에 감사드립니다.
문의 사항이 있어서 이렇게 방법에 대한 질의 드립니다.

1. 한글에서의 개요보기처럼 문단의 목록을 가져올수 있는지 테스트를 해보고 있는데,
그 부분이 Paragraph(하나의 문단 객체)와 스타일에서 순번과의 관계(관련) 부분과 조합이 가능할런지요? 
예)  1. 사업개요
         1-1 개요
           1-1-1. 개요내용
         1-2  기타
            1-2-1. 기타 내용

그리고, 한글과 컴퓨터에서 제공하는 한글문서파일형식 문서에서의 tag ID로 데이터를 조합해서, 
문서에서의 해당 문단, 스타일과 속성정보를 추출하여, 구조화된 아래의 문서처럼
hml, odt, xml, xml, pdf 같은 형태로 변환도 가능할듯 한데, 
그 부분에 대해서 나아갈 방안도 있으신가요? 
답변 가능하시면 회신(drlove96@naver.com) 부탁드립니다. 

이런 공유라이브러리도 사용시에 한글과 컴퓨터에서 문제제기가 될지는 잘 모르겠지만, 여러가지 방법을 찾아보고자 이렇게 질의 드립니다.

**Comment by neolord0** [comment]
메일로 답변 드렸습니다.

**Comment by neolord0** [comment]
메일로 답변 드렸고요..

텍스트 추출에서 개요 추가는 시간이 좀 걸리겠지만 추가해 드리겠습니다.
