### ISSUE TITLE
안녕하세요 글씨크기 및 글꼴 질문입니다.

### ISSUE THREAD

**Issue by disk4052** [neolord0/hwplib#120]
안녕하세요 개발자님, 라이브러리 제작 및 사용자지원에 진심으로 감사드립니다.

다름아니라 문단마다 각기다른 글씨크기와 글꼴, 색상으로 작성하고싶은데 방법을 도무지 모르겠어서 이렇게 질문드립니다.ㅜㅜ

또한 스타일id에 대해 각 id별 어떤글꼴과 크기로 지정되어있는지 참고할만한 매뉴얼은 없나요 ?

**Comment by neolord0** [comment]
글씨크기, 글꼴, 색상등은 글자모양(CharShape) 객체를 통해 설정합니다.
kr.dogfoot.hwplib.sample.Inserting_CharShape 샘플을 참고하세요.

**Comment by disk4052** [comment]
감사합니다 !!
