### ISSUE TITLE
테이블 행 추가 질문

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#121]
안녕하세요.
라이브러리 잘 사용하고 있습니다. 감사합니다.
질문이 있어 글 올립니다.

![화면 캡처 2021-02-03 111733](https://user-images.githubusercontent.com/39794244/106688429-70ed2900-6611-11eb-9464-3a5f8246cd6a.png)

위와 같은 테이블이 있습니다.
저는 행을 추가하고싶습니다.

행 추가 위치는 0행과 1행 사이에 5열짜리 행을 추가하고싶습니다.

제가 시도한 코드입니다.
for(int iRow=1; iRow<19; iRow++) {
   row = table.addNewRow();
   for(int iCol=0; iCol<5; iCol++) {
        cell = row.addNewCell();
   }
}

위 코드에서 테이블 행을 추가하는데 필요한 속성은 모두 추가하였습니다.

위 소스에서 iRow 를 "2"로 시작하면 테이블 마지막 행부터 행이 추가가 되는 걸 확인 했는데,
테이블 중간에 행을 추가 할 수 있는 방법이 있나요?

제가 원하는 결과입니다.
![화면 캡처 2021-02-03 111953](https://user-images.githubusercontent.com/39794244/106688814-346dfd00-6612-11eb-9d2a-f9edf85ed164.png)

**Comment by neolord0** [comment]
위와 같은 방식으로 추가하면.. Row, Cell 객체만 생성됩니다.  
Cell 객체 안쪽의 속성들을 세팅해 줘야 하는데..

이 부분은  음... 현재로써는  kr.dogfoot.hwplib.sample.Inserting_Table가 가장 가깝네요. 
예제 코드를 만들어 들이고 싶지만, 요즘 바빠서... --;
한번 해 보시고 이해 안되는 부분을 질문해 주세요..

**Comment by sgh9196** [comment]
감사합니다. 참고하겠습니다.
