### ISSUE TITLE
문단 복사 시 Paragraph 관련 질문입니다.

### ISSUE THREAD

**Issue by seopchan** [neolord0/hwplib#122]
[layout.hwp.zip](https://github.com/neolord0/hwplib/files/5923153/layout.hwp.zip)
[1.hwp.zip](https://github.com/neolord0/hwplib/files/5923155/1.hwp.zip)
[2.hwp.zip](https://github.com/neolord0/hwplib/files/5923156/2.hwp.zip)
[3.hwp.zip](https://github.com/neolord0/hwplib/files/5923157/3.hwp.zip)

layout파일에 1, 2, 3 파일을 각각 복사를 하는 코드입니다.

첫 줄에 번호를 붙이기 위해서 deleteText()와 createText()를 사용했습니다.
3번 파일의 경우 이상없이 작동을 합니다.
1, 2번 파일을 테스트하면 빈 파일이 나오게 되는데 한글 파일에 문제가 있는 것 일까요?

아래 파일은 2번 파일을 테스트 했을 때 나온 파일입니다.
[new1237.hwp.zip](https://github.com/neolord0/hwplib/files/5923179/new1237.hwp.zip)

테스트에 사용한 코드입니다.
```
if (sourceHWPFile != null && targetHWPFile != null) {
            ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

            ParagraphListInterface targetFirstSection = sectionList.get(0);
            Section targetSection = sourceHWPFile.getBodyText().getSectionList().get(0);
            for (int i = 0; i < targetSection.getParagraphCount(); i++) {
                Paragraph sourceParagraph = targetSection.getParagraph(i);
                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);

                if (i == 0) {
                    String firstLine = sourceParagraph.getNormalString();
                    sourceParagraph.deleteText();
                    sourceParagraph.createText();
                    String newFirstLine = "1. " + firstLine;
                    sourceParagraph.getText().addString(newFirstLine);

                    Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                    paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                } else {
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }
            HWPWriter.toFile(targetHWPFile, "new" + sourceFileName);
        }
```

**Comment by neolord0** [comment]
이 부분은 문단 앞에 "1. "을 추가하는 부분에서.. 
모든 글자를 지우고 다시 입력하는 과정에서 지우지 말아야 할 .. 그림 객체를 위한 Extend Control Character가 삭제되어서 
그런 거 같습니다..그래서.. insertString() 함수를 추가하였습니다.

''' java
        HWPFile targetHWPFile = HWPReader.fromFile(targetFileName);
        HWPFile sourceHWPFile = HWPReader.fromFile(sourceFileName);

        if (sourceHWPFile != null && targetHWPFile != null) {
            ArrayList<Section> sectionList = targetHWPFile.getBodyText().getSectionList();

            ParagraphListInterface targetFirstSection = sectionList.get(0);
            boolean firstSection = true;

            Section sourceSection = sourceHWPFile.getBodyText().getSectionList().get(0);
            for (int i = 0; i < sourceSection.getParagraphCount(); i++) {
                Paragraph sourceParagraph = sourceSection.getParagraph(i);

                ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                if (i == 0) {
                    sourceParagraph.getText().insertString(0, "1. ");
                }

                if (firstSection) {
                    paraAdder.merge(targetFirstSection.getParagraph(0), sourceHWPFile, sourceParagraph);
                    firstSection = false;
                } else {
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }
            HWPWriter.toFile(targetHWPFile, "is123/result.hwp");
        }

**Comment by seopchan** [comment]
테스트 해보았고 너무나 잘 작동합니다!! 
바쁘실텐데 정말 감사합니다!!
