### ISSUE TITLE
안녕하세요. 질문이 있어서 글을 작성합니다.

### ISSUE THREAD

**Issue by dgahn** [neolord0/hwplib#129]
안녕하세요. 개발해주신 라이브러리를 덕분에 잘 사용하고 있는 개발자입니다.

현재 hwp 파일을 웹에서 보여주기 위한 작업을 진행하고 있는데 문제를 겪고 있어 질문을 드립니다.

1. hwp 파일을 만들 때 어떤 버전으로 만들어지나요? 또 버전을 명시할 수 있나요?

2. pdf 파일 변환에 대한 개발을 계획이 있으신가요? 있으면 언제쯤으로 생각하시나요?

감사합니다.

**Comment by neolord0** [comment]
1. hwp 파일은 한글 프로그램과 다른 버전 체제를 가지고 있습니다. 크게는 hwp 3 버전과 hwp 5 버전이 있고요.   
hwp 3 버전은 도스용으로 한글 97 이전에서 사용된 파일 포맷이고요,
hwp 5 버전은 2000 이후에 만들어진 windows용 한글 파일에서 사용된 버전 입니다.한글 2002 ~ 2020 까지 ... 기능이 추가되며면서... 조금씩 내부가 다르긴 하지만, 한컴은 업데이트를 통해..이 부분을 맞춰 나가고 있습니다. 
이 라이브러리는  hwp 5 버전 만을 지원합니다

2. pdf 변환 기능을 구현해 보고는 싶지만, 혼자 짬을 내서 개발하는 상황에서는 하기 힘들 거 같습니다 .  
혼자 짬을 내서 개발하기 이 기능은 너무 방대합니다.  아마도 작은 규모의 조직(회사)가 있어야 할 거 같습니다.
현재 상황하에서는 불가능하다는 말씀을 드립니다.
 pdf 변환 기능을 원하시면 한컴, 사이넵 소프트 등에.... 한글 뷰어 기술을 가지고 있는 회사에 의뢰해 보세요.

**Comment by dgahn** [comment]
친절한 답변 감사합니다. 좋은 연휴 되세요!
