### ISSUE TITLE
Section 복사 시 임의의 Paragraph가 생성되는 문제

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#131]
안녕하세요. 한글문서 구조 공부하던 중 hwplib 라이브러리를 알게되어 실습해보고 있는 중
궁금한 점이 있어서 질문드립니다.

Section cloneSection = cloneFile.getBodyText().getSectionList().get(0).clone();
Section newSection = hwpFile.getBodyText().addNewSection();

EmptyParagraphAdder.add(newSection);

// 복사 대상 Section의 여백 정보를 새로 생성 된 Section의 여백으로 설정해준다
ControlSectionDefine csdClone = (ControlSectionDefine) cloneSection.getParagraph(0).getControlList().get(0);
ControlSectionDefine csdNew = (ControlSectionDefine) newSection.getParagraph(0).getControlList().get(0);

csdNew.getPageDef().setTopMargin(csdClone.getPageDef().getTopMargin());
csdNew.getPageDef().setBottomMargin(csdClone.getPageDef().getBottomMargin());
csdNew.getPageDef().setLeftMargin(csdClone.getPageDef().getLeftMargin());
csdNew.getPageDef().setRightMargin(csdClone.getPageDef().getRightMargin());
csdNew.getPageDef().setHeaderMargin(csdClone.getPageDef().getHeaderMargin());
csdNew.getPageDef().setFooterMargin(csdClone.getPageDef().getFooterMargin());
csdNew.getPageDef().setGutterMargin(csdClone.getPageDef().getGutterMargin());
csdNew.getPageDef().getProperty().setPaperDirection(csdClone.getPageDef().getProperty().getPaperDirection());

위 소스로 target.hwp 파일에 source.hwp의 Section 정보를 복사해서 넣어주는 과정에 임의의 Paragraph가 생성됩니다.

![제목 없음](https://user-images.githubusercontent.com/39794244/108677093-87114980-752c-11eb-8ecf-8536ac7d3e85.png)

위 빨강색 사각 박스처럼 생성되며, 임의로 생성 된 Paragraph를 지우려고 시도하였으나,
ParagraphList.class 파일에 deleteParagraph() 함수가 존재하지 않아 방밥을 찾지못하여 질문드립니다.

1. Section 복사 후 붙여 넣는 과정에서 임의의 Paragraph가 생성되는 이유를 알고싶습니다.
2. Paragraph(문단)을 삭제하는 방법을 알고싶습니다. Text 삭제하는 것이 아닌 해당 라인을 제거하고싶습니다.

**Comment by neolord0** [comment]
1. 한글에서 섹션(구역)은 문단의 리스트의 일종입니다. 사각형과 표 같은 컨트롤 들에 포함된 문단 리스트와 달리, 섹션에는 섹션을 정의하는 부분과 단(Column ) 정의하는 부분이 있어야 합니다. 그래서, 섹션은 적어도 하나의 문단이 있어야 하고, 그 문단의 처음에는 반드시 섹션 정의 컨트롤과  단 정의 컨트롤로 시작해야 합니다.  
붙여 넣는 과정에서 첫번째 문단에서 이런 결과가 있어서..  문단 병합 이라는 기능을 추가 했습니다.
kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.merge()을 사용하여 문단을 병합할 수 있습니다.
'' java
package kr.dogfoot.hwplib.sample;

import kr.dogfoot.hwplib.object.HWPFile;
import kr.dogfoot.hwplib.object.bodytext.ParagraphListInterface;
import kr.dogfoot.hwplib.object.bodytext.Section;
import kr.dogfoot.hwplib.object.bodytext.paragraph.Paragraph;
import kr.dogfoot.hwplib.reader.HWPReader;
import kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder;
import kr.dogfoot.hwplib.writer.HWPWriter;

import java.io.File;

public class Test1 {
    public static void main(String[] args) throws Exception {
        HWPFile targetHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "layout.hwp");

        if (targetHWPFile != null) {
            ParagraphListInterface targetFirstSection = targetHWPFile.getBodyText().getSectionList().get(0);
            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "1.hwp");
                Section sourceSection = sourceHWPFile.getBodyText().getSectionList().get(0);

                for (int index = 0; index < sourceSection.getParagraphCount(); index++) {
                    Paragraph sourceParagraph = sourceSection.getParagraph(index);

                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    if (index == 0) {
                        Paragraph targetLastParagraph = targetFirstSection.getParagraph(targetFirstSection.getParagraphCount() - 1);
                        paraAdder.merge(targetLastParagraph, sourceHWPFile, sourceParagraph);
                    } else {
                        paraAdder.add(sourceHWPFile, sourceParagraph);
                    }
                }
            }

            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "2.hwp");
                for (Paragraph sourceParagraph : sourceHWPFile.getBodyText().getSectionList().get(0)) {
                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }

            {
                HWPFile sourceHWPFile = HWPReader.fromFile("sample_hwp" + File.separator + "3.hwp");
                for (Paragraph sourceParagraph : sourceHWPFile.getBodyText().getSectionList().get(0)) {
                    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection);
                    paraAdder.add(sourceHWPFile, sourceParagraph);
                }
            }

            HWPWriter.toFile(targetHWPFile, "sample_hwp" + File.separator +"layout-add-paragraph.hwp");
        }
    }
}
'' java

**Comment by sgh9196** [comment]
답변 감사합니다. 위에 질문드렸던 궁금증들은 다 해결되었습니다.

하나만 더 질문드리겠습니다..

table에 Row를 추가하고있는데 row를 추가하고 한글 파일을 열면 "문서 손상" 이라는 메세지가 뜹니다.

![image](https://user-images.githubusercontent.com/39794244/109112138-7dcaeb80-777d-11eb-9bcb-b98e772030dd.png)

위 그림은 해당 코드인데.. 테이블 row, cell을 추가하기 위한 조건들은 다 맞춰줫지만

82번째 라인을 보시면 2036 행까지 Row를 생성하면 "문서 손상"이라는 메세지 없이 정상적으로 row도 생성되며 한글파일도 잘 열리는데 2037 행 이상을 생성 하면서부터는 "문서 손상"이라는 메세지와 함께 한글파일이 깨집니다.

에러를 내뱉지도 않고있어서 파악하기 어려워서 질문드립니다.

혹시 라이브러리에 최대로 그릴수 있는 행의 limit가 걸려있는 부분이 있나요? 아니면 다른 문제인가요?

**Comment by neolord0** [comment]
github에서 소스를 다운로드 해서 테스트 해보세요
요즘 수정한 버그 라...

**Comment by sgh9196** [comment]
github에서 다운받아 적용한 소스입니다.

**Comment by sgh9196** [comment]
자답입니다. 어제 소스를 받아서 최신인줄 알았는데 다시 받으니 이 문제는 해결되었습니다.. 감사합니다..

혹시 이 이슈 관련해서 어떤부분이 수정되었는지 알고싶은데 알 수 있을까요?

**Comment by neolord0** [comment]
2035 행을 넘어가면서.. 특정 레코드가 4095 bytes 을 넘는데요..
레코드가 4095 바이트을 넘을 때 처리를 한 겁니다..

**Comment by sgh9196** [comment]
답변 감사합니다.
