### ISSUE TITLE
안녕하세요. 머리말과 꼬리말을 추가하는 예제가 궁금합니다.

### ISSUE THREAD

**Issue by dgahn** [neolord0/hwplib#132]
안녕하세요. 개발해주신 라이브러리를 잘 사용하고 있는 개발자입니다.

머리말과 꼬리말을 추가하는 예제를 좀 부탁드려도 될까요?

추가적으로 머리말과 꼬리말에 표를 넣을 수 있는지도 궁금합니다.

**Comment by neolord0** [comment]
예제 추가 했습니다. 소스 전체를 다시 받으시고 테스트 해 보시길..
Inserting_HeaderFooter.java 

머리말/꼬리말에 표 추가하는 건 특별한게 없습니다.
머리말/꼬리말에 포함된 문단에 표를 추가하면 됩니다.

**Comment by dgahn** [comment]
감사합니다. 덕분에 고민이 해결될거 같네요. 좋은 저녁 되세요!

**Comment by dgahn** [comment]
개발자님 꼬리말을 추가하는 것에 대해서는 해결을 했는데 2가지 기능을 구현하는데 어려움을 겪고 있어 문의드립니다.

1. 꼬리말에 borderFillId를 부여하는 기능
2. 꼬리말에 현재쪽 수를 부여하는 기능

답변 미리 감사합니다.

**Comment by neolord0** [comment]
1. 꼬리말에 borderFillId을 부여하는 기능이  무엇이지 모르겠네요..

2. 필드로 들어가는 거 같습니다 만..

저도 잘 모르는 부분이라.. 시간이 걸릴듯하네요.. 

급하면 직접 해보세요.. 
원하는 기능을 한글 프로그램으로 설정해서 파일로 저장한 후에, 
라이브러리로 읽어서 분석한 후에.. 만들어 보세요.  
하시다가 궁금한 점 있으시면.. 질문하시고요.
