### ISSUE TITLE
DocInfo write시에 순서에 의한 파일손상 문의

### ISSUE THREAD

**Issue by tjguswns33** [neolord0/hwplib#134]
변경 내용 추적이 사용된 문서를 읽고 쓰기를 진행하다 발견하여 문의드립니다!
![image](https://user-images.githubusercontent.com/59809631/110740543-9277ab00-8276-11eb-89f1-b432a10ce030.png)

테스트파일    
 - [테스트파일.zip](https://github.com/neolord0/hwplib/files/6120642/default.zip)

테스트 코드 입니다.
```
	public static void main(String[] args) throws Exception {
		String filename = "C:\\Users\\Desktop\\테스트파일.hwp";
		File f = new File(filename);
		HWPFile hwp = HWPReader.fromFile(filename);
		File toFile = new File(f.getParentFile(), "_" + f.getName());
					
		HWPWriter.toFile(hwp, toFile.getAbsolutePath());	
	}
```

변경 추적이 사용된 문서를 읽고 쓰기를 진행하면 파일이 손상되어 안열리는 현상이 발생하여 문의드립니다!

원인이라고 생각되는 부분을 찾아서 작성해 보았습니다. 검토 부탁드립니다!

ForDocInfo.write 시 아래 이미지에 빨간줄 하위부분이 순서?와 레벨?이 맞지 않아서 그런것 같습니다.
![image](https://user-images.githubusercontent.com/59809631/110741111-7e807900-8277-11eb-91ef-2f9ad6ef44c6.png)

kr.dogfoot.hwplib.writer.docinfo.ForDocInfo.java
![image](https://user-images.githubusercontent.com/59809631/110742848-6ceca080-827a-11eb-9dab-0c772f5e2e1a.png)

write 테스트 소스
```
public void write(DocInfo docInfo, StreamWriter sw) throws Exception {
        this.docInfo = docInfo;
        this.sw = sw;

        documentProerties();
        idMappings();

        sw.upRecordLevel();

        binData();
        faceName();
        borderFill();
        charShape();
        tabDef();
        numbering();
        bullet();
        paraShape();
        style();
        memoShape();
        trackChangeAuthor();
        trackChange2();
        
        sw.downRecordLevel();

        docData();
        forbiddenChar();
        compatibleDocument();
        
        sw.upRecordLevel();

        layoutCompatibility();

        sw.downRecordLevel();

        distributeDocData();
        
        sw.upRecordLevel();

        trackChange();
        
        sw.downRecordLevel();
    }
```

**Comment by neolord0** [comment]
음.. 그러네요.. 
이 코드를 생성할 당시에 포맷 공개 문서에서는 이 쪽 부분이 완벽하지 않아서  추측해서 만들었습니다. 
새버전 포맷 공개 문서에서 아떤 내용이 변경 됐는지 전부 확인하지 못 했는데..
이 부분이 완벽하게 정리 됐군요..

버그 찾아 주셔서.. 감사합니다.
반영하겠습니다.
