### ISSUE TITLE
한글 문서를 읽어 들이지 못하는거 같습니다.

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#135]
hwp 파일에 그려진 Section이 총 30000 페이지입니다.

HWPReader.fromFile("한글파일경로");

위 코드를 사용하여 30000페이지가 그려진 한글파일을 읽으려고 하는데

java.lang.Exception: cell's list header does not exist. 에러가 발생하고있습니다.

Debug를 찍어보니 해당 파일를 읽는데 exception이 발생하는 것으로 확인되었습니다.

해당 문제를 해결할 수 있는 방법이 있을까요?

**Comment by neolord0** [comment]
파일을 보내주세요..
셀에 ListHeader 가 없는 본적이 없는데요..
 한번 살펴보겠습니다.

**Comment by KangSeungKu** [comment]
안녕하세요.
한글파일로 공부중인 학생입니다.
저도 같은 오류로 내용을 찾고 있던 중 해당 내용을 발견하였습니다.
오류가 해결되셨다면, 해당 방법을 구하고싶습니다.

**Comment by KangSeungKu** [comment]
해당 오류 한글 라이브러리(hwplib) 버전을 1.5에서 1.8버전으로 올리니 해결되었습니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    

--------- 원본 메일 ---------

    
        보낸사람: KangSeungKu ***@***.***>
        받는사람: neolord0/hwplib ***@***.***>
        
            참조: park.sung kyun ***@***.***>, Comment ***@***.***>
        
        날짜: 21.07.29 01:56 GMT +0900
        제목: Re: [neolord0/hwplib] 한글 문서를 읽어 들이지 못하는거 같습니다. (#135)
        
        
    
    
        

해당 오류 한글 라이브러리(hwplib) 버전을 1.5에서 1.8버전으로 올리니 해결되었습니다.
