### ISSUE TITLE
안녕하세요 이미지 관련 문의드립니다.

### ISSUE THREAD

**Issue by qkrtjdfyd12** [neolord0/hwplib#137]
선배님같은 분들이 계셔서 저도 개발을 할 수 있는 것 같습니다.

다름이 아니라 이미지 파싱을 순차적으로 하고 싶은데
bodyText 안에 paragraph마다 controlList가 있고 각 Control마다 ControlPicture로 형변환 시키고 쭉쭉
내려가면 binItemId 라는 데이터가 존재하며 그것이 한글파일의 이미지 순서라는 것까지 이해했습니다.
그런데 문제는 표 안에 배경으로 들어간 이미지는 bodyText 안에 아무리 찾아봐도 ControlPicture가 존재하지
않더라구요.  혹시 ControlTable 안에 그 정보가 있나해서 찾아봐도 도무지 binItemId를 찾을 수가 없는데
그 데이터를 어떻게 찾아야 할지...ㅜㅜ.
답변주시면 감사드립니다.

**Comment by neolord0** [comment]
셀에 배경에 들어간 이미지는 ..
        for(Row row : table.getRowList()) {
            for (Cell cell : row.getCellList()) {
                cell. 
            }
        }
이렇게 셀을 구한 다음에..

int borderFillId = cell..getListHeader().getBorderFillId();

로 테두리/배경 객체 아이디를 구한 후..
    
BorderFill borderFill =  hwpFile.getDocInfo().getBorderFillList().get(borderFillId - 1);

DocInfo에서 테두리/배경 객체을 구한 후에..

borderFill.getFillInfo().getImageFill().getPictureInfo(().getBinItemID() 

로 binItemId을 구할 수 있습니다.

**Comment by qkrtjdfyd12** [comment]
답변 감사드립니다^^. 저도 이런걸 능숙하게 만들고 다룰 수 있는 개발자가 되고 싶네요. 존경합니다.
