### ISSUE TITLE
안녕하세요 도형 관련하여 문의드립니다.

### ISSUE THREAD

**Issue by gns05** [neolord0/hwplib#138]
안녕하세요. 다름이 아니라 한글 문서를 파싱하면서 도형 데이터를 가져와 이미지 파일로 저장하고 싶은데 가능할까요?
아니면 이미지 파일이 아니더라도 도형 데이터를 가져와서 출력할 방법이 있을까요?
답변 부탁드립니다. 감사합니다.

**Comment by neolord0** [comment]
도형은 컨트롤로 저장 되는데요.   ​

컨트롤의 내용을 이미지로 저장 하려면..  계산해서.. 그려야 합니다.
이 라이브러리에는 내용을 그리는 부분이 아직 구현되어 있지 않습니다.
도형의 모양만 그린 다면... 도형 객체를 찾아서.. 간단히(?) 그리면 되겠지만.. 
도형 안에 있는 글자나 글자 안에 포함된 또 다른 컨트롤까지 그려야 한다면.. 
HWP 파일 전체를 그리는 것과 동일한 작업을 해야 합니다.

이 부분은 아직 지원하지 않습니다.  한글 뷰어 업체에 문의하거나 
https://hanlee.io/hwp.js/demo/  참조로 만드셔야 할 거 같습니다.

**Comment by ginamsim** [comment]
답변 감사드립니다.
도형 관련해서는 더 확인을 해봐야겠네요...
그리고 혹시 텍스트 [수식] 텍스트 혹은 텍스트 [이미지] 텍스트와 같이 한 문장 안에 텍스트와 컨트롤이 함께 구성되어 있을 때 입력된 순서대로 가져오는 방법이 있을까요? 현재 제가 테스트한 부분에서는 Paragraph의 getNormalString과 getControlList로 텍스트와 컨트롤을 별도로 가져오다보니 문장 중간에 있는 [수식]이나 [이미지]같은 컨트롤이 텍스트의 뒤로 나오게 되어 문서와는 순서가 다르게 나오고 있어서요.
답변 부탁드립니다. 감사합니다.

**Comment by neolord0** [comment]
Paragraph.getControlList()는 컨트롤이 생성된 순서대로 저장됩니다.
컨트롤의  [위치], [글자 처럼], [본문과의 배치] 등에 속성 따라 .. 문서에서 나오는 순서가 달라집니다. 
이 순서를 알아내는 게.. HWP 파일을 그리는 핵심입니다.

정확한 위치를 알려면, 문단 속성과 글자 속성, 그리고, 컨트롤에 배치에 대한 속성을 모두 적용하여 그려야 합니다.
위에서 말씀 드렸듯이, 이 부분은 아직 지원하지 않느니 한글 뷰어 업체에 문의 하시길 바랍니다. 

저도 회사일로 HWP 그리기를 하고 있긴 한데요.
이 기능은 나중에는 품질을 높이기 위해서는 개발인력이 어느 정도 투입할 필요가 있고 
그렇게 되면 상업적인 라이센스로 가야하지 않나 고민 중입니다.
