### ISSUE TITLE
텍스트 자동번호 관련 문의드립니다.

### ISSUE THREAD

**Issue by qkrtjdfyd12** [neolord0/hwplib#141]
안녕하세요. 텍스트 추출 관련해서 여쭤보고 싶은게 있는데

문서에서 자동번호가 매겨져 있는 경우 Extracting_Text 예제를 돌려보면

텍스트만 추출되고 자동으로 매겨지는 I, 1.  이런 정보들은 추출이 안되던데

혹시 bodyText말고 docInfo에서 정보를 찾아와서 별도로 텍스트를 만들어 줘야 하는건가요?? 

(예제)
I. 기술 개요
  1. 기술의 정의
  2. 기술의 특징
  3. 기술의 분류
      상위 기술 분류
      동종 기술 분류
      하위 기술 분류

**Comment by neolord0** [comment]
문단 번호, 글머리표 기능은 아직 지원하지 않습니다.
이 부분은 생각할 부분이 많아서 시간 날 때 천천히 하려고 했는데..
계속 바쁘네요.

직접 해 보실 려면... 
Paragraph(문단) 객체에서  getHeader().getParaShapeId()로 문단 모양 Id을 구한 후에..
DocInfo 아래에  문단 모양 리스트에서 아이디 해당하는 ParaShape(문단 모양) 객체를 구한 다음에
ParaShpae객체에 getParaHeadID()로  문단 번호 나 글머리표 Id을 구하고 
DocInfo 아래에  문단 번호 리스트나 글머리표 리스트에서 아이디 해당하는 Numbering(문단 번호) 객체나 Bullet(객체)를 구해야 합니다.
Numbering(문단 번호) 객체나 Bullet(객체)를 가지고 처리하여 문단 앞에 붙여주면 됩니다.
