### ISSUE TITLE
hwpx 파일 관련 문의입니다.

### ISSUE THREAD

**Issue by qkrtjdfyd12** [neolord0/hwplib#142]
안녕하세요~.

바쁘실텐데 문의를 드릴 때마다 친절한 답변 정말 감사드립니다. ^^

한글 파일을 hwpx 파일로 저장해서 변환하면 POI 라이브러리에서 파일을

읽어드리지 못하는 것 같은데 혹시 방법이 있나요??

**Comment by neolord0** [comment]
hwpx 는 hwp과는 완전히 다른 zip파일 형태 입니다. 

이 라이브러리는 지원하지  않습니다.
완전히 다른 라이브러리를 만들어야 합니다.
