### ISSUE TITLE
이슈라기보다는 질문입니다. 지원되는 HWP버전을 알고 싶네요.

### ISSUE THREAD

**Issue by SeanKi** [neolord0/hwplib#144]
HWP 5.0 이상만  되는 건가요?
아래아 한글 의 프로그램 버전 기준으로 어느 버전에서 작성 한 것부터 가능 한지 알 수 있을까요?

**Comment by neolord0** [comment]
지금 사용중인 hwp 파일은 ..  한글 97에서 사용한 3.0 버전과..  2000년 이후에 만들어진.. 5.0버전으로 나눌 수 있으나.
이 파일 버전과 한글 프로그램의 버전은 특별한 상관관계가 없는 걸로 알고 있습니다. 
한컴은 자체적으로 업데이트를 통해.. 한글 프로그램의 버전에 관계없이.. 모든 한글 파일 포맷을 동일하게
처리하도록 지원하고 있는 걸로 알고 있습니다.
