### ISSUE TITLE
쪽 정보 복사 기능

### ISSUE THREAD

**Issue by Eintior** [neolord0/hwplib#146]
쪽 정보를 복사하는 기능이 없길래 작성해보았습니다.

원래는 ParagraphCopier 에 넣어볼까 했는데 쪽 정보는 section 첫번째 파라그래프에만 들어가니

일반적으로 사용했을 때 오류 발생 여부에 대한 테스트가 미흡해서 그냥 Copier만 작성했습니다..

확인부탁드립니다.
<br>
>수정
/hwplib/src/main/java/kr/dogfoot/hwplib/tool/blankfilemaker/SectionDefineAdder.java
기존 pageBorderFill에서 BottomGap 처리 대신 setBorderFillId 으로 잘못 처리중입니다
```java
    private static void pageBorderFill(PageBorderFill pageBorderFill) {
        pageBorderFill.getProperty().setValue(1);
        pageBorderFill.setLeftGap(1417);
        pageBorderFill.setRightGap(1417);
        pageBorderFill.setTopGap(1417);
        pageBorderFill.setBottomGap(1417); 
        pageBorderFill.setBorderFillId(1);
    }

```
<br>

>추가
/hwplib/src/main/java/kr/dogfoot/hwplib/tool/paragraphadder/control/SectionDefineCopier.java
[SectionDefineCopier.zip](https://github.com/neolord0/hwplib/files/6698143/SectionDefineCopier.zip)

**Comment by neolord0** [comment]
보내주신 소스를 검토해보니..  바탕쪽 정보(BatangPageInfo) 부분이 빠져서 추가해서 올렸습니다.

위에 님이 설명해 주신 것 처럼.. 구역정의 컨트롤은 구역 문단 리스트의 첫 문단에만 존재합니다.
ParagraphCopier는, 특정한 문단 리스트를 다른 문단 리스트에 복사해 넣는다는 목적으로 제작되었습니다.
그 때문에, 구역정의 컨트롤에 대한 복사기능을 만들지 않았습니다. 
섹션 전체(페이지 크기가 다른) 를 복사할 때 사용할 수 있으나, 특정한 문단 리스트를 다른 문단 리스트에 복사해 넣을 때는
사용하지 않는 맞으니, 주의해서 사용하시길 바랍니다.

**Comment by Eintior** [comment]
SectionDefineCopier 추가 확인했습니다.
감사합니다.

위에 Adder 수정사항은 파일로 안올려서 누락된 것 같아 추가로 올립니다

/hwplib/src/main/java/kr/dogfoot/hwplib/tool/blankfilemaker/SectionDefineAdder.java
[SectionDefineAdder.zip](https://github.com/neolord0/hwplib/files/6713760/SectionDefineAdder.zip)

**Comment by neolord0** [comment]
보내주신 SectionDefineAdder.zip을 봤는데.. 현재 파일이랑 동일한데요..
잘 못 보내신 건지?? 아니면.. ??

**Comment by Eintior** [comment]
https://github.com/neolord0/hwplib/blob/master/src/main/java/kr/dogfoot/hwplib/tool/blankfilemaker/SectionDefineAdder.java

```java
    private static void pageBorderFill(PageBorderFill pageBorderFill) {
        pageBorderFill.getProperty().setValue(1);
        pageBorderFill.setLeftGap(1417);
        pageBorderFill.setRightGap(1417);
        pageBorderFill.setTopGap(1417);
        pageBorderFill.setBorderFillId(1417);
        pageBorderFill.setBorderFillId(1);
    }
```

최신 코드에는 setBorderFillId 선언이 두 번 되어있습니다
제 파일도 그렇게 되있나요? 이상하네..

**Comment by neolord0** [comment]
아.. 그렇군요.
실수 했네요. 버그 찾아주셔서 감사합니다.

**Comment by Eintior** [comment]
넵 수고하셨습니다
