### ISSUE TITLE
파일열기가 안되는 파일입니다. 확인 부탁드립니다.

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#147]
파일열기가 안되는 파일입니다. 확인 부탁드립니다.
수고하세요.
[공고문.zip](https://github.com/neolord0/hwplib/files/6827403/default.zip)

**Comment by neolord0** [comment]
제가 테스트 한 결과입니다.
공고문01 : 열림
공고문02 : HWPML
공고문03 : HWPML
공고문04 : HWPML
공고문05 : HWP3.0 (97포맷)
공고문06 : HWP3.0 (97포맷)
공고문07 : HWP3.0 (97포맷)
공고문07 : HWP3.0 (97포맷)
공고문08 : HWPML
공고문09 : 열림
공고문10 : 파수 DRM으로 암호화 된 파일(한글 프로그램에서도 안 열림)
공고문13 : 열림
공고문14 : 열림

HWPML 파일이나, HWP3.0파일은 이 라이브러리의 범위 밖에 기능이고, 
공고문01, 09, 13, 14은 라이브러리를 업데이트 하신 후에 다시 테스트 해주세요.

**Comment by osc91** [comment]
네. 알겠습니다.
