### ISSUE TITLE
안녕하세요 한글파일 다운로드 시 질문있습니다!

### ISSUE THREAD

**Issue by dntjr031** [neolord0/hwplib#149]
안녕하세요 오픈소스 라이브러리를 제공하여 주셔서 감사합니다!

현재 한글파일을 만들어서 다운로드할 수 있게 서비스 하려고 합니다.

`HWPWriter.toFile()`을 이용하면 로컬에 정상적으로 저장이 되지만
`HWPWriter.toStream()`을 이용하여 outputStream으로 response를 보내게 되면 파일은 열리지만 안에 내용들이 다 깨지더라고요.
(HWPWriter.toFile() 으로 파일생성후 FileOutputStream 으로 보내도 마찬가지입니다.)

### Example
![image](https://user-images.githubusercontent.com/63115449/125931142-c052c33a-51a7-40e8-b7ad-e5722e8b4ff9.png)
example 폴더에 있는 target.hwp 로 테스트

**Comment by neolord0** [comment]
음..  web response 스트림으로 내보내는 건 아직 테스트 해 본 적이 없어서 정확히는 알지 못하나..
FileOutputStream는 잘 동작하는 것을 확인 했습니다.
 
web쪽에..  컨텐츠 타입, 인코딩.. 등을 살펴보시고.. 
해결 안 되시면 ... toFile()로 저장된 파일과 toStream()으로 저장된 파일을  올려주세요.

**Comment by dntjr031** [comment]
답변 감사드립니다!
기본적으로 utf-8로 인코딩을 사용하는데
POST 로 넘기니 저렇게 깨진것이었고 GET으로 여청하니 잘 받아와지더라고요.
아마 웹쪽 문제인듯 싶습니다.
