### ISSUE TITLE
한글파일 내용을 html 형태로 변환하는 기능도 있는지요?

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#15]
한글파일 내용을 html 형태로 변환하는 기능도 있는지요?
답변 부탁드립니다. 

수고하세요 ^^

**Comment by neolord0** [comment]
다른 파일로 변환하려면 한글 파일의 내용을 정확히 그릴 수 있어야 하는데, 이 부분은 아직 파악하지 못했습니다. 이 부분은 지원하지 않습니다.
