### ISSUE TITLE
한글파일에서 줄바꿈 적용하는 법

### ISSUE THREAD

**Issue by werty2938** [neolord0/hwplib#150]
안녕하세요.
jsp textarea에서 내용을 입력받아 BlankFileMaker를 이용해 빈 hwp파일을 생성한 후 해당하는 내용을 저장하는 페이지를 만들고 있습니다. 
java단에서 출력을 해보면 textarea에서 쓴 줄바꿈이 적용이 되어 출력이 되고, 이를 통해 한글 파일에 저장할 때 한글파일에도 똑같이 줄바꿈을 적용하려고 하는데 sample_hwp나 src에서 어느부분을 참고하면 되는지 알 수 있을까요??

**Comment by neolord0** [comment]
줄 바꿈 하는 방법은 두가지 입니다.
1) 문단을 그만큼 만드는 방법
2) 개행 제어 문자를 넣는 방법

지금은...  딱 들어맞는 샘플이 없습니다.
한글 프로그램으로 원하는 hwp 파일(줄바꿈이 들어간...)을 만든 후, 
라이브러리로 읽어서 분석한 후에, 동일하게 만드는 방법을 추천 드립니다.

해 보시고 모르는 부분 있으시면 다시 질문 해 주세요.

**Comment by werty2938** [comment]
답변 감사합니다. 말씀하신 방법으로 해보겠습니다. 감사합니다 :)
