### ISSUE TITLE
테이블 셀 안에 이미지 객체 넣는 방법을 알고 싶습니다.

### ISSUE THREAD

**Issue by baboototo** [neolord0/hwplib#151]
안녕하세요.
HWP 라이브러리를 아주 잘 사용하고 있습니다. 감사합니다.
샘플 코드(Inserting_Table_WithImageBack)를 이용해 테이블 셀에 이미지를 백그라운드화 해서 사용하고 있습니다.
현재 테이블 셀에 백그라운드 이미지를 객체화 해서 이미지 크기를 사용자가 직접 변경할 수 있도록 작업중에 있습니다.
샘플 코드(Inserting_Image) 이용해 이미지 객체화 까지는 진행 했습니다.

혹시 테이블 셀의 위치에 이미지 객체를 넣고 싶은데 어떻게 넣을 수 있을까요?
테이블 셀 위치를 어떻게 해야 알수 있는지 문의 드립니다.

이미지 가로/세로 길이는 구해져 있는데~ 테이블 셀 위치 파악이 안되서 문의드립니다.

**Comment by neolord0** [comment]
이미지 컨트롤은... ControlPicture로 추가할 수 있습니다.
셀 안에.. 문단에 ControlPicture을 추가하는 방법으로 가능합니다..

Inserting_Image라는 예제를 참고 하시면 좋을 듯 합니다.  
사각형 컨트롤(ControlRectangle) 에 이미지 배경을 설정하여.. 본문에 삽입하는 예제인데..
ControlRectangle과 ControlPicture은 다르고, 본문과 셀안에 삽입해야 하는 부분은 다르지만,
기본적으로 이미지를 추가하는 부분과 문단 안에.. 컨트롤을 삽입하는 부분은 동일합니다.

해보시고 궁금한 부분이 있으시면.. 다시 질문해 주세요.

**Comment by baboototo** [comment]
보내주는 메일 내용으로 참고해서 처리 했습니다.
테이블 안에 텍스트 문단 위치를 잡고 이미지 객체를 생성해서 처리 하니까
셀 위치에 들어 가더라구요.
덕분에 잘 해결 했습니다.
감사합니다^^
