### ISSUE TITLE
테이블 셀안의 텍스트 치환시 개행문자 처리에 대해

### ISSUE THREAD

**Issue by vkcorp** [neolord0/hwplib#152]
테이블 셀에 필드이름을 지정하여 검색한 다음, 내부 문자열을 추가 중에 있습니다.
헌데 개행문자에 대해 처리되지 않고 모두 한 줄에 출력이 되고 있어 문의 드립니다.
예를들어, 

ABC
123

이라는 문자열을 넣으면

ABC123

으로 한줄에 출력이 됩니다. 이를 위한 코드는 아래처럼

  Cell c = cellList.get(0);
  Paragraph firstPara = c.getParagraphList().getParagraph(0);
  ParaText paraText = firstPara.getText();
  if (paraText == null) {
      firstPara.createText();
      paraText = firstPara.getText();
  }
  paraText.addString(newText)

와 같이 사용중입니다. 
한글에서는 /r/n 대신에 /n 만을 개행문자로 사용중인듯 하여
전달하는 문자열은 "ABC\n123"으로 사용하고 있습니다.

이와 다르게 셀의 필드이름이 아닌, 내부에 누름틀을 추가하고 사용하는 경우에는
2줄로 입력이 되었습니다.
해서 현재는 누름틀을 추가하는 코드를 비교확인해 보고 있습니다만...

**Comment by neolord0** [comment]
HWP는 여러줄인 텍스트를 만들때..
개행 제어 문자를 넣거나, 문단을 여러개 넣어서 표현합니다.
한글 프로그램으로 원하는 형태를(여러 줄인 텍스트) 만든 후,
라이브러리로 읽어 보시면.. 어떻게 만드는지 알수 있으리라 생각됩니다.

**Comment by vkcorp** [comment]
단순히 문자열 내부의 특정 코드로 처리하는 것이 아닌,
말씀하신 데로 문단으로 처리하는 형태로 진행하는 것으로 해야할 것 같습니다~
