### ISSUE TITLE
HFT 폰트도 글자모양으로 변경이 가능한가요?

### ISSUE THREAD

**Issue by sy1234567890** [neolord0/hwplib#153]
안녕하세요

글자 모양 변경 관련 샘플파일 Inserting_CharShape.java 이 소스에서

fontName을 중고딕이나 신명조로 변경하여 테스트 해보았는데 글자모양이 적용이 안되는데..

중고딕이나 신명조 같은 HFT 폰트도 글자모양으로 변경이 가능한가요?

**Comment by neolord0** [comment]
음.. 한글폰트(HFT)를 어떻게 설정하는 지 정확하게 알 수 없지만..
![image](https://user-images.githubusercontent.com/24711108/131785743-2b4f7bd6-3f24-48cc-9da2-440ee6c79de1.png)
제가 한글 폰트인  "함초롱바탕" 세팅하고 읽어보니.. 위와 같이 설정되는 군요.
아마도 비슷한 방식으로 하면 될 듯 합니다.

한글에서 "중고딕"이나 "신명조"로 설정된 hwp파일 만들어서.. 확인 후 비슷하게 만들어 보시면 될 듯 합니다.
