### ISSUE TITLE
표의 ROW가 많아질경우...

### ISSUE THREAD

**Issue by EricHanHJ** [neolord0/hwplib#154]
표 하나의 ROW가 많아져서 2000개 이상 혹은 48page이상이 되도록 넘칠경우,
파일이 열리지 않습니다.
혹시 해결 할 수 있는 방법이 있을까요?

**Comment by neolord0** [comment]
이 문제... 올해 2월 달에.. 패치한 걸로 알고 있는데요..
최신 버전으로 다시 받아서 테스트 해보세요..

**Comment by EricHanHJ** [comment]
> 이 문제... 올해 2월 달에.. 패치한 걸로 알고 있는데요..
> 최신 버전으로 다시 받아서 테스트 해보세요..

감사합니다 해결되었습니다!
