### ISSUE TITLE
특정한 열을 전체 삭제하는 경우, 삭제 후의 작업에 대해

### ISSUE THREAD

**Issue by vkcorp** [neolord0/hwplib#155]
덕분에 하나씩 테스트 하면서 작업을 진행해가고 있습니다만,
이번에는 테이블에서 특정 열 전체를 삭제하는 것을 시도해 보고 있습니다.

열의 삭제의 경우는 기존의 TableCellMerger.java 코드에서
Merge 부분을 제외하고 삭제하고 셀의 수를 업데이트 하는 부분을 처리해 주면 될듯하여
시도해 보고 있습니다.

            //resetMergedCell();
            removeRestCell();
            resetCellCountOfRow();

구조를 확인해 봐도 삭제 그 자체는 정상적으로 진행된듯 한데, 
업데이트된 문서가 정상적으로 열리지 않고 있습니다.
행이나 열을 삭제하는 경우 추가적으로 업데이트 해야할 정보가 있다는 것을 다른 분들의 질문을 통해
어느 정도 인지는 하고 있으나 정확히 어떤 부분이 필요할지 잘 모르겠습니다.

열의 경우 TableCellMerger 에서와 같이, 열의 개수만 업데이트 해주는 것으로는 부족 할까요 ?

**Comment by vkcorp** [comment]
테이블(5x3)을 샘플로 하나 만들어 3번 컬럼을 수동으로 삭제하여 구조 비교를 한 번 해보았습니다.
아.. 예상보다 컬럼을 삭제하면 많으게 바뀌네요. 이중에서 한글앱에서 자동으로 
갱신 해주는 속성들도 있을지는 모르겠지만 일단은 변화가 큽니다.


Diff:
* changes on kr.dogfoot.hwplib.object.HWPFile/ :
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/header.width' changed: '41950' -> '33560'
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0.cellList' collection changes :
     4. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/0/listHeader/property.value' changed: '67108896' -> '32'
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/2/paragraphList/paragraphList/0/text/charList/0.code' changed: '51' -> '52'
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/3/paragraphList/paragraphList/0/text/charList/0.code' changed: '52' -> '53'
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.borderFillId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.bottomMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.colIndex' value '4' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.colSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.height' value '282' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.leftMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.paraCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.rightMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.rowSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.textWidth' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.topMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader.width' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/listHeader/property.value' value '32' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList.paragraphList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/charShape.positionShapeIdPairList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/charShape/positionShapeIdPairList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/header.charShapeCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/header.characterCount' value '2' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/header.lastInList' value 'true' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/header.lineAlignCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/header.paraShapeId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg.lineSegItemList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.distanceBaseLineToLineVerticalPosition' value '850' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineSpace' value '600' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.segmentWidth' value '7368' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.textPartHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0/tag.value' value '393216' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/text.charList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/text/charList/0' removed
     1. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/text/charList/1' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/text/charList/0.code' value '53' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/4/paragraphList/paragraphList/0/text/charList/1.code' value '13' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1.cellList' collection changes :
     4. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.borderFillId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.bottomMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.colIndex' value '4' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.colSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.height' value '282' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.leftMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.paraCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.rightMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.rowIndex' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.rowSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.textWidth' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.topMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader.width' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/listHeader/property.value' value '32' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList.paragraphList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/charShape.positionShapeIdPairList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/charShape/positionShapeIdPairList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/header.charShapeCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/header.characterCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/header.lastInList' value 'true' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/header.lineAlignCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/header.paraShapeId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg.lineSegItemList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.distanceBaseLineToLineVerticalPosition' value '850' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineSpace' value '600' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.segmentWidth' value '7368' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.textPartHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0/tag.value' value '393216' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2.cellList' collection changes :
     4. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.borderFillId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.bottomMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.colIndex' value '4' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.colSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.height' value '282' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.leftMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.paraCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.rightMargin' value '510' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.rowIndex' value '2' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.rowSpan' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.textWidth' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.topMargin' value '141' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader.width' value '8390' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/listHeader/property.value' value '32' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList.paragraphList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/charShape.positionShapeIdPairList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/charShape/positionShapeIdPairList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/header.charShapeCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/header.characterCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/header.lastInList' value 'true' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/header.lineAlignCount' value '1' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/header.paraShapeId' value '3' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg.lineSegItemList' collection changes :
     0. 'kr.dogfoot.hwplib.object.HWPFile/#bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0' removed
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.distanceBaseLineToLineVerticalPosition' value '850' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.lineSpace' value '600' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.segmentWidth' value '7368' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0.textPartHeight' value '1000' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/4/paragraphList/paragraphList/0/lineSeg/lineSegItemList/0/tag.value' value '393216' unset
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/table.cellCountOfRowList' collection changes :
     0. '5' changed to '4'
     1. '5' changed to '4'
     2. '5' changed to '4'
  - 'bodyText/sectionList/0/paragraphList/2/controlList/0/table.columnCount' changed: '5' -> '4'
  - 'docInfo/documentProperties/caretPosition.listID' changed: '1' -> '3'

(참고로, 비교 자체는 눈으로 하나씩 트리 확인하기 어려워 Javer를 사용하여 보았습니다.)

**Comment by vkcorp** [comment]
일단 원인은 찾은 것 같습니다.
수작업으로 컬럼을 삭제하는 것과, removeRestCell() 처럼 적용해 본 것과의 차이는
컬럼의 인덱스를 재설정하는 것이었습니다.
removeRestCell()을 이용한 삭제는 내부적으로 컬럼의 인덱스가 특정 셀 이후 +1이 되네요.

- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/2/listHeader.colIndex' changed: '2' -> '3'
- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/3/listHeader.colIndex' changed: '3' -> '4'

- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/2/listHeader.colIndex' changed: '2' -> '3'
- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/1/cellList/3/listHeader.colIndex' changed: '3' -> '4'

- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/2/listHeader.colIndex' changed: '2' -> '3'
- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/2/cellList/3/listHeader.colIndex' changed: '3' -> '4'

이를 재조정 해주면 정상적으로 출력이 됩니다.
이 외에 변한 값들 중, 정확히 무슨 의미인지는 모르나 아래 값도 수작업애서 했던 것과 같이 강제로
적용해줘야 하나 봅니다.

- 'bodyText/sectionList/0/paragraphList/2/controlList/0/rowList/0/cellList/0/listHeader/property.value' changed: '67108896' -> '32'
- 'docInfo/documentProperties/caretPosition.listID' changed: '1' -> '3'

아마도 캐럿 위치 정보인듯한, caretPosition.listID 는 변경안해줘도 상관없는듯 합니다.

**Comment by neolord0** [comment]
음.. 열을 삭제하려면... 
첫 번째로 체크해야 하는 부분은 열의 셀 들이 병합되어 있는지 여부를 확인하고.
병합된 셀이 있으면...처리를 해서.. 병합된 셀이 없도록 해야 합니다. (병합된 셀을 나눠서 병합되지 않게 처리함..)

이렇게 처리해야 삭제할 열에 병합된 셀이 없도록 처리한 후에..열을 삭제할 수 있습니다.  

열을 삭제하기 위해서는 3부분을 설정해야 합니다.

ControlTable.getRowList()에서 각 행 별로 열에 속하는 셀을 삭제해야 합니다.
for(Row row : table.getRowList()) {
     for (Cell cell : row.getCellList()) {
          if (cell.getListHeader().getColIndex() == deletingColIndex) {
              row.getCellList().remove(cell);
              break;
         }
     }
} 

그리고,  ControlTable.getTable().getCellCountOfRowList() 에 각 행의 셀 갯수에 1를 빼줍니다.

ArrayList<Integer> newCellCountOfRow = new ArrayList<>();
for (int cellCount : table.getTable().getCellCountOfRowList()) {
     newCellCountOfRow.add(cellCount - 1);
}
table.getTable().getCellCountOfRowList().clear();
for (int cellCount : newCellCountOfRow) {
table.getTable().getCellCountOfRowList().add(cellCount);
}

마지막으로, ControlTable.getTable().setColumnCount() 을 다시 설정합니다.
table.getTable().setColumnCount(table.getTable().getColumnCount() - 1);

이렇게 하면 될 듯 합니다.

**Comment by vkcorp** [comment]
제가 확인하지 못했던 부분에 대해 알려주셔서 감사합니다!
그리고 세부적인 절차에 대해 안내를 해주신 친절한 메일도, 상세하게 설명해주신 부분이라 
저 같이 처음 해보는 다른 분들에게도 도움이 될것 같아
아래에 추가로 기록을 남겨 두어도 될지 모르겠습니다만, 혹 삭제해야 하는 부분이라면 알려주시면 삭제하도록 하겠습니다.

---------------------------------------------------------------------------------------------------------------------------

열을 삭제하려면...
첫 번째로 체크해야 하는 부분은 열의 셀 들이 병합되어 있는지 여부를 확인하고.
병합된 셀이 있으면...처리를 해서.. 병합된 셀이 없도록 해야 합니다. (병합된 셀을 나눠서 병합되지 않게 처리함..)

이렇게 처리해야 삭제할 열에 병합된 셀이 없도록 처리한 후에..열을 삭제할 수 있습니다.

열을 삭제하기 위해서는 3부분을 설정해야 합니다.

ControlTable.getRowList()에서 각 행 별로 열에 속하는 셀을 삭제해야 합니다.
for(Row row : table.getRowList()) {
for (Cell cell : row.getCellList()) {
if (cell.getListHeader().getColIndex() == deletingColIndex) {
row.getCellList().remove(cell);
break;
}
}
}

그리고, ControlTable.getTable().getCellCountOfRowList() 에 각 행의 셀 갯수에 1를 빼줍니다.

ArrayList newCellCountOfRow = new ArrayList<>();
for (int cellCount : table.getTable().getCellCountOfRowList()) {
newCellCountOfRow.add(cellCount - 1);
}
table.getTable().getCellCountOfRowList().clear();
for (int cellCount : newCellCountOfRow) {
table.getTable().getCellCountOfRowList().add(cellCount);
}

마지막으로, ControlTable.getTable().setColumnCount() 을 다시 설정합니다.
table.getTable().setColumnCount(table.getTable().getColumnCount() - 1);

이렇게 하면 될 듯 합니다.
