### ISSUE TITLE
TestMakingCharShape 어디있나요?

### ISSUE THREAD

**Issue by jclab-joseph** [neolord0/hwplib#159]
안녕하세요.

이미지를 추가하는 것 때문에 TestMakingCharShape 예제를 찾고 있는데 파일이 없는거 현재 같습니다.

어디서 다운받을 수 있을까요?

감사합니다.

**Comment by neolord0** [comment]
kr.dogfoot.hwplib.sample.Inserting_CharShape 에 있습니다.
전에 이름을 변경한 적이 있는데.. 변경하기 전.. 이름인 거 같습니다.

**Comment by jclab-joseph** [comment]
감사합니다~
