### ISSUE TITLE
한글파일을 HTML파일로 저장

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#16]
혹시 한글파일을 HTML파일로 저장하는것은 가능한지요?
HwpCtr 의 saveAs 같은 기능이 있는지 궁금합니다.

**Comment by neolord0** [comment]
이 부분은 아래에 답변과 동일합니다.
아직 구현하지 못하고 있습니다.

HwpCtr은 한글 프로그램(HWP.EXE)을 실행시켜서 기능하는 OLE Automation ActiveX 입니다.
한글 프로그램(HWP.EXE)에서야 당연히.. hwp 파일을 컨트롤, 글자들의 위치를 계산해서 그릴 수 있고
그 위치정보로 다른 파일로 저장이 가능하겠지만, 전 아직 이 부분은 구현하지 못 했습니다.
