### ISSUE TITLE
Para의 Text 변경 후 "문서 보안 설정" 문제

### ISSUE THREAD

**Issue by jclab-joseph** [neolord0/hwplib#160]
안녕하세요.

```java
        paragraph.getText().getCharList().clear();
        paragraph.getText().addString(text);
```

위와 같은 방식으로 paragraph의 문자열을 변경하였는데 변경 된 파일을 열면 아래와 같은 경고가 발생합니다.

![image](https://user-images.githubusercontent.com/88625531/141480829-62e22b4b-989e-436f-8caa-142bc9d7ea17.png)

이게 모든 상황에 발생하는 것은 아니고 문서의 특정 위치인 경우 이러는 거 같습니다.

최소한의 예제로는 재현하는게 쉽지 않아 파일과 전체 소스를 올리긴 어렵습니다.

혹시 무엇이 원인이 될 수 있는지 알 수 있을까요?

감사합니다.

**Comment by neolord0** [comment]
위 내용만으로는 판단하기 어렵습니다만.
이 에러는 한글 프로그램에 hwp 파일을 파싱하다가
오류가 의심되는 바이트 블럭을 발견 했을 경우인데....
너무 광범위합니다. 

위 내용에서 
paragraph.getText().getCharList().clear();
paragraph.getText().addString(text);
이 코드로 문단에 텍스트를 추가하는데..  특정 위치(??)가 문제인지 모르겠다고 하셨는데.

특정 위치 보다는 특정 TEXT에서 오류가 나는게. 아닐지 의심됩니다.

의심가는 특정 위치의 문단이나 text을 조금씩 줄여서 테스트해 보는 수 밖에 없습니다.
