### ISSUE TITLE
텍스트 중간에 확장컨트롤이 있을때.

### ISSUE THREAD

**Issue by liu4445** [neolord0/hwplib#161]
안녕하세요 , 

사용중에 잘 모르겠는 부분있어 혹시나하여 남겨봅니다.

텍스트중간에 하이퍼링크, 책갈피 같은 것들이 껴잇는 경우에 해당 문단의 text의 문자갯수와 
해당 문단의 CharShape의 Position 부분의 값이 차이가 나는 경우가 있습니다.
예를들어 문자의 갯수는 40개이지만, position은 52를 가리키고 있는 경우가있는데 

이러한 경우는 어떻게 해석을 해야하는 건가요?

**Comment by neolord0** [comment]
문단에 .. CharShape의 Position 값을 계산할 때...  
글자 개수로 생각하신 거 같습니다.

예를 들어... 이런 텍스트가 있을때. 
<A><B><히이퍼링크 시작><C><D><히이퍼링크끝><E> 
  1  +  1  +      1               +   1 +  1 +        1       = 6 
<E>의 Position은 일반적으로 6으로 생각하는데.. 
한글에서는 글자마다 별도의 크기(?)가 있어서.. 그걸 더해줘야 합니다.
HWPCharNormal과 HWPCharControlChar는 1을,
HWPCharControlExtend과 HWPCharControlInline는 4를 더해줘야 합니다.
그래서 
<A><B><히이퍼링크 시작><C><D><히이퍼링크끝><E> 는 
  1  +  1  +          8         +    1  +  1 +        8            =   20 로 설정해야 e의 위치가 됩니다.

**Comment by liu4445** [comment]
감사합니다!!!
