### ISSUE TITLE
특정문서를 읽는 도중 에러가 발생합니다.

### ISSUE THREAD

**Issue by sungjini78** [neolord0/hwplib#162]
첨부된 문서를 읽다가  에러가 두개 발생합니다.
글맵시 부분과 ClassCastException 오류가 발생합니다.
원인이 무엇일까요?

java.lang.NullPointerException: Cannot invoke hwplib.object.bodytext.control.gso.GsoControl.setCaption(hwplib.object.bodytext.control.gso.caption.Caption)" because "gc" is null

java.lang.ClassCastException: class hwplib.object.bodytext.control.ControlColumnDefine cannot be cast to class hwplib.object.bodytext.control.ControlSectionDefine (hwplib.object.bodytext.control.ControlColumnDefine and hwplib.object.bodytext.control.ControlSectionDefine are in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @2ed38370
[테스트.zip](https://github.com/neolord0/hwplib/files/7609394/default.zip)

**Comment by neolord0** [comment]
글맵시 컨트롤은 HWP파일 스팩 문서에 공개되지 않은 부분이라서.. 시간이 걸릴 거 같습니다.

테스트 해보니.. 간단히 끝날 거 같지 않습니다.

수정하는데로 올리겠습니다.

**Comment by neolord0** [comment]
글맵시 컨트롤 추가를 완료 했습니다.
받아서 테스트 해 보세요..
