### ISSUE TITLE
Caption 관련 질문

### ISSUE THREAD

**Issue by Bobby-m-m** [neolord0/hwplib#163]
안녕하세요. 캡션 관련하여 문의 드립니다.

캡션이 없는 표 또는 그림에 캡션을 추가하는 경우, 생성된 문서에 손상이 발생합니다.

예를 들어, 기존 캡션이 있는 표 또는 그림에 새로운 캡션 객체를 생성하여 변경하게 되면 새로 생성된 캡션 정보를 잘 반영하여 문서가 생성되지만,

기존 캡션이 없는 표 또는 그림에 위와 동일한 캡션 객체를 생성하여 변경하게 되면 생성된 문서가 손상되어 한글이 실행되지 않습니다.

캡션 객체를 새로 생성하여 대체하는 것이기 때문에 제가 생성한 캡션 객체에 문제가 있다면 두 경우 모두 반영되지 않을 것으로 생각됩니다.

따라서 다른 부분에 문제가 있을까 생각되어 문의 드립니다.

감사합니다.

**Comment by neolord0** [comment]
분석해 보니까.. Caption을 추가하면..   
CtrlHeaderGso 의 32비트 속성 값 중.. 29비트가 1로 돼 더군요.
한컴에서 제공한 HWP 포맷 문서에 누락된 부분인 거 같습니다.
해결 했습니다.
그리고,  kr.dogfoot.hwplib.sample.Making_Caption 에 캡션 만드는 예제를 추가했습니다.
참고하세요.

**Comment by Bobby-m-m** [comment]
감사합니다.
