### ISSUE TITLE
표의 계산식 추출 방법 문의

### ISSUE THREAD

**Issue by sungjini0718** [neolord0/hwplib#166]
안녕하세요 hwp 라이브러리 덕분에 많은 도움을 받고 있습니다.

표의 셀에 입력된 다른 속성들은 잘 가지고 왔는데 계산식(sum, avg 등)을 추출하지 못해서요
계산식을 추출하는 방법이 궁금합니다.

**Comment by neolord0** [comment]
표의 셀에 계산식이 있었던가요 ?? 
셀에는 계산식 속성은 없는 걸로 알고 있는데요..
혹시 셀안에.. 수식 컨트롤을 넣은 건 아닌지요 ??
hwp 파일이 없어서 정확한 내용은 알 수 없네요.
읽어 보려는 hwp파일을 올려주세요..

**Comment by sungjini0718** [comment]
[계산식.zip](https://github.com/neolord0/hwplib/files/8014646/default.zip)

파일 첨부했습니다.

**Comment by neolord0** [comment]
보내주신 파일을 보니.. 셀의 계산식은 필드를 통해.. 적용되는 군요..

특정한 표의 셀을 찾은후에.. 
셀의 첫문단에 첫번째 글자가 계산식 핃드이면, 계산식을 가진 셀로 인식하고
이 경우에 셀의 첫문단의  첫 컨트롤은 필드 컨트롤이여야 하기 때문에..
필드 컨트롤에서 원하는 정보를 빼올 수 있습니다.
소스를 참고하세요..

''java 
public class Test {

    public static void main(String[] args) throws Exception {
        HWPFile hwpFile = HWPReader.fromFile("test/계산식.hwp");

        Section section = hwpFile.getBodyText().getSectionList().get(0);
        Paragraph paragraph = section.getParagraph(0);
        ControlTable table = (ControlTable) paragraph.getControlList().get(4);
        Cell cell = table.getRowList().get(5).getCellList().get(1);
        if (hasFormula(cell)) {
            String formula = getFormula(cell);
            System.out.println(formula);
        }
    }

    private static String getFormula(Cell cell) {
        Paragraph firstParagraph = cell.getParagraphList().getParagraph(0);
        ControlField field = (ControlField) firstParagraph.getControlList().get(0);
        return field.getHeader().getCommand().toUTF16LEString();
    }

    private static boolean hasFormula(Cell cell) {
        Paragraph firstParagraph = cell.getParagraphList().getParagraph(0);
        HWPChar firstChar = firstParagraph.getText().getCharList().get(0);
        if (firstChar.getCode() == 3) {  // is field
            HWPCharControlExtend charControlExtend = (HWPCharControlExtend) firstChar;
            byte[] addition = charControlExtend.getAddition();

            if (addition[3] == '%'
                    && addition[2] == 'f'
                    && addition[1] == 'm'
                    && addition[0] == 'u') {
                return true;
            }

        }
        return false;
    }
}
''java

**Comment by sungjini0718** [comment]
자세한 답변 감사합니다.
