### ISSUE TITLE
Sample 코드 업데이트 요청

### ISSUE THREAD

**Issue by Mineru98** [neolord0/hwplib#167]
[ceddd24007](https://github.com/neolord0/hwplib/blob/ceddd24007f8aaaab98efddcd6b40228cb7e35b4/src/main/java/kr/dogfoot/hwplib/object/bodytext/control/ctrlheader/gso/TextFlowMethod.java) 커밋 이후로 Tight 맴버가 제거 되었는데 deprecated 되었는지 다른 맴버로 대체가 되었는지 샘플 코드에서 더이상 동작하지 않으니 샘플 코드가 수정이 되었으면 합니다.

[참고 코드 위치](https://github.com/neolord0/hwplib/blob/master/src/main/java/kr/dogfoot/hwplib/sample/htmltohwp/src/main/java/htmltohwp/HtmlToTableExample.java#L274)
```java
...
private void setCtrlHeaderRecord(ControlTable table) {
    ...
    ctrlHeader.getProperty().setTextFlowMethod(TextFlowMethod.Tight);
    ...
}
```

**Comment by neolord0** [comment]
수정 했습니다.
