### ISSUE TITLE
hwplib로도 캐럿을 특정위치로 이동해서 이미지를 넣는게 가능할까요?

### ISSUE THREAD

**Issue by bumjin** [neolord0/hwplib#169]
안녕하세요.

웹한글 API방식으로 사용시
InsertPicture는 현재캐럿위치에서 이미지가 추가되기 때문에
이를 위해 MoveToField를 통해 특정셀로 이동한 후 InsertPicture 를 사용했었는데

hwplib로도 캐럿을 특정위치로 이동해서 이미지를 넣는게 가능할까요?

**Comment by neolord0** [comment]
MoveToField하여 캐릿을 이동하는 방식은 아니지만..
Field가 특정한 문자열로 설정된 셀을 찾아서.. 셀에 이미지를 추가하는 방식으로 
원하는 기능을 구현할 수 있습니다.

**Comment by bumjin** [comment]
답변 감사합니다. 추가로 올라온 특정셀에 이미지 넣는 소스도 잘 참고하겠습니다.
