### ISSUE TITLE
hwp파일에서 이미지만 추출하는 방법 문의

### ISSUE THREAD

**Issue by sshi2074** [neolord0/hwplib#17]
올려주신 작업관련하여 큰 감동과 많은 도움을 받고 있습니다.
감사합니다.

초보 작업자로 하나 여쭙고 싶습니다.
HWP파일에서 이미지만 추출하고 싶습니다.

작업하신 소스를 보고 이미지를 추출하는 방법을 아래처럼 작성해 봤습니다.
추출은 잘 되는데, 실제 윈도우에서 추출된 파일을 읽어보면 이미지 파일이 읽어지지 않습니다.

가르침을 받고자 합니다.
감사합니다.

이 사이트에 말씀을 주시거나 메일로 말씀주셔도 됩니다. (연락처: sungho.shin7@gmail.com)

다시한번 감사인사 드립니다.
감사합니다.

 == 예시 ==

		String strFilePath = "c://tmp/hwp01/test-image.hwp";
		
		HWPFile hwpFile = HWPReader.fromFile(strFilePath);
		List<EmbeddedBinaryData> list = hwpFile.getBinData().getEmbeddedBinaryDataList();
		
		for(EmbeddedBinaryData e:list) {
					
			byte[] byteData = e.getData();
			
			String filePath = "c://tmp/" + e.getName();
			Path path = Paths.get(filePath);
			Files.write(path, byteData);			
		}

**Comment by neolord0** [comment]
코드 상으로는 문제가 없고, 혹시나 해서 제가 테스트 해봤는데  잘 되는 거 같던데요. 
테스트 하신 hwp 파일을 보내주실 수 있으시면... 보내주세요.. 

제가 테스트해 보겠습니다.

**Comment by sshi2074** [comment]
이유를 알았습니다. HWP 저장시 압축 옵션을 해제하니 정상적으로 추출이 잘 됩니다.
공연히 고생을 끼쳐드린것 같습니다. 송구스럽습니다.
압축저장옵션 상태를 어떻게 확인하고, 데이터를 가져오는 지 확인해 봐야 할 것 같습니다.

감사합니다.
감사합니다.

**Comment by neolord0** [comment]
압축 푸는 방법은 제가 알고 있으니.. 조망간 코드에 반영하겠습니다.
