### ISSUE TITLE
특정 문단 텍스트 변경

### ISSUE THREAD

**Issue by ggws1** [neolord0/hwplib#173]
안녕하세요.

문단에 특정 단어를 replace하려고합니다.

paragraph.getText().addString() 처럼 paragraph에 특정 단어만 변경할수 있는지 알고싶습니다.

**Comment by neolord0** [comment]
네.. 안녕하세요.

문의하신 기능은 현재 지원하지 없습니다.
가능하긴 한데.. 글자 모양 처리 등의 복잡한 부분이 좀 있어서.. 

단순히.. 문단의 특정한 부분에 문자열을 넣으려 하시는 거라면 ..
누름틀 필드라는 기능을 사용하는 것이 좋습니다.

한글 프로그램에서  문자열이 삽입될 위치에 누름틀 필드를 삽입한 후.
라이브러리에서 누름틀 필드에 문자열을 넣어주는 방법이 있습니다.

**Comment by ggws1** [comment]
답변 감사합니다. 제안해주신 방법으로 적용해보겠습니다
