### ISSUE TITLE
혹시 배포용 문서로 저장하기 기능이 되나요?

### ISSUE THREAD

**Issue by ggbbbi** [neolord0/hwplib#174]
안녕하세요 hwpLib를 이용하여 배포용 문서로 저장이 가능하지 궁금합니다..
setDeploymentDocument 라는 매소드가 있긴하던데....

**Comment by neolord0** [comment]
배포용 문서는 아직 지원하지 않습니다.

setDeploymentDocument() 함수는 
파일 헤더 부분에서 배포용인지 여부를 판단하는 값을 설정하는 부분인데요.
이 속성이 설정되었을때.  파일 본문을 배포용으로 저장되어야 하는데.. 이 부분은 아직 지원하지 않습니다.
