### ISSUE TITLE
각주에 있는 하이퍼링크 추출 방법

### ISSUE THREAD

**Issue by sungjini0718** [neolord0/hwplib#175]
좋은 라이브러리를 제공해 주셔서 항상 감사합니다.

다름이 아니라 각주에 있는 하이퍼링크 추출 방법에 대해 문의 드립니다.
ControlField에서 하이퍼링크는 CtrlField.getHeader().getCommand().toUTF16LEString() 를 이용해 추출하고 있는데
ControlFootnote는 Header에 command가 존재하지 않아 어떤 방법으로 추출해야 하는지 문의 드립니다.

**Comment by neolord0** [comment]
각주 컨트롤 안에..  내용은.. 문단 리스트에 포함되어 잇습니다.
ControlFootnote.getParagraphList()로 문단 리스트을 얻을 수 있으며..
이 문단 리스트에서 본문과 동일한 방법으로 하이퍼링크가 들어 있는 ControlField에 접근할 수 있습니다.

해보시고 안되사면.. hwp 파일과 함께.. 다시 질문해 주세요.

**Comment by sungjini0718** [comment]
감사합니다.  해결되었습니다.
