### ISSUE TITLE
책갈피와 쪽번호 매기기의 시작번호에 대해 문의드립니다.

### ISSUE THREAD

**Issue by sungjini0718** [neolord0/hwplib#176]
매번 도움을 받아 감사드립니다.

책갈피의 이름은 controlBookmark.getCtrlData().getParameterSet().getParameterItemList().get(0).getValue_BSTR() 에서 확인 했는데
책갈피의 위치(어느 글자 앞)를 확인할 수 있는 방법이 있을까요? 

그리고 쪽번호와 문단의 시작번호 추출 방법이 확인이 안되 문의 드립니다.

**Comment by neolord0** [comment]
한글파일은 섹션-문단-글자 구조로 된 문서파일로써,
파일 내용만으로는 특정 컨트롤(책갈피 컨트롤)의 위치를 n번째 섹션에  n번째 문단에 n번째 글자 위치에 있다는 정도 밖에 가져올 수 없습니다.

쪽번호와 문단의 시작번호 등은 실제로 한글 파일을 그리면서 계산해야 알 수 있는 정보입니다.

**Comment by sungjini0718** [comment]
한글에서 보면 쪽번호 매기기창의 속성에 보면 시작번호를 입력할 수 있는데
라이브러리의 속성에서 확인이 안되는 부분인가요?

![쪽번호매기기](https://user-images.githubusercontent.com/99086981/169035992-a6a16af9-78f4-4c79-b1ae-b459f2a5b931.JPG)

**Comment by neolord0** [comment]
ControlPageNumberPosition.getHeader().getNumber() 로... 구할 수 있습니다.
![image](https://user-images.githubusercontent.com/24711108/169163493-632fd9e7-e40a-4a24-8465-feded9713f6b.png)

개발툴에 debug 의 watch 기능을 사용하시면.. 편리하게 찾을 수 있습니다.

**Comment by sungjini0718** [comment]
상세한 답변 감사합니다. 많은 도움이 됬습니다.
