### ISSUE TITLE
글머리표 추출관련

### ISSUE THREAD

**Issue by KyonmoYang** [neolord0/hwplib#18]
안녕하세요. 우선, 좋은 라이브러리 만들어 주셔서 감사합니다.

한글에서 사용한 글머리표도 같이 추출될 수 있는 방법이 없을까요?

<ex>
◦ Title
-­ Sub-Title
· Text1

<현재 TestExtractingText.java결과>
Title
Sub-Title
Text1

<글머리추출 결과(원하는 결과)>
◦ Title
-­ Sub-Title
· Text1

**Comment by neolord0** [comment]
글 머리표는 아직 지원하지 않습니다. 
하려곤 하는데.. 워낙 분량이 많은 부분이라 손을 못 데고 있습니다. --;
