### ISSUE TITLE
메이븐 레파지토리에 버전

### ISSUE THREAD

**Issue by Adelin2332** [neolord0/hwplib#180]
안녕하세요!
좋은 라이브러리 만들어주셔서 잘 사용하고 있습니다.
감사합니다!

지금 메이븐에 올라가있는 버전이 1.1.0인데 다음 버전은 언제 올려주실지 궁금해서요!
1.1.0 에서 텍스트 추출이 안되는 파일이 있어서요.. ㅎㅎ

**Comment by neolord0** [comment]
네... 제가 게을러서.. --;  
조망간 올리겠습니다.
