### ISSUE TITLE
JDK 버전 문의

### ISSUE THREAD

**Issue by wansu1108** [neolord0/hwplib#189]
안녕하세요. hwplib 감사합니다. 궁금한 점이 있어 문의 드립니다

hwplib는 JDK1.8을 사용하는 거 같은데

jdk 1.7 버전으로 사용할 수 있는 방법이 있을까요??

**Comment by neolord0** [comment]
JDK 1.7 버전은 기본적으로는 지원하지 않습니다.
JDK 1.7 버전을 사용하길 원하시면.. 소스를 받아서 직접 수정해서 사용하셔야 합니다.
제 생각엔.. 많이 수정하지 않을 거 같습니다.
