### ISSUE TITLE
hwpx 파일은 지원이 가능한지 문의드립니다.

### ISSUE THREAD

**Issue by kyugwan** [neolord0/hwplib#190]
안녕하세요 
제공해주신 라이브러리로 hwp 파일 텍스트 추출 하는 부분을 잘 사용하고 있습니다.
혹시 hwpx도 지원이 가능한지 문의 드립니다.

**Comment by neolord0** [comment]
안녈하세요.
hwpx는 아직 지원하지 않습니다.
