### ISSUE TITLE
HtmlToTableExample.java 에서 생성한 표의 ParagraphAdder   add 시 문제.

### ISSUE THREAD

**Issue by loveis** [neolord0/hwplib#191]
HtmlToTableExample.java  를 통해 생성한  "result-htmltohwp.hwp" 를
Adding_Paragraph_Between_Cloned_HWPFIle.java 의  addHWPFile(  타켓 , 소스) 의 소스로 사용시
BorderFillAdder 쪽 클래스에서 java.lang.ArrayIndexOutOfBoundsException: -1  를 발생시킴니다.

한글오피스에서 생성한 표 일반 파일은 이상이 없는걸로봐선 HtmlToTableExample.java에서 표 생성시 Border 정보가 누락된 문제로 생각됩니다.

result-htmltohwp.hwp파일을 열어서 테이블선택 > 셀테두리/배경 > 각셀마다 적용/저장 후 다시 테스트 해보면 오류가 사라지네요.

소스상으로는 HtmlToTableExample.java 파일의  setCellLineBreaker 메소드에 paraShape.setBorderFillId(1); 를 추가하니 일단은 동작하네요.

    private void setCellLineBreaker(HWPFile hwpFile, Cell c) {
        ParagraphList paragraphs = c.getParagraphList();
        for (int i = 0; i < paragraphs.getParagraphCount(); i++) {
            ..
            ParaShape paraShape = hwpFile.getDocInfo().addNewParaShape();
            ..
            paraShape.setLineSpace(100); // 줄바꿈이 일어날 위치 지정.
            paraShape.setBorderFillId(1);
            ..
        }
    }
 

    private int createCharShape(HWPFile hwpFile, String color, String fontName, int ptSize, boolean bold){
       ...
       cs.setBorderFillId(1);  // 기존 0 대신 1 셋팅.
       ...

**Comment by neolord0** [comment]
소스를 살펴보니.. HtmlToTableExample 에서..  result-htmltohwp.hwp 를 만들 때  BorderFillID에 올바르지 못한 값이 설정되어 있더라고요.
sample 소스를 수정하여 올렸습니다.
