### ISSUE TITLE
한글문서 copy 시 ClassCastException 발생

### ISSUE THREAD

**Issue by hyowong** [neolord0/hwplib#193]
개발해주신 오픈소스 덕분에 개발에 많은 도움이 되고 있습니다.
hwplib 사용중에 발생한 ClassCastException 을 파고 들다 보니 아래와 같이 수정하시면 좋을 부분이 발견되어 공유 드립니다.

1.
kr.dogfoot.hwplib.paragraphadder.ParagraphMerger.java 
173 라인
ControlType.IndexMark -> ControlType.Bookmark

2.
kr.dogfoot.hwplib.paragraphadder.ParagraphCopier.java 
184 라인
ControlType.IndexMark -> ControlType.Bookmark

**Comment by neolord0** [comment]
지적 감사합니다. 
많이 사용하지 않은 부분이라. 오류가 발견되지 않은 거 같습니다.
수정하여 올리겠습니다.\
