### ISSUE TITLE
문단번호 추출 관련 문의

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwplib#194]
공유해 주신 API 덕분에 많은 도움을 받고 있습니다.

문단번호 추출 관련하여 문의 드립니다.

String str = TextExtractor.extract(hwpFile, TextExtractMethod.InsertControlTextBetweenParagraphText);로 추출을 하였는데

1. 문단번호 1
테스트

2. 문단번호 2
가 문단번호 2-가
나 문단번호 2-나
다 문단번호 2-다

로 되어 있는 파일이

1.문단번호 1
테스트

2.문단번호 2
2.1. 문단번호 2-가
2.2. 문단번호 2-나
2.3. 문단번호 2-다

위와 같이 2.1, 2.2 형태로 추출됩니다.

[문단번호테스트.zip](https://github.com/neolord0/hwplib/files/9526219/default.zip)

**Comment by neolord0** [comment]
개요 번호 기능에 대한 이해가 부족했던 거 같습니다.
제가 이해한 범위내에서 수정했습니다.
받아서 테스트 해보세요.

**Comment by JiniApp** [comment]
감사합니다 받아서 테스트 했습니다
