### ISSUE TITLE
4x3 테이블의 열을 삭제하고 싶은 경우..

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#195]
안녕하세요 hwplib을 사용하여 문서 자동 생성을 공부중인 취준생입니다..

그림에 빨강 열(Column)을 제거하려고합니다.

![image](https://user-images.githubusercontent.com/39794244/194004427-124f16de-0f46-4af1-b268-d66252986896.png)

hwplib 라이브러리를 통해서 4x3 테이블의 중간열을 제거할수 있는지 궁금해서 질문 올립니다.

**Comment by neolord0** [comment]
열 삭제는 가능합니다.
 
전에 답변 했던 내용을 아래에 첨부해 드립니다.
열을 삭제하기 전후에 hwp 파일을 라이브러리로 읽어서
debug 모드에서 hwp 파일 객체 안에 있는 table 객체를 비교해 보시면 
좀 더 이해하기 쉬울 것 같습니다.

--------------------------------------------
열을 삭제하려면...
첫 번째로 체크해야 하는 부분은 열의 셀 들이 병합되어 있는지 여부를 확인하고.
병합된 셀이 있으면...처리를 해서.. 병합된 셀이 없도록 해야 합니다. (병합된 셀을 나눠서 병합되지 않게 처리함..)

이렇게 처리해야 삭제할 열에 병합된 셀이 없도록 처리한 후에..열을 삭제할 수 있습니다.

열을 삭제하기 위해서는 3부분을 설정해야 합니다.

ControlTable.getRowList()에서 각 행 별로 열에 속하는 셀을 삭제해야 합니다.

for(Row row : table.getRowList()) {
for (Cell cell : row.getCellList()) {
if (cell.getListHeader().getColIndex() == deletingColIndex) {
row.getCellList().remove(cell);
break;
}
}
}

그리고, ControlTable.getTable().getCellCountOfRowList() 에 각 행의 셀 갯수에 1를 빼줍니다.

ArrayList newCellCountOfRow = new ArrayList<>();
for (int cellCount : table.getTable().getCellCountOfRowList()) {
newCellCountOfRow.add(cellCount - 1);
}
table.getTable().getCellCountOfRowList().clear();
for (int cellCount : newCellCountOfRow) {

}

마지막으로, ControlTable.getTable().setColumnCount() 을 다시 설정합니다.

table.getTable().setColumnCount(table.getTable().getColumnCount() - 1);

이렇게 하면 될 듯 합니다.

**Comment by sgh9196** [comment]
답변 감사합니다.

위에서 조언해주신 것을 적용해보았지만 한글 파일이 정상적으로 만들어지지 않습니다.

if (hwpFile != null) {
		ControlTable table = findTable(hwpFile);
		
		// Column 삭제
		for(Row row : table.getRowList()) {
			for (Cell cell : row.getCellList()) {
				if (cell.getListHeader().getColIndex() == 1) {
					row.getCellList().remove(cell);
					break;
				}
			}
		}
		
		// Column 수 만큼 List에 Index 저장
		List<Integer> newCellCountOfRow = new ArrayList<Integer>();
		for (int cellCount : table.getTable().getCellCountOfRowList()) {
			newCellCountOfRow.add(cellCount - 1);
		}
		
		// Table cell count list 초기화
		table.getTable().getCellCountOfRowList().clear();
		
		// Table에 각 Row마다 cell 개수 추가
		for (int cellCount : newCellCountOfRow) {
			table.getTable().addCellCountOfRow(cellCount);
		}
		
		// Table 전체 cell 개수 업데이트
		table.getTable().setColumnCount(table.getTable().getColumnCount() - 1);
		table.getTable().setRowCount(3);
}

제가 적용한 소스인데요.. 디버그로 찍어봐도 각 Row에 정상적으로 cell 개수가 맞춰 지는걸 확인했고
table columnCount도 의도한대로 적용이 되었습니다.. 하지만 위 코드로 한글 파일 출력 시

표가 만들어진 건 확인할 수 있지만 몇초후 자동으로 한글파일이 닫힙니다..

어느 부분을 더 추가해야할게 있을까요?

**Comment by sgh9196** [comment]
답변 감사합니다. 
hwplib 라이브러리가 개발 공부에 많은 도움이 되고 있습니다!! 
좋은 라이브러리 배포해주셔서 감사합니다.
