### ISSUE TITLE
안녕하세요. 혹시 해당 library로 수식 쓰기도 가능한가요??

### ISSUE THREAD

**Issue by yojic-jung** [neolord0/hwplib#196]
stream writer를 통해서 시도해보고있는데 잘 안되네요.

EQEdit.class 파일을 보니 script를 set하는 함수가 없어서 가능한지 여부 질문드립니다.

**Comment by neolord0** [comment]
EQEdit 클레스에 getScript() 는 HWPString 클래스를 반환하는데...
이 클래스에 set() 하는 함수가 있습니다.
