### ISSUE TITLE
addHWPFile 메소드 실행시 인덱스 오류가 발생합니다.

### ISSUE THREAD

**Issue by bumjin** [neolord0/hwplib#198]
안녕하세요. 

source.hwp 본문에 target.hwp 을지를 merge하려는데
addHWPFile 사용시 (Adding_Paragraph_Between_Cloned_HWPFIle에 있는 함수)
특정파일(bad-source.hwp 하고 bad-target.hwp) merge시 인덱스 오류가 발생합니다.
확인해주실 수 있으시면 감사하겠습니다. 

한글파일 첨부했습니다. 
[hwp.zip](https://github.com/neolord0/hwplib/files/9807218/hwp.zip)

java.lang.IndexOutOfBoundsException: Index: 24, Size: 24
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.FaceNameAdder.processByHanjaId(FaceNameAdder.java:110)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.copyFaceNameIds(CharShapeAdder.java:164)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.addAndCopy(CharShapeAdder.java:138)
	at kr.dogfoot.hwplib.tool.paragraphadder.docinfo.CharShapeAdder.processById(CharShapeAdder.java:36)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copyCharShape(ParagraphCopier.java:102)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphCopier.copy(ParagraphCopier.java:47)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.copyAndAdd(ParagraphAdder.java:71)
	at kr.dogfoot.hwplib.tool.paragraphadder.ParagraphAdder.add(ParagraphAdder.java:64)
	at 

AppendPageTest.addHWPFile(HandyHwpLibAppendPageTest.java:183)
	at AppendPageTest.testMerge실패(HandyHwpLibAppendPageTest.java:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

정상적인거
```java
@Test
public void testMerge() throws Exception {
	File sourcePath = new File("good-source.hwp");
	File targetPath = new File("good-target.hwp");
	HWPFile targetHWPFile = HWPReader.fromFile(targetPath.getAbsolutePath());
	
	addHWPFile(targetHWPFile, sourcePath.getAbsolutePath());

}
```
오류나는거
```java
@Test
public void testMerge실패() throws Exception {
	File sourcePath = new File("bad-source.hwp");
	File targetPath = new File("bad-target.hwp");
	HWPFile targetHWPFile = HWPReader.fromFile(targetPath.getAbsolutePath());
	
	addHWPFile(targetHWPFile, sourcePath.getAbsolutePath());

}
```
```java
private void addHWPFile(HWPFile targetHWPFile, String sourceHWPFilePath) throws Exception {
	ParagraphListInterface targetFirstSection = targetHWPFile.getBodyText().getSectionList().get(0);

	HWPFile sourceHWPFile = HWPReader.fromFile(sourceHWPFilePath);
	
{
	    Paragraph sourceParagraph = sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(0);

	    ParagraphAdder paraAdder = new ParagraphAdder(targetHWPFile, targetFirstSection, 0);
	    paraAdder.add(sourceHWPFile, sourceParagraph);
	}
}
```

**Comment by neolord0** [comment]
올려주신 hwp파일과 소스를 보니,
hwp 파일이 잘못 만든게 아닐까 추측 됩니다. 
내부 객체의 연결 인덱스 들이 여러 군데 어긋나 있습니다.
이 파일을 한글 프로그램에서 읽어서 다시 저장한 후.. 실행하면 오류가 나지 않은 것을 확인햇습니다.

아마도, 한글 프로그램에서 저장된 hwp 파일이 아니라,  리포팅툴 등에 프로그램으로  만들어진 거 같습니다.
이 파일을 한글 프로그램에서 읽으면,  알고리즘에 의해 적당한 내부 객체로 보정되어 링크하는 거 같습니다.

**Comment by bumjin** [comment]
[file.zip](https://github.com/neolord0/hwplib/files/9825294/file.zip)
해당로직은 (리눅스)서버상에서 hwplib만으로 동작합니다. 

1. 서식템플릿파일(첨부의 01서식템플릿.hwp) 을 열고 
2. 결재제목 문서번호 등 셀에다 값들을 채워주고 (첨부의 02merge전본문.hwp)
3. 을지파일(첨부의 03merge할을지.hwp) 머지

2번 단계까지는 문제가 없는데 3번 파일 머지시 문제가 발생하네요.

**Comment by neolord0** [comment]
1번 => 2번으로 셀정하는 과정에서 설정이 잘못하거나 빠진 부분이 있는 거 같습니다.
CharShape.getFaceNameIds().set??() 함수를 호출하는 부분과 셀에 BorderFillID를 설정하는 부분을 확인해 보세요. 

2번에 과정에서 만들어진 파일을 한글 프로그램으로 읽어서 다시 저장하면 보정됩니다.
2번 과정에서 만들어진 파일과 보정된 파일을 읽어서 디버그 정보를 보고 비교해 보세요.

**Comment by bumjin** [comment]
감사합니다.
2번 과정에서 문제가 되었을거라고는 생각못했었는데 덕분에 문제가 된 부분을 확인할 수 있었습니다.

저희 로직에서 파일 merge전 셀이나 본문 누름틀에 데이타를 넣는 과정이 있습니다.
String fieldName = "서명.1";
InsertGreenCellTextByField(sourceHWPFile, fieldName, "박범진");

혹은 
ArrayList<String> textList = new ArrayList<String>();
textList.add("본문 내용");
//SetFieldResult sfr = FieldFinder.setClickHereText(sourceHWPFile, "본문", textList);
SetFieldResult sfr2 = setClickHereText(sourceHWPFile, "본문", textList);


저희로직에서 셀에 값을 넣을때 
기존 셀의 서식이나 내용 클리어가 필요해 setClickHereText를 복사후 아래와 같은 로직을 추가했었는데
그게 파일머지시 인덱스에 영향을 주는 문제가 되었었던 거 같습니다.

....
//누름틀 색깔?서식 클리어를 위해 추가했었던 내용 시작
        for (Section s : hwpFile.getBodyText().getSectionList()) {
        	int paraCount = s.getParagraphCount();
            for (int paraIndex = 0; paraIndex < paraCount; paraIndex++) {
                Paragraph p = s.getParagraph(paraIndex);
                p.deleteCharShape();
	        	ParaCharShape pcs = p.getCharShape();
	            if (pcs == null) {
	                p.createCharShape(); // 글자 모양이 없다면, 글자 모양을 담을 공간을 생성하여야 합니다.
	                pcs = p.getCharShape();
	            }
	            // 글자 모양에 지정한 폰트, 크기, bold를 지정합니다.
	            if(pcs != null) {
	            	pcs.addParaCharShape(0, createCharShape(hwpFile, ApprConstants.DEFAULT_HWP_FONT_COLOR, ApprConstants.DEFAULT_HWP_FONT_NAME, ApprConstants.DEFAULT_HWP_FONT_SIZE, false));
	            }
            }
        }
        //누름틀 색깔? 서식클리어위해 추가했었던 내용 끝
...


스타일 관련해서는 별도로 정리해서 다시 질문(가이드)요청드리겠습니다.

PS)
지난 번 샘플에서 문제가 된 셀처리 부분은 일단 사용안하고 
파일 머지하는것만 테스트했는데
good-source.hwp(본문) 하고 good-target.hwp (을지)
머지했을때 
을지가 마지막에 append되는게 아니라
본문내에 append되는 문제가 있는데
마지막에 append되게 하려면 어떻게 해야될지 알려주시면 감사하겠습니다. (별도 이슈로 올리는게 나을까요?)

**Comment by neolord0** [comment]
ReadMe 에서 말씀드린 것 처럼, 이 라이브러리를 기반으로 하는 제품을 판매하고 있습니다.
그래서, 지금은 자유롭게 지원해 드릴 수 없습니다. 
버그 수정이나 간단한 질문에 대한 이슈 만을 처리하고 있습니다. 

아래의 질문은 원하는 형태의 hwp 파일을 한글 프로그램으로 만들어서, 라이브러리로 만든 hwp 파일과 동시에 읽어서 
디버그 Watch 기능을 이용하면 충분히 차이점을 인식할 수 있을 거라 생각됩니다.

양해해 주셨으면 합니다.
