### ISSUE TITLE
안녕하세요 취소선(strikeLine) 관련해서 문의 남깁니다.

### ISSUE THREAD

**Issue by junsoo875** [neolord0/hwplib#199]
hwplib 잘사용하고있습니다. 너무 감사합니다.

strikeLine 관련해서 취소선색 변경방법이 있을까요?? 
현재 올라와있는 hwplib를 이용해 어떻게 설정가능하는지 문의 드립니다.
strikeLine은 CharShape를 이용해 구현하였습니다. (getProperty().setStrikeLike(true))

**Comment by neolord0** [comment]
취소선색은 CharShape.getStrikeLineColor() 메소드를 통해 얻을 수 있는 
Color4Byte 객체를 통해 설정 가능합니다.

CharShape.getProperty().setStrikeLike()은 취소선이 적용되는지 여부만을 설정합니다.

아울려, 취소선의 모양은 CharShape.getProperty().setStrikeLineShape()로 설정하여야 합니다.
