### ISSUE TITLE
안녕하세요 hwplib-master를 사용해보고 궁금한 점이 있어서 질문드립니다.

### ISSUE THREAD

**Issue by quantum123** [neolord0/hwplib#2]
먼저 유용한 라이브러리를 개발해주셔서 감사합니다. 제가 다운받고 여러 hwp 파일들을 테스트해봤는데 이미지, 누름틀, 표서식 등 복잡한 문서도 대부분 잘 읽혔습니다. 하지만 특정한 한글문서버전은 읽지 못하고 예외가 발생하거나 결과가 나오지 않는 경우를 확인하게 되었습니다. 대표적으로 문서버전이 5.0.0.6, 5.0.2.4.1, 5.0.0.3, 5.0.1.6, 5.0.3.0.1, 5.0.0.5, 5.0.1.7인 경우 문서를 읽지 못하였습니다. 해당 원인을 찾기위해 현재도 알아가보는 중이지만 개발하신 분도 아시면 개발에 도움이 되실 것 같아 이렇게 질문을 드리게 됩니다.

**Comment by neolord0** [comment]
한글 프로그램은 주기적으로 서브 버전을 업그레이드 합니다.  버전에 따라  파일에 특정 부분이 추가/변경되는 거 같습니다. 이 부분이 한컴 측에서 배포된 문서에 생략된 경우가 있어서 저도 예측하기 어려운 부분입니다. 제가 가지고 있는 한글 프로그램은 최신 버전 뿐인지라 테스트하기 힘듭니다. 
제게 파일들을 보내주시면 테스트 해보겠습니다. 
neolord@hamail.net 으로 보내주세요.

**Comment by quantum123** [comment]
해당 메일로 보내들렸습니다. 답변해주셔서 감사합니다.

**Comment by quantum123** [comment]
naver 메일로는 전송이 되지 않은 것을 오늘 확인하여 nate 메일로 다시 전송해드렸습니다.

**Comment by neolord0** [comment]
neolord@hanmail.net 인데 
메일 주소 오타 였군요.. 여기로 보내주세요.

**Comment by quantum123** [comment]
네 메일 보내드렸습니다.

**Comment by neolord0** [comment]
받았습니다. 확인 해보겠습니다.

**Comment by neolord0** [comment]
보내주신 파일들을 테스트하여 수정하였습니다.
받아서 확인 해보세요.
