### ISSUE TITLE
Count of FaceName is greater than ID Mappings 오류가 뜹니다.

### ISSUE THREAD

**Issue by beam307** [neolord0/hwplib#20]
http://ebiz.khnp.co.kr/MB_BID/C/util/file_down.jsp?f_gbn=m1&f_nam=9430Y18S0950005.hwp

url로 이걸 불러올때 저런에러가 뜨는데 수정부탁드립니다.

**Comment by neolord0** [comment]
수정해서 업데이트 했습니다. 
받아서 테스트 해보세요.
