### ISSUE TITLE
xml 변환기능이 있을까요?

### ISSUE THREAD

**Issue by bongdan** [neolord0/hwplib#200]
안녕하세요.

한가지 궁금한게 있습니다.

혹시 읽어들인 hwp 파일을 

xml로 변환하는 기능이 잇을까요?

그리고 반대로 xml 읽어들여서 hwp이나 아니면 html를 만들어내는 기능도 있을까요??

hwp 가 xml 기반이라고 들었거든요.

좋은 오픈소스 만들어주셔서 감사드립니다.~~

**Comment by neolord0** [comment]
안녕하세요.
hwp ->  xml, xml -> hwp  모두 정해진 규칙이 없이 해당 업무에 따라 다르기 때문에 
직접 만드셔야 합니다.

**Comment by bongdan** [comment]
hwpx가 xml 기반이라고 하셨는데요.

hwpx의 xml를 볼 수 잇는 방법이 있을까요?

**Comment by neolord0** [comment]
hwpx 파일은 zip 파일로 돼 있습니다.
알집 등의 압축 프로그램으로 읽으면  hwpx 파일 속에 있는 내용을 볼 수 있습니다.
