### ISSUE TITLE
글꼴 관련 문의 드립니다.

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwplib#201]
안녕하세요 새해 복 많이 받으세요
제공해 주신 라이브러리 사용 중 도움을 받고자 문의 드립니다.

글꼴 관련 문의인데요 HwpFile.getDocInfo().getHangulFaceNameList().get(Idx).getName() 메소드를 통해 글꼴을 추출하는데 
일부 글꼴이 한글프로그램과 다르게 추출되어 문의 드립니다.
한글에서는 견고딕으로 나오나 라이브러리에서 추출 시 한양견고딕 등으로 추출됩니다.

그리고 한글2022로 작성된 파일인데 파일을 읽는 중 아래와 같은 오류가 발생하여 같이 문의 드립니다.
java.lang.Exception: Shape Component must come after CtrlHeader for gso control.
[test.zip](https://github.com/neolord0/hwplib/files/10323796/test.zip)

**Comment by neolord0** [comment]
에러 나는 부분은 수정했습니다.
전에 테스트 했을 때는 사격형 컨트롤 내부에서 컨트롤 데이터가 먼저 나오고 그 다음에 캡션 정보가 나오는 순서 였는데..
보내주신 파일을 열어보니 순서가 반대로 나와있더군요. 순서가 유동적일 수 있다는 전제로 코드를 수정하였습니다.

그리고, 폰트 이름 문제는 ... "견고딕"이 파일에는 "한양견고딕"으로 들어가 있더라고요.
무슨 이유인지 몰라도 한글 프로그램 내부에서 그렇게 처리하는 것 같습니다. --;

**Comment by JiniApp** [comment]
많은 도움 주셔서 감사합니다.
