### ISSUE TITLE
문단 번호 관련 문의드립니다.

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#202]
안녕하세요. 새해 복 많이 받으세요
제공해 주신 라이브러리 사용 중 도움을 받고자 문의 드립니다.

한글 문서 생성할 때 총 4개의 레벨로 문단 번호를 형성하려고 합니다.
기존에 만들었던 소스는 아래와 같습니다.

```
Paragraph newPara = this.hwpFile.getBodyText().getSectionList().get(0).addNewParagraph();
	
util.deleteParagraphChild(newPara); //  Paragraph 하위 태그 모두 제거
util.setParaText(newPara, "가"); // 콘텐츠 변경
util.setStyle(hwpFile, newPara, "AutoNumber_Lv1");  // 스타일 추가
```

기존 템플릿에 만들어 둔 "AutoNumber_Lv1"라는 스타일을 추가해서 해당 Paragraph에 스타일 추가하는 방식으로 구현했습니다.

여기서 궁금한건

1. 새로 생성한 newPara에 hwplib를 통해서 직접 문단번호를 추가할수 있나요?
2. 문단 번호를 추가할 수 있다면 문단 모양을 지정할수 있나요?
3. 문단 번호의 수준을 설정할 수 있나요?

위 3가지 항목이 가능한지 알고싶습니다.

**Comment by neolord0** [comment]
hwplib는 기본적으로 한글 프로그램에 기능적인 부분은 모두 처리 가능합니다.

스타일 처럼 공통 객체를 특정문단에 연결하는 방식 인데요..
문단 번호(Numbering class)는 문단 모양(ParaShape)에 연결되고, 문단 모양 객체가 문단에 연결되는 방식으로
특정 문단에 문단 번호를 선택할 수 있습니다.

**Comment by sgh9196** [comment]
답변 감사합니다.

한 가지만 더 여쭤보겠습니다.
 
미리 만들어 둔 테이블에 캡션을 추가 하려고합니다.


	`public void insertTableCaption() {
		
		// ArrayList<Control> controlList = ControlFinder.find(hwpFile, new HwpControlFinder());
		List<Control> controlList = ControlFinder.find(this.hwpFile, new HwpControlFilter());
		
		for (Control control : controlList) {
			if (control.getType() == ControlType.Table) {
				this.table = (ControlTable) control;
				
				Caption caption = this.table.getCaption();
				
				// 타겟 테이블에 캡션이 존재하지 않으면 생성해준다.
				if (caption == null) {
					this.table.createCaption();
					caption = this.table.getCaption();
				}
				
				setListHeader(caption.getListHeader());
				setPara(caption.getParagraphList().addNewParagraph(), "테스트 캡션입니다.");
			}
		}
		
	}
	
	public void setListHeader(ListHeaderForCaption listHeader) {
		listHeader.getCaptionProperty().setDirection(CaptionDirection.Bottom);
		listHeader.setSpaceBetweenCaptionAndFrame(850);
	}
	
	public void setPara(Paragraph emptyPara, String text) {
		setParaHeader(emptyPara);
        setParaText(emptyPara, text);
        setParaCharShape(emptyPara);
	}
	
    public void setParaHeader(Paragraph p) {
        ParaHeader ph = p.getHeader();
        ph.setLastInList(true);
        // 셀의 문단 모양을 이미 만들어진 문단 모양으로 사용함
        ph.setParaShapeId(1);
        // 셀의 스타일을이미 만들어진 스타일으로 사용함
        ph.setStyleId((short) 1);
        ph.getDivideSort().setDivideSection(false);
        ph.getDivideSort().setDivideMultiColumn(false);
        ph.getDivideSort().setDividePage(false);
        ph.getDivideSort().setDivideColumn(false);
        ph.setCharShapeCount(1);
        ph.setRangeTagCount(0);
        ph.setLineAlignCount(1);
        ph.setInstanceID(0);
        ph.setIsMergedByTrack(0);
    }

    public void setParaText(Paragraph p, String text2) {
        p.createText();
        ParaText pt = p.getText();
        try {
            pt.addString(text2);
        } catch (UnsupportedEncodingException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
    
    public void setParaCharShape(Paragraph p) {
        p.createCharShape();

        ParaCharShape pcs = p.getCharShape();
        pcs.addParaCharShape(0, 1);
    }
 
    public void setParaLineSeg(Paragraph p) {
        p.createLineSeg();

        ParaLineSeg pls = p.getLineSeg();
        LineSegItem lsi = pls.addNewLineSegItem();

        //lsi.setTextStartPosition(0);
        lsi.setTextStartPositon(0);
        lsi.setLineVerticalPosition(0);
        lsi.setLineHeight(ptToLineHeight(10.0));
        lsi.setTextPartHeight(ptToLineHeight(10.0));
        lsi.setDistanceBaseLineToLineVerticalPosition(ptToLineHeight(10.0 * 0.85));
        lsi.setLineSpace(ptToLineHeight(6.0));
        lsi.setStartPositionFromColumn(0);
        lsi.setSegmentWidth((int) mmToHwp(50.0));
        lsi.getTag().setFirstSegmentAtLine(true);
        lsi.getTag().setLastSegmentAtLine(true);
    }`

위와 같이 caption 생성 후 캡션 속성과 문단까지 추가해주었는데 실제 문서를 열어보면 손상된 파일이라고 나오는데

혹시 더 추가해야 할 부분이 있나요?

[관련자료.zip](https://github.com/neolord0/hwplib/files/10357390/default.zip)

제가 테스트한 소스와 파일입니다.

**Comment by sgh9196** [comment]
감사합니다. 해결되었습니다.
