### ISSUE TITLE
hwplib 최신 버전에서 테이블 복사가 오래걸립니다.

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#203]
안녕하세요.
문서 자동 생성에 관심 있어서 공부하고 있습니다.

hwplib 1.0.3 버전을 사용하다가 최근에 1.1.1 최신 버전으로 업그레이드 진행했습니다.

1.0.3 버전에서 B파일에 그려져 있는 테이블을 A파일에 새로운 Section에 복사하는 로직을 공부하면서 테스트 코드를 만들어 둔게있는데

1.1.1 버전으로 올리면서 ApragraphAdder에 문단 추가하는 부분에서 속도가 큰 차이가 납니다.

A 파일에서 새로운 섹션 만들고 B파일의 테이블을 복사하는데 까지 
1.0.3 버전에선 바로 복사가 되고
1.1.1 버전에선 50분 가량 걸리는 것으로 보입니다.

혹시 어느 부분이 변경이 되서 그런건지 알수있을까요??

테스트 파일 및 코드 첨부합니다.
[test 파일.zip](https://github.com/neolord0/hwplib/files/10388012/test.zip)
[test 소스.zip](https://github.com/neolord0/hwplib/files/10388007/test.zip)

**Comment by neolord0** [comment]
안녕하세요.

코드를 비교하니, FillInfo 객체를 복사하는 부분에서 제가 실수를 한 거 같습니다.
이 버그는 수정하였고,  아울러 다른 공통 객체의 복사 속도를 개선하였습니다.

받아서 테스트 해보세요...

**Comment by sgh9196** [comment]
감사합니다. 속도가 확실히 빨라졌습니다. 
좋은 라이브러리 공유해주셔서 다시 한번 감사합니다.
