### ISSUE TITLE
문단 번호 생성 관련 문의

### ISSUE THREAD

**Issue by TesterDevS** [neolord0/hwplib#205]
안녕하세요. 

공유해 주신 API 덕분에 많은 도움을 받고 있습니다.

문단 번호 생성 관려해서 Sample 코드 있을까요?

문단에 Numbering 관련 Class를 참고하여 개발하려고 시도했는데..

방법을 잘 모르겠습니다.

**Comment by neolord0** [comment]
안녕하세요.
문단 번호 생성은 다양한 케이스가 있어서 샘플을 제공해 드려도 도움이 되지 않을 확률이 큽니다.
kr.dogfoot.hwplib.tool.blankfilemaker.NumberingAdder 클래스를 참고하시고, 
한글 프로그램으로 원하는 문단 번호가 설정된 hwp 파일을 만든 후, 라이브러리로 읽어서
디버그 툴의 watch 기능으로 hwp 파일 객체의 설정을 확인하며 설정하는 방법으로 해 나가셔야 합니다.

이 라이브러리은 상용으로 판매되고 있기 때문에, 더 이상의 기술지원은 유료로 진행할 수밖에 없음을 양해해 주셨으면 합니다.
