### ISSUE TITLE
솔루션 도입 문의드립니다

### ISSUE THREAD

**Issue by durumee** [neolord0/hwplib#206]
안녕하세요.

깃헙 이슈에 이 글을 올리는게 적절한지 몰라 조심스럽습니다.

한글 기안기 제품과 관련하여 검색을 하다가 위키랩사의 제품을 주시하고 있었으나..
현재 위키랩사와 연락이 되지 않아 메일을 남깁니다.

혹시 연락이 가능하시다면 아래 메일로 회신을 부탁드립니다.

bluewish614 (at) naver.com

**Comment by neolord0** [comment]
안녕하세요.
메일 드렸습니다.
