### ISSUE TITLE
latex 변환 관련 질문드립니다

### ISSUE THREAD

**Issue by wolru** [neolord0/hwplib#207]
안녕하세요. 수학 hwp 문서를 텍스트 변환하려고 하는데요

수식 부분이
kr.dogfoot.hwplib.object.etc.HWPString@19dc67c2
이런식으로 출력이 되는데 파일이 문제일까요?

아래 파일입니다.

[2019.hwp.zip](https://github.com/neolord0/hwplib/files/10527121/2019.hwp.zip)

**Comment by neolord0** [comment]
안녕하세요..
hwp는 수식을 사용하기 위해... 수식 컨트롤을 사용하는데..
수식 script 문법이 latex 문법이 아닌듯 합니다.

**Comment by wolru** [comment]
답변 감사드립니다.
샘플에 있는 수식.hwp 도 동일하게 출력되길래 소스를 보니 
private static void equation(ControlEquation equation, StringBuffer sb) {
        sb.append(equation.getEQEdit().getScript()).append("\n");
}
이렇게 돼있어서 object 해시값이 출력되는 것 같습니다

**Comment by neolord0** [comment]
제가 실수 했군요.. 

이렇게 하셔야 합니다.
```
    private static void equation(ControlEquation equation, StringBuffer sb) {
        sb.append(equation.getEQEdit().getScript().toUTF16LEString()).append("\n");
    }

```

**Comment by wolru** [comment]
넵 감사합니다
