### ISSUE TITLE
table cell size 관련 문의드립니다

### ISSUE THREAD

**Issue by wolru** [neolord0/hwplib#208]
안녕하세요. 좋은 라이브러리 만들어주셔서 감사합니다

한글 문서를 봐도 딱히 나와있는 곳이 없는것 같아서 문의드립니다
테이블의 cell에서 c.getListHeader().getWidth() 로 길이 (or 높이)를 가져오면 큰 값이 넘어오는데요
ex) 한글에서는 13.57mm가 282
html로 변환을 하는 작업을 하고 있는데, 이 값이 어떤 기준인지 잘 파악이 안되고 있습니다. 
이 값이 html의 pixel로 바뀌려면 어떻게 값을 변환하면 좋을까요?

**Comment by neolord0** [comment]
안녕하세요..
한글 좌표는  HWPUNIT(1/7200인치) 라는 단위로 표현됩니다.   pixel로 표현하려면 DPI(dot per inch) 값이 필요합니다.
DPI 값은 정식대로 하면 출력 디바이스에서 얻어와야 하지만, 상수값으로 설정해주면 될 거 같습니다.

대략적으로 
=  좌표 값  / 7200 * DPI * 확대/축소 배율  
이렇게 하면 되지 않을까 생각됩니다.

**Comment by wolru** [comment]
HWPUNIT(1/7200인치) 이런 단위였군요
답변 감사드립니다~!
