### ISSUE TITLE
파일을 읽고 저장시 파일손상

### ISSUE THREAD

**Issue by tjguswns33** [neolord0/hwplib#209]
대상파일( .zip만 제거하여 사용하시면 됩니다)
[test.hwp.zip](https://github.com/neolord0/hwplib/files/10866625/test.hwp.zip)

파일을 읽고 저장만 하였을때 파일이 손상됩니다..

추가로 파악되는 부분은 업데이트 해놓겠습니다..

**Comment by neolord0** [comment]
안녕하세요..

보내주신 파일로 테스트 해보니.. 크기가 다른 다단이 적용될 경우에 문제가 발생하는 것 같습니다.
수정 되었으니 다시 받아서 테스트 해 보세요.

**Comment by tjguswns33** [comment]
확인하였습니다 감사합니다 (__)
