### ISSUE TITLE
혹시 호-곡선객체읽기, 쓰기가 안되는데 가능하실까요?

### ISSUE THREAD

**Issue by smileGithu** [neolord0/hwplib#210]
호-곡선 객체 읽고 쓰기를 하고 있는데 결과는 투명한 객체가 생성되고 있습니다.
속성은 기존거하고 같은데 안나오고 있습니다. 원인이 뭔건지 알수 있으실까요?
감사합니다.

**Comment by neolord0** [comment]
안녕하세요..

버그가요 ? 아니면 사용법이 잘 몰라서 그러시는 건가요?
버그라고 생각되시면 좀 더 자세히 설명해 주시고, 사용법을 몰라서 그런 거 라면 샘플과 한컴 문서등을 참조하셔서 직접 해결하셔야 합니다 

앞에 대문에서 말씀드렸듯이, hwplib를 기반으로 하는 제품을 판매하고 있어서, 사용법에 대한 기술지원을 무상으로 제공해 드리지 못하는 점을 양해해 주셨으면 합니다. 정식적으로 hwplib 기술지원을 계약하거나, 샘플과 한컴 문서등을 참조하셔서 직접 해결하셔야 합니다.

**Comment by smileGithu** [comment]
답변 감사합니다.
제 생각에는 버그라 생각됩니다.
샘플코드에서 HWPReader.fromFile함수로 한컴파일을 읽고 HPWWriter.toFile함수로 다시 쓰기하면 객체는 생기는데 곡선이 안보입니다. 객체속성은 꼭 같이 생성됩니다.
![소스](https://user-images.githubusercontent.com/71059313/223106870-afe7a07a-03cd-4613-b575-2ccf038ad8a7.jpg)
![결과](https://user-images.githubusercontent.com/71059313/223106878-4a060eac-3208-4fc7-82b0-446484cf828b.jpg)
감사합니다.

**Comment by neolord0** [comment]
제가 테스트 한 경우에는 호/곡선 모두 잘 됩니다.

최신 버전의 hwp 라이브러리를 소스코드를 받아서 테스트 해보시고, 
같은 문제가 발생하면 테스트 하신 hwp 파일을 올려주세요.
