### ISSUE TITLE
컨트롤 - 이미지 순서 매칭

### ISSUE THREAD

**Issue by JungH00ns** [neolord0/hwplib#213]
안녕하세요
라이브러리 사용하여 이미지를 데이터 소스에 업로드 후 링크로 치환하고 있습니다.
컨트롤 중 picture인 것을 찾아
바이너리에서 이미지를 인덱스 순서로 불러와
데이터 소스에 업로드 후 링크를 추가하는 방식으로 사용 중 입니다.
이 과정에서 화면에 그려지는 이미지와 바이너리에 있는 이미지들의 순서가 맞지않아서
컨트롤을 치환 후에 확인해보면 이미지들의 순서가 섞여있습니다.
컨트롤과 이미지들의 순서를 맞출 수 있는 방법이 있을까요 ?

**Comment by neolord0** [comment]
안녕하세요.
컨트롤과 이미지의 순서는 독립적이라고 할 수 있습니다.
한글 프로그램에서 만들고 삭제하는 과정에서 얼마든지 변경될 수 있습니다.
wiki 을 참조하여.. 컨트롤에서 링크된 바이너리를 찾아서 처리해야 합니다.

**Comment by JungH00ns** [comment]
감사합니다!

**Comment by JungH00ns** [comment]
안녕하세요 이후에
컨트롤에서 바이너리 정보를 찾아보았는데
getBinItemID 를 통해서 바이너리 아이디를 얻을 수 있었습니다
하지만 이 바이너리 아이디 자체가 순서대로 되어있어서
결국 순서대로 받아오면 이미 섞인 상태로 가져오게 되는데요
바이너리 아이템 자체를 생성할 때 순서가 섞이는 걸까요 ?

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    이미지 만드는 샘플인 kr.dogfoot.hwplib.sample.Inserting_Image 클래스를 참고하시면 될 같습니다.

--------- 원본 메일 ---------

    
        보낸사람: JungH00ns ***@***.***>
        받는사람: neolord0/hwplib ***@***.***>
        
            참조: 박성균(Park.sung.kyun) ***@***.***>, Comment ***@***.***>
        
        날짜: 23.03.20 10:53 GMT +0900
        제목: Re: [neolord0/hwplib] 컨트롤 - 이미지 순서 매칭 (Issue #213)
        
        
    
    
        
안녕하세요 이후에
컨트롤에서 바이너리 정보를 찾아보았는데
getBinItemID 를 통해서 바이너리 아이디를 얻을 수 있었습니다
하지만 이 바이너리 아이디 자체가 순서대로 되어있어서
결국 순서대로 받아오면 이미 섞인 상태로 가져오게 되는데요
바이너리 아이템 자체를 생성할 때 순서가 섞이는 걸까요 ?
