### ISSUE TITLE
java로 읽어온 hwp파일을 읽기전용 파일로 새롭게 저장할 수 있는 방법이 있을까요?

### ISSUE THREAD

**Issue by koreaGunner** [neolord0/hwplib#214]
해당 경로에 있는 파일을 읽어와서 읽기전용 파일로 다시 저장하는 방법이 있을까요?
알려주신다면 너무 감사하겠습니다!

그리고 

- 각각의 객체들과 객체에 포함된 메소스들에 대해선 "/doc" 디렉토리에 있는 javadoc 문서를 참고하시기 바랍니다.
이렇게 남기셨는데 저 디렉토리가 어디에 있는지 잘 모르겠습니다 알려주시면 감사하겠습니다!

**Comment by koreaGunner** [comment]
![image](https://user-images.githubusercontent.com/121987844/231705030-86195add-f2ca-443b-b8a9-ff0b5d2c6cc2.png)

이거 읽기전용파일 기능 맞지 않나요?

**Comment by neolord0** [comment]
HWPEdit는 제가 만든게 아니라... 정확히는 알 순 없습니다만..
여기서 말하는 읽기 전용이라는게..  HWPEdit 가 읽기 전용 모드라는 거지.. HWP 파일이 읽기 전용이라는 게 아닌 거 같습니다.
위에 설명에도 "편집 모드"라는 말이 있듯이 말입니다.
자세한 것은 한컴에 문의해 보세요.

**Comment by koreaGunner** [comment]
넵 ! 감사합니다!!
