### ISSUE TITLE
줄바꿈 제거 관련 문의드립니다.

### ISSUE THREAD

**Issue by dandelion1124** [neolord0/hwplib#215]
안녕하세요, 만들어주신 라이브러리 정말 잘 활용하고 있습니다! 
줄바꿈과 관련하여 문의드리려고 합니다. 

kr.dogfoot.hwplib.object.bodytext.paragraph.text 

표의 특정 cell에 문자를 넣도록 하고 싶은데요, 
findHwpFieldCell()을 통해서 cell을 선택하고 
해당 cell에 createText() 후 , getText().addString(text) 로 문자를 넣도록 했습니다 .

그런데 addString() 으로 문자를 넣고나면 마지막에 
processEndOfParagraph()가 실행되며 줄바꿈이 되는거 같은데 맞나요..? 

줄바꿈이 되지 않도록 하고싶은데, 
혹시 줄바꿈 없이 표에 문자를 넣을 수 있는 다른 함수가 있거나
줄바꿈을 없앨 수 있는 함수가 있을까요?

**Comment by neolord0** [comment]
안녕하세요.

EndOfParagraph는 말 그대로 문단의 끝을 나타내는 글자 입니다. 
이 문자가 없으면 문단 끝을 인식 못해서 한글에서 못 읽습니다.
EndOfParargraph는 Char(13)이고 줄바꿈은 Char(10)으로 다른 값 입니다.

**Comment by dandelion1124** [comment]
그렇다면 addString()을 사용하는 것 외에 다른 부분에서 줄바꿈이 실행되는 거겠군요.. ㅜ 
원인을 더 찾아보고 문의드리겠습니다, 답변 감사합니다~!

**Comment by dandelion1124** [comment]
안녕하세요! 
알려주신대로 addString(text)에는 문제가 없었습니다. 
문자를 넣고자 하는 cell을 확인해보니
cell.getParagraphList().getParagraphCount() 결과가 2가 나왔습니다. 
애초에 Paragraph가 2개 존재하고 제가 첫번째 Paragraph에 문자를 넣은건데 줄바꿈이 되었다고 생각을 했습니다. 
그런데 해당 cell에는 addString 이전에 다른 작업을 하지 않았는데 왜 Paragraph가 2개로 나오는지 잘 모르겠습니다.
혹시  Paragraph를 제거하는 방법은 없을까요?

**Comment by neolord0** [comment]
안녕하세요.

이 질문에 답은 제가 할 수 없습니다. 
앞에 대문에서 말씀드렸듯이, hwplib를 기반으로 하는 제품을 판매하고 있어서, 사용법에 대한 기술지원을 무상으로 제공해 드리지 못하는 점을 양해해 주셨으면 합니다. 정식적으로 hwplib 기술지원을 계약하거나, 샘플과 한컴 문서등을 참조하셔서 직접 해결하셔야 합니다.
