### ISSUE TITLE
[추가요청] 파일을 읽고 다는 과정중 문제가 발생하여 문의드립니다!

### ISSUE THREAD

**Issue by tjguswns33** [neolord0/hwplib#216]
안녕하세요..!

문서를 열고 저장하는 과정 중 문제가 발생하여 문의드립니다.

시간나실때 확인 부탁드립니다! 감사합니다..!

( .zip만 제거하여 사용하시면 됩니다)
현상발생문서 : [문서파싱오류.hwp.zip](https://github.com/neolord0/hwplib/files/11328363/hwp.zip)

아래 처럼 목차 부분 가운데 공백 line에서 파싱하지 않는 내용이 있는것 같은데 공백 line 제거하면 정상적으로 작동됩니다.
![image](https://user-images.githubusercontent.com/59809631/234449691-f220a801-ea4f-41c8-a2e1-450865cda6b0.png)

테스트 소스
```
public static void main(String[] args) {
    long time = System.currentTimeMillis();
    try { 
        File f = new File("C:\\aaa\\hwp\\aaa.hwp");
        File dest = new File(f.getParentFile(), "_" + f.getName());
        HWPFile hf = HWPReader.fromFile(f);
        HWPWriter.toFile(hf, dest.getAbsolutePath());
    }catch(Exception e) {
        e.printStackTrace();
    }finally {
        System.out.println(">>> Time elapsed : " + (System.currentTimeMillis()-time));
    }
} 
```

**Comment by neolord0** [comment]
네 확인 해보겠습니다.

**Comment by neolord0** [comment]
확인 해보니.. 특정 레코드의 길이가 0인 경우. 무한루프에 빠지는 현상이 발견되어..  수정했습니다.
다시 받아서 테스트 해보세요.

**Comment by tjguswns33** [comment]
안녕하세요 빠른 해결 감사드립니다.

무한루프는 해결이 되었는데 문서깨짐현상이 발생합니다..ㅠ

시간나실때 확인 부탁드립니다..

감사합니다(__)

**Comment by tjguswns33** [comment]
해당원인 처리해주셔서 감사합니다 추가로 발생한 이슈는 #217에 추가작성 하였습니다.
