### ISSUE TITLE
테이블 작성시 첫줄에 공백의 한줄이 들어가는데요. 원래도 첫줄에 공백이 들어가나요??

### ISSUE THREAD

**Issue by Geoje1dong** [neolord0/hwplib#218]
테이블 작성시 첫줄에 공백의 한줄이 들어가고 있습니다.
혹시 EmptyParagraphAdder.add(section)으로 인해 공백한줄이 발생하는걸까요?
삭제시 csd가 null이 되서 테이블을 만들지 못하더라구요.
어떤 부분떄문에 첫줄의 공백이 생기는지 감이 안잡혀서 질문드립니다.
`
EmptyParagraphAdder.add(section);
Size paperSize = getPaperSize();

ControlSectionDefine csd = (ControlSectionDefine) section.getParagraph(0).getControlList().get(0);

csd.getPageDef().setPaperWidth(paperSize.cx);
csd.getPageDef().setPaperHeight(paperSize.cy);

int margin = (int) ((float) ReportUtil.MAP_MARGIN / ReportUtil.DOCUMENT_WIDTH * paperSize.cx);
csd.getPageDef().setLeftMargin(margin);
csd.getPageDef().setRightMargin(margin);
csd.getPageDef().setTopMargin(margin / 4);
csd.getPageDef().setBottomMargin(margin / 4);

Paragraph firstParagraph = section.getParagraph(0);

new FloorHwpTable(hwp)
        .createMapTable(firstParagraph, section_name, project_name, pageDirection, mapImage, map_row_width, map_row_height);
`

**Comment by neolord0** [comment]
안녕하세요.

FloorHwpTable 클래스는 Geoje1dong님이 만드신 거 같습니다.
FloorHwpTable 부분을 주석으로 처리한 후... 실행 해 보세요.

지금 판매 중인 제품이기 때문에, 버그 패치가 아닌 기술지원은 대응하지 않습니다.
직접 해결해 보신 후에, 버그라고 생각하시면 소스코드와 hwp 파일 등 제가 테스트할 수 있는 자료들과 함께 다시 문의해 주세요.
