### ISSUE TITLE
hwpFile numbering 이슈

### ISSUE THREAD

**Issue by yundongjun** [neolord0/hwplib#219]
ParaHeadMaker클래스에 있는 hwpFile.getDocInfo().getNumberingList().size가 0일경우가 있습니다.
일단 저는 임시적으로 
if(hwpFile.getDocInfo().getNumberingList().size() == 0) {
    return null;
}
추가해서 해결하였습니다.

관련되서 이렇게 해결해도 되는지 질문드립니다.

**Comment by neolord0** [comment]
안녕하세요.. 

Numbering numbering = hwpFile.getDocInfo().getNumberingList().get(paraHeadID - 1)
이 부분에서 에러가 난 거 같은데요..
이게 정상적인 hwp에서는 에러가 나면 안되는 부분입니다.
잘 못 만들어 지거나 한글 프로그램이 아닌 다른 프로그램으로 만든 hwp 파일에서 설정이 잘 못 되었을 경우인거 같습니다.

님이 처리하신 데로 하면.. 실행은 돼도, 글자 추출할 때, 글자번호등이 출력되지 않을 건입니다.
