### ISSUE TITLE
table just 2 row but get rowCount is 4

### ISSUE THREAD

**Issue by zuoliang0** [neolord0/hwplib#22]
maybe is something error .
i create a 2 row 3 cell table.
read in library but get row count 4;

![image](https://user-images.githubusercontent.com/8434253/42302100-ab6aaeda-804b-11e8-98ec-4b33ece22ed6.png)
 
![image](https://user-images.githubusercontent.com/8434253/42302115-bc169bcc-804b-11e8-83f7-08473e85cf3e.png)

thank you.

**Comment by neolord0** [comment]
I tested this issue with My Example(kr.dogfoot.hwplib.test.TestMakingTable.java).
It was no problem.   

please. see my example code and send your full source code to me(neolord@hanmail.net)
I want to see it.
