### ISSUE TITLE
The supplied data appears to be in the Office 2007+ XML. You are calling the part of POI that deals with OLE2 Office Documents. You need to call a different part of POI to process this data (eg XSSF instead of HSSF)

### ISSUE THREAD

**Issue by yundongjun** [neolord0/hwplib#220]
https://rfp.g2b.go.kr:8426/cmm/FileDownload.do?atchFileId=000001075172&fileSn=1 해당 파일에서 발생하는 문제입니다.

이 문제는 어떤문제인지 정확하게 판단이 되지 않아서 질문드립니다.

**Comment by neolord0** [comment]
안녕하세요.. 
요즘 회사일 때문에.. 답변이 늦었네요.

이 파일은 hwp 파일이 아니라 hwpx 파일 입니다.
그래서, hwplib로 읽을 수 없고 hwpxlib로  읽어야 합니다.
