### ISSUE TITLE
ParaLineSeg에서 하위 태그들을 읽어올 방법이 없을까요?

### ISSUE THREAD

**Issue by supersolaris** [neolord0/hwplib#221]
현재 hwp를 가지고 hwpml을 뽑고 있는데요. lineseq까지는 뽑았는데 그 밑으로 들어가는 부분을 어떻게 구현해야 할지 막혀서 조언좀 부탁드립니다.

**Comment by neolord0** [comment]
안녕하세요

lineseq 부분은 문단을 라인별로 나눠지는 정보를 저장한 부분입니다.
hwpml 포맷에는 해당하는 내용의 테그가 없는 걸로 알고 있습니다.
해당 부분은 신경쓰지 않아도 될 부분입니다.

제가 생각하기로는 여러 줄로 나눈 문단을 그릴 때 그리기 속도를 빠르게 하기 위해 계산된 결과를 저장해 둔 부분이 아닐까 생각됩니다.

**Comment by supersolaris** [comment]
바쁘실텐데 고맙습니다. 그럼 바로 paragraph에서 ControlList를 갖고와서 태그를 만드는 방향으로 작업하면 되겠군요. 감사합니다.
