### ISSUE TITLE
바쁘실텐데 죄송합니다. paragraph속에 하위태그 정보들을 어떻게 읽어올수 있을까요?

### ISSUE THREAD

**Issue by supersolaris** [neolord0/hwplib#222]
![image](https://github.com/neolord0/hwplib/assets/130431442/887fb49a-b05f-475f-8dea-10c429a24415)
여기서 원래의 취지는 LIneSeg의 밑에 테이블이 있는지 이미지가 있는지 그냥 텍스트만 있는지를 파악해서 hwpml을 xml형태로
만들려고 했으나 linesegment에서 하위를 읽어오는 방법은 말씀하셨듯이 의미가 없을듯 해서 paragraph에서 하위속성을 가져올려고 하는데 어떻게 어떤 부분을 참고해서 작업해야 할지 난감해서요. 가르침을 주시면 감사하겠습니다.

**Comment by neolord0** [comment]
안녕하세요.. 
이 부분은 저희 회사 정책상 무료로.... 제가 코멘트 해드릴 수 없는 부분입니다.
앞에 대문에서 이미 설명드렸듯이.. 라이브러리를 포함한 상용 제품을 판매중입니다.
이 부분에 대한 자세한 기술지원을 받으려면... 유료 서비스를 받으셔야 합니다. 
일단, 한컴에서 제공한 문서를 참조하고 한글 프로그램에서 hwp를  hwpml 로 저정한 후에 비교해 보는 방법으로 작업하는 게 좋을 듯 합니다.

**Comment by supersolaris** [comment]
고맙습니다.
