### ISSUE TITLE
색상 변경

### ISSUE THREAD

**Issue by Devgiit** [neolord0/hwplib#223]
안녕하세요.
hwplib 매우 유용하게 사용하고 있는 사용자입니다.

Before : **가나** 다라 _마바_
After : **가나** 다라(빨강) _마바_

원문은 유지한 채 '다라' 부분만 색상을 변경하는 방법이 있을까요?

바쁘실 텐데, 확인 한 번 해 주시면 감사합니다.

**Comment by neolord0** [comment]
안녕하세요. 
이 라이브러리는 상용으로 판매되고 있습니다.  상용 라이센스와의 차별을 두기 위해 사용법 등에 가이드는 하지 않습니다.
이점을 양해해 주시길 바랍니다.

직접 찾아 보시길 바랍니다.
