### ISSUE TITLE
이미지 파싱 정보 관련

### ISSUE THREAD

**Issue by nicebeak** [neolord0/hwplib#225]
안녕하세요
제공해주신 소스로 한글문서의 이미지를 읽는 부분을 테스트하고 있는데
각 paragraph에서 이미지 정보를 얻을 수는 있지만 paragraph에 있는 이미지와 실제 이미지를 매핑할 수 있는 부분을 찾지 못해서 문의드립니다.<BR>

**아래의 순서처럼 이미지를 등록**했습니다.<BR>
![image](https://github.com/neolord0/hwplib/assets/56873214/d6e8d076-44ac-411c-8397-2e9397dbcd4a)
<BR>
첨부 소스를 작성하여 이미지를 읽어서 출력해보면(아래 출력결과)
이미지를 가지고 있는 hwpFile.getBinData().getEmbeddedBinaryDataList()와 
ID를 가지고 있는 PictureInfo의 getBinItemID() 와 연결점을 찾을 수 없는데 혹시 방법이 없을까요?

다음은 첨부 소스로 출력한 결과입니다.
**[출력결과]**
![image](https://github.com/neolord0/hwplib/assets/56873214/24b3cb71-df07-41a5-8418-732e662a500d)

**[테스트 소스]**
[image_test.zip](https://github.com/neolord0/hwplib/files/12517819/image_test.zip)

**Comment by nicebeak** [comment]
혹시 PictureInfo의 getBinItemID()와 파일명 뒤에 있는 숫자 BINxxx1.bmp 와 연결되는건가요? 
![image](https://github.com/neolord0/hwplib/assets/56873214/91c9cadd-5904-4158-a569-7137d63e2286)

**Comment by neolord0** [comment]
안녕하세요.

해당 내용은 wiki 에 포함되어 있습니다. 
참고하세요.

**Comment by nicebeak** [comment]
감사합니다.
