### ISSUE TITLE
hwplib 오픈소스에 감사드립니다.

### ISSUE THREAD

**Issue by deokgyuhan** [neolord0/hwplib#226]
안녕하세요 저도 코딩을 좋아하는 마음만 개발자인 사람입니다.
 
hwplib를 메이븐 레파지토리에서 보고 여기까지 찾아와봤네요.

저는 neolord0님의 hwplib 라이브러리를 활용하여  플러터에서 한글파일의 텍스트 추출하는 플러그인을 만들었습니다.

라이브러리 저자에 대한 정보출처는 제 프로젝트에도 명확히 밝혔습니다.

다시한번 오픈소스에 감사드리며 항상 화이팅하세요 ^^

https://pub.dev/packages/flutter_hwp_lib

**Comment by neolord0** [comment]
안녕하세요
네.. 도움이 되었다니... 
다행입니다. 
^^;
