### ISSUE TITLE
안녕하세요. 텍스트하고 이미지를 사용 할 때 이미지 위치를 조정 할 수 있을까요?

### ISSUE THREAD

**Issue by stylealist** [neolord0/hwplib#228]
안녕하세요 텍스트하고 이미지를 혼용사용하는중이고 이미지 삽입 클래스에서 prop.setLikeWord(true); 해당 옵션만 true로 변경하여 이미지를 텍스트로 인식하게하였습니다. 그런데 이미지 위치가 항상 최상위에 출력되는 부분이 있는데 순서대로 출력되게하려면 어떤부분을 수정해야하는지 궁금합니다!
현재) 
<이미지>
■ 이미지가 아래로

원하는 hwp상태) 
■ 이미지가 아래로
<이미지>

아래는 코드입니다!
Inserting_CharShape tmcs = new Inserting_CharShape();
tmcs.test(hwpFile,"■ 이미지가 아래로",13,true, 0);
Inserting_Image tii = new Inserting_Image();
tii.insertShapeWithImage(hwpFile, image);

**Comment by neolord0** [comment]
안녕하세요.
setLikeWord() 글자처럼 속성을 설정하는 것입니다.
이 라이브러리는 상용으로 판매되고 있기 떄문에, 정책상 무료 사용자에게는 사용법에 대한 세세한 질문은 받지 않습니다. 
이상입니다.

**Comment by stylealist** [comment]
넵 답변감사합니다!
