### ISSUE TITLE
긴 문장이 `paragraph` 안에서 개행(줄바꿈)없이 겹쳐짐

### ISSUE THREAD

**Issue by greenn-lab** [neolord0/hwplib#230]
안녕하세요! 한글문서가 다른언어에서는 지원되는게 없어서 난감했는데, 
Java로 API 구성된 걸 보고 너무 반가웠고, 덕분에 감사의 인사 먼저 전해드립니다 😘

```
section.insertParagraph(line++, paragraph);
```
위와 같은 코드로 여러 `Paragraph` 문장을 하나의 `Section` 에 추가해 가도록 코드를 작성했고요.
실제로 파일로 출력해서 보는데...

![image](https://github.com/neolord0/hwplib/assets/46670613/3554b02d-7da8-4b9b-96f1-6897cde80ea6)
긴 문장은 이렇게 개행(줄바꿈)없이 겹쳐서 나오고 있습니다.

제가 API를 잘못 사용하고 있는 건지, 아니면.
누락한 내용이 있는건지. 조언 부탁드리고자 합니다.

감사합니다 :)

**Comment by neolord0** [comment]
안녕하세요.
아마도 줄 간격이나, 그런 속성값이 잘 못 된 거 같습니다.
원하는 hwp 파일을 한글 프로그램으로 만들고, 그 파일을 라이브러리로 읽어서, 
greenn-lab님이 만든 hwp 파일과 비교해 보세요(디버그툴 등 사용) 
이 두파일의 차이점을 확인할 수 있을 거라 생각됩니다.

**Comment by greenn-lab** [comment]
감사합니다. 조언에 힘입어 이슈가 해결 되었습니다. 행복하세요~
