### ISSUE TITLE
한글파일 5.1.0.1 버전 변환안됨에 따른 문의

### ISSUE THREAD

**Issue by leewj98** [neolord0/hwplib#231]
안녕하세요? 최근 한글변환파일을 잘 쓰고 있는 사람입니다.
다름이 아니오라 한글파일을 다운받아서 변환하려 하는데 5.1.0.1버전의 파일은 아래와 같은 메세지가 뜨면서 변환이 불가한 것을 인지하게 되었습니다.
"File version '5.1.0.1' is not imcompatible."
이 부분에 대한 해결방법이 있는지 여쭈려고 이렇게 문의드립니다.

**Comment by neolord0** [comment]
안녕하세요..

"File version '5.1.0.1' is not imcompatible." 

이 메시지는 hwplib에서 출력된 것이 아닌 거 같습니다.
어떤 상황인지 정확히 알 수 없어서. 답변드리기 힘드네요.
