### ISSUE TITLE
안녕하세요. 질문사항이 있어 글 올립니다.^^

### ISSUE THREAD

**Issue by kwonhyun** [neolord0/hwplib#233]
안녕하세요.
이런 라이브러리를 만들어주셔서 참 감사한 마음입니다.^^
한가지 여쭤볼게 있어서 글올립니다.
제가 하려는 것은 테이블 셀에다가 또 다른 테이블을 넣고 싶은 건데요..
일단  문서 BODY 에 있는 테이블의 셀에 있는 필드에는 필드명 찾아서 넣었는데요.(사실.. 된 것인지는 좀 더 테스트를 해봐야 되요..^^)
테이블의 셀에 테이블이 있고 그 내부 테이블의 셀의 필드는  찾지 못해서인지 넣질 못하더라구요..
이 부분이 현재 소스로 가능한 것인지 궁금합니다.
아예 안되는데 하려고 하는 것보단 방법을 찾는 게 더 좋을 것 같아서요..^^;
감사합니다~

**Comment by neolord0** [comment]
안녕하세요.
테이블 셀 안에 테이블이 있고 그 테이블 셀안에 필드를 못 찾는다고 하셨는데
테스트 해보니 잘 됩니다.

**Comment by kwonhyun** [comment]
훔...제가 잘 못 한 건가 보네요..
다시 한번 해볼게요..^^
감사합니다.
