### ISSUE TITLE
안녕하세요. 라이브러리 관련하여 문의 드립니다..

### ISSUE THREAD

**Issue by dnsdl126** [neolord0/hwplib#235]
먼저 라이브러리 제공해주신 부분에 감사드립니다 :)
저는 지금 html to hwp 작업을 진행하고 있고 이부분 제공해주신 샘플이 있어 많이 참고가 되었습니다.
일단 제가 변경해야하는 html 은 table이 2개가 담겨 있어 제공해주신 HtmlToTableExample 코드부분에
 '동적으로 i번째 문단에 테이블을 생성하시려면 그 만큼 문단이 필요합니다.' 라고 주석을 남겨주신 부분을 확인하였는데
 저같은경우 2번째 테이블 의 경우 2번째 페이지에 작성되어야 하여 첫번쨰 표에대한 정보를 그리고 
   hwpFile.getBodyText().getSectionList().get(0).addNewParagraph(); 로 문단을 추가하여 2번째 표를 그리게 하였으나 
NullPointerException  이발생되었습니다.  바쁘실텐데 혹시 제가 잘못이해한 부분이 있는지 답변 부탁드립니다...

**Comment by neolord0** [comment]
안녕하세요.
회사 일때문에.. 답변이 늦었습니다.
해결 하셨다니... 다행입니다.
