### ISSUE TITLE
안녕하세요! 테이블 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by dnsdl126** [neolord0/hwplib#237]
안녕하세요! 먼저 라이브러리 제공해주신점 감사드립니다.
제공해주신 라이브러리로 table cell 을 추가하는 코드를 테스트 중입니다. 
 cell 을 추가 할때 table 높이가 한 페이지를 넘어가게 될 경우 새로운 table 을 추가하도록 진행하려 하는데
table의 높이를 확인하는 방법이 있는지 문의드립니다 ㅠㅠ 
그리고 cell에 text를 추가 했을 때 변경된 cell의 높이를 알수 있을까요..?
![image](https://github.com/neolord0/hwplib/assets/58206035/3f35a6a1-9599-4daa-bc2f-8cb7aad983b6)

**Comment by neolord0** [comment]
안녕하세요. 
셀에 포함된 내용의 높이를 계산하는 부분은 지원하지 않습니다.
높이를 구하려면.. 그리는 알고리즘이 있어야 하는데..  그러기 위해서는 뷰어 기능의 완벽한 구현이 필요합니다.  
셀 높이를 0(또는 -1)로 주시면.. 셀 안에 글자에 맞게 셀이 늘어 납니다.

**Comment by dnsdl126** [comment]
답변 감사합니다 ㅠㅠ 그러면 혹시 table의 높이를 알수있는 방법도 혹시 없을 까요 ? 
table  row가 일정 수 이상 늘어나면 페이지를 넘어가게 되는데 이때 row 생성을 멈추고 section을 추가해서 
새로운 table controll을 추가하려고 해서요..

**Comment by neolord0** [comment]
cell 안에 들어가는 문단 리스트는 기본적으로 한글 파일 전체에 들어가는 문단 리스트와 동일한 구조 입니다.  
한글 파일의 모든 기능이 들어갈 수 있죠.

정확히 계산하려면.. 한글 파일의 모든 기능을 구현해야 하겠지만.
셀 안에 들어가는 내용이나 글자 크기 등을 특정할 수 있다면.. 간이적인 방법으로 간단히 구할 수 있으리라 생각됩니다.

**Comment by dnsdl126** [comment]
답변 감사합니다 알려주신 내용 토대로 한번더 확인해보겠습니다 ㅠㅠ
