### ISSUE TITLE
ParagraphAdder를 통해 파일복사 시 복사한 파일의 개요문단  수준이 1로 고정되는 현상

### ISSUE THREAD

**Issue by jihazard** [neolord0/hwplib#238]
안녕하세요 라이브러리 잘 사용하고 있습니다.
감사합니다.

ParagraphAdder을 이용하여 2개의 문단을 합칠 경우 
개요번호 가 정상적으로 합쳐지지 않는 현상이 있어 문의드립니다.

![image](https://github.com/neolord0/hwplib/assets/18673029/e24f2d4e-7d7f-476c-9a59-0ecee193cf97)

![image](https://github.com/neolord0/hwplib/assets/18673029/fc9b8b58-b580-44a6-8405-afa3c6983393)
같은 수준의 개요문단을 가진 2개의 파일을 ParagraphAdder를 통해 합칠 경우 추가한 파일의 개요문단이 1로 변경 되는데 
문서상의 "4.하세"를 개요 문단 2수준  "4.1 하세"으로 변경하려면 어떻게 해야할까요?

Parashape를 추가 후 수정하거나 LevelNumbering을 변경 하는 방법을 사용해봤으나 정상적으로 작동하지 않네요.
어떻게 접근해야 할지 조언 부탁 드립니다.

[Adding_Paragraph_Between_HWPFile.zip](https://github.com/neolord0/hwplib/files/13546769/Adding_Paragraph_Between_HWPFile.zip)

**Comment by neolord0** [comment]
안녕하세요..
ParagraphAdder에서 버그 수정했습니다.
원래는 문단 모양에서 개요 수준을 저장하는 부분이 3비트(0~7)이었으나,
요즘 버전에서 1-10 수준으로 확장하면서 이 정보를 다른 곳에 저장하는 것 같습니다.
소스를 다시 받아서 테스트 해 보세요.

**Comment by jihazard** [comment]
정상적으로 작동 하는 것 확인 하였습니다. 
감사합니다.
