### ISSUE TITLE
누름틀에 값 입력 시 발생하는 현상 문의드립니다.

### ISSUE THREAD

**Issue by kwonhyun** [neolord0/hwplib#239]
안녕하세요.
또 다시..문을 두드립니다..^^
누름틀에 값 입력 시 누름틀 고치기를 하지 않으면 정상적으로 보이는데 고치기를 하여 안내문을 수정하게 되면 값은 제대로 들어가지만
표현이 다릅니다.
![원본](https://github.com/neolord0/hwplib/assets/49061684/9ccd6122-7e2b-4d0e-b487-8200e21d83bc)
필드명은 정상은 (_TEST1_), 이상현상이 있는 것은 (_TEST2_) 입니다.
![결과](https://github.com/neolord0/hwplib/assets/49061684/ad16190a-6d05-4c51-8637-3c0c5abb920f)

Setting_FieldText 클래스를 이용하여 넣었습니다.
값은 정상인데 처음부터 일부분은 누름틀의 안내문 처럼 보여집니다.(색상과 폰트-이탤릭)
이런 현상이 발생합니다.
어떻게든 만들어주신 라이브러리를 사용은(물론 만들어주신 예제를 사용하지만요..^^) 하겠는데 도저히 수정을 못하겠습니다..ㅠㅠ;
이해가 잘 안 가서..ㅠㅠ; 그리고 한글 포멧 문서를 봐도...사실 이 부분 자체를 이해를 못하니 코드도 이해를 못하는 것 같네요.ㅠㅠ;
감사합니다..

**Comment by neolord0** [comment]
안녕하세요..
글자색이 바뀌는 건.. 문단에 글자모양 속성이 그렇게 설정된 상태인 거 같습니다. 
원하는  결과의 hwp 파일을  한글 프로그램으로 생성하여 프로그램으로 생성된  hwp 파일을 비교해 가면서.. 수정하세요.
hwp 파일을 라이브러리로 읽어서 이클립스 등에 프로그램에서 디버그 하면서 비교하면 다른 부분을 발견할 수 있고
수정하실 수 있을 겁니다.

**Comment by kwonhyun** [comment]
네. 말씀대로 해보겠습니다..
그런데 색상만이 아니라 폰트 자체도 누름틀 안내문의 폰트를 따라 가게 되더라구요...
."테스트 값2"를 한번에 넣은 건데 "값2"는 정상이고 "테스트"만 저렇게 나오는 거거든요. 
처음 첫 번째, 두 번째 누름틀 모두 만들고 나서 폰트나 색상을 건드리지 않은 상태였습니다.
그래서 첫 번째 것은 정상적으로 나오는 거구요...^^;
말씀대로 일단 디버깅 해가면서 수정해보겠습니다..^^
먄약..만약에... 되면...ㅎㅎ 공유하도록 하겠습니다..

감사합니다.^^
