### ISSUE TITLE
밑줄 텍스트 추출 관련 문제

### ISSUE THREAD

**Issue by ran4214** [neolord0/hwplib#24]
`		HWPFile hwpFile = HWPReader.fromFile(dataPath+fileName);`
		`ParaCharShape paraText =hwpFile.getBodyText().getSectionList().get(0).getParagraph(1).getCharShape();`

 getCharShapePeoperty 를 이용해서 문단안에있는 텍스트들의 밑줄의 종류를 가져오고 싶은데 도대체 어떻게 가져오는지 잘모르겠습니다.

**Comment by neolord0** [comment]
텍스트들의 밑줄이 정확히 어떤 속성인지 몰라서.. 답변을 드리기 힘드네요.. 

한글 프로그램에서 어떻게 설정하는지 알려주세요 ..

어디 메뉴에서  무슨 대화상자에서 무슨 속성으로 설정할 수 있는지 알면 답변하는데 도움이 될꺼 같습니다.

**Comment by ran4214** [comment]
![image](https://user-images.githubusercontent.com/22853225/42354607-f2ae783c-8102-11e8-934b-923d21573f40.png)

편집칸에 있는 가에 언더바있는거요.

**Comment by neolord0** [comment]
ParaCharShape 객체에는 글자 모양에 대한 속성들을 가지고 있는 CharShape의 인덱스와 그 속성들을 적용할 시작 위치가 쌍으로 나열되어 있습니다. 이것이 추가 되면서, 한글은 하나의 문단에 여러개의 글자 모양을 선택할 수 있게 됩니다.  

글자 모양 속성을  설정하려면 ParaCharShape 객체에 인덱스로 설정된 CharShape 객체를 찾아서 수정해야 합니다. CharShape는 DocInfo 객체 안에 있으며 인덱스 - 1번째 객체가 이 문단과 연결된 글자모양일 것 입니다.  이 CharShape  객체에서 수정할 수 있을 것 입니다.

**Comment by ran4214** [comment]
paraCharShape 는 맨윗 글 처럼 정상적으로 구하였는데 parCharShape 로 어떻게 CharShape 객체를 찾는지 감이 안잡힙니다. CharShape 객체만 얻으면 getUnderLineSort() 메소드로 쉽게 제가 원하는 기능을 사용할 수 있을 것 같습니다.

**Comment by neolord0** [comment]
음.. 제가 조망간 샘플 코드 하나 만들어 올리겠습니다.

**Comment by neolord0** [comment]
글자 모양을 만드는 코드(TestMakingCharShape.java)를 추가했습니다. 이 코드를 보시면 문단의 글자 모양을 어떻게 추출할지 알 수 있으니라 생각됩니다.

**Comment by ran4214** [comment]
친절한 답변 감사드립니다.
