### ISSUE TITLE
안녕하세요 테이블 관련 문의 드립니다!

### ISSUE THREAD

**Issue by dnsdl126** [neolord0/hwplib#243]
한페이지에 표를 그리고 그아래 에 표를 추가 하려고 하는데 이럴경우
 Section 에 새로운 Paragraph 를 추가하여 그려야 하는 건가요 ..? 
 ㅠㅠ 아니면 각 표마다 위치지정을 해줘야하는건가요 ..? ㅠㅠ 
 표를 3번 그리는것은 완료 하였으나 같은 위치에 반복적으로 table이 추가되어 문의 드립니다.

**Comment by neolord0** [comment]
안녕하세요.
상용으로 판매하고 있어서 회사 정책상 사용법에 대한 질문에는 답변할 수 없음을 양해해 주세요.
한글에서 표를 그려서 저장 후 그 파일을 라이브러리로 읽어서 분석하는 방식으로 작업하시면 될 거 같습니다.
