### ISSUE TITLE
안녕하세요 오류 This is not paragraph. 질문 드립니다

### ISSUE THREAD

**Issue by ImSangHyun888** [neolord0/hwplib#244]
해당 라이브러리 잘 사용하고 있습니다 감사합니다.

오류 해결에 도움을 얻고자 게시글을 등록합니다.

//orgFile >>hwp 파일이며 파일안에는 표셀,누름틀 등이 존재합니다.
HWPReader.fromFile(orgFile); 

모든 hwp파일이 아닌 특정한 것만 읽을때 문제가 됩니다.

현재 파악 결과 문서 정보가 5.1.1.0.1 파일이 This is not paragraph. 에러가 발생합니다.

다른 피씨로 다른이름으로 저장 또는 저장하고 다시 업로드 후 진행을 하면 문서 정보는 5.1.1.0.1 동일한데 정상 작동하네요.(내용 수정은 하지 않았습니다.)

if (sr.getCurrentRecordHeader().getTagID() != 66) {
            throw new Exception("This is not paragraph.");
        }

bodyText > section > ForSection  read > ForParagraphList read > ForParagraph read

바디 >> 섹션 >> 문단 세팅 할 때 문제가 되는걸로 지금 이해하고 있는데 맞게 이해 한 걸까요 ?

StreamReader TagID 대해서 설명과 예상되는 오류 원인이 있을까요?

바쁘시겠지만 해당하는 파일이 뭐가 문제인지 확인 해 주실 수있을까요 ..

**Comment by neolord0** [comment]
안녕하세요.. 
특정 파일에서 나는 문제는 그 파일이 있어야 문제를 파악할 수 있습니다.
문제가 발생하는 파일을 첨부해 주시면 검토해 보겠습니다.

**Comment by ImSangHyun888** [comment]
답변 주셔서 정말 감사합니다.
파일 첨부하였습니다.
검토 부탁드립니다. 감사합니다.
-----Original Message-----

**Comment by neolord0** [comment]
파일을 어디에 첨부하셨나요?
못 찾겠네요.

**Comment by ImSangHyun888** [comment]
네이버 메일로 보냈는데 첨부되지않았나요? 메일알려주실수있을까요 다시 보내겠습니다.

**Comment by neolord0** [comment]
neolord@hanmail.net 입니다.

**Comment by ImSangHyun888** [comment]
파일 첨부하여 메일 전송했습니다

감사합니다.

**Comment by neolord0** [comment]
안녕하세요.
파일을 받아서 테스트 해봤습니다.
최종 소스에서는 문제가 없습니다. 혹시, mvn 레퍼지토리에서 받았다면..다시 최신 소스를 받아서 연결해 주세요.
mvn 레퍼지토리는 차츰 업데이트 하겠습니다.

**Comment by ImSangHyun888** [comment]
답장 감사합니다.

혹시 파일을 열람하고 저장을 하신 후에 테스트를 하신건가요 ?

파일을 저장 후 진행하면 문제가 없는 상황이며 mvn repository 에서 최신 버전으로 진행했었습니다.

해당 파일을 그대로 진행하였을 경우 에러가 나타났었습니다. 

파일을 재 첨부 후 이메일로 전송했습니다.

정말 죄송하지만 한번만 더 확인 해 주실 수 있을까요?

**Comment by neolord0** [comment]
안녕하세요.
혹시나 다른 파일일까 해서.. 다시 테스트 해봤습니다만 에러가 없었습니다.
전에도 말씀 드렸듯이.. mvn repository에서 받은 거 말고..  github에 소스를 받아서 사용하세요.
mvn repository 는 최신 버전이 아닙니다.

**Comment by ImSangHyun888** [comment]
github 소스 받아서 사용해보겠습니다. 바쁘신 와중에 시간 내주셔서 감사합니다.
