### ISSUE TITLE
한글 2024 버전의 파일을 읽지 못하는 경우가 발생합니다.

### ISSUE THREAD

**Issue by JiniApp** [neolord0/hwplib#246]
안녕하세요 
라이브러리 사용 중 문의 사항이 있어 글 남깁니다.
한글2024 버전의 파일을 HwpReader.fromFile 로 읽다가 멈추는 현상이 발생하여 문의 드립니다.

[2024.zip](https://github.com/neolord0/hwplib/files/14475704/2024.zip)

**Comment by neolord0** [comment]
안녕하세요

올려주신 파일을 분석해보니.. CtrlHeaderGSO 부분에서 알 수 없는 2bytes의 데이타가 추가되어 있었습니다.
내용을 알 수 없어서... byte[] unknown으로 처리 했습니다.

다시 받아서 테스트 해보세요.

**Comment by JiniApp** [comment]
감사합니다 다시 받아서 해보겠습니다.
