### ISSUE TITLE
안녕하세요. 라이브러리 사용중 궁금한점이 있어서 문의드립니다.

### ISSUE THREAD

**Issue by dongkki** [neolord0/hwplib#248]
안녕하세요.
현재 유용하게 라이브러리를 사용하고 있는 일부 사용자입니다.

한글 문서를 생성하고 여러 쪽을 만든 상태입니다.
각 쪽마다 하단에 쪽 번호를 매기고 싶은데 어떤 옵션이 필요한지 궁금해서 문의 드립니다.

**Comment by neolord0** [comment]
안녕하세요.
한글 프로그램 사용법 질문 같습니다.
한글 프로그램의 메뉴얼을 보고 원하는 문서를 만들어 보세요.
그리고, 라이브러리에서 파일을 열어서 검토해 보세요.

사용법에 대한 질문은 회사 정책상 유료 계약을 해야 합니다.
감사합니다.

**Comment by dongkki** [comment]
한글 프로그램 사용법이 아닌 제공해주신 라이브러리를 기반으로 한글 파일을 생성했으며 
PageNumberPositionHeaderProperty 라는 쪽 번호 위치 컨트롤의 속성을 나타내는 객체를 찾았습니다.
번호 표시 위치 NumberPosition와 번호 모양 NumberShape 을 찾았는데 적용하는 방법에 대한 예시 코드가 없을까요??

**Comment by neolord0** [comment]
이전에 답변 드렸듯이.. 사용법이나. 예시 코드를 제공해 드리는 건 유료로 기술지원해 드려야 합니다.
직접 한글에서 파일을 만들고, 라이브러리로 읽은 후 개발툴에서 디버그 정보 등을 사용하여 
설정값을 확인후에 직접 설정하시면 가능할 거 같습니다.

**Comment by dongkki** [comment]
네 감사합니다.
