### ISSUE TITLE
안녕하세요. 테이블 셀 색상 관련해서 문의드립니다.

### ISSUE THREAD

**Issue by YoonTaeMinnnn** [neolord0/hwplib#249]
htmlToTableExample.java 를 참고해서 hwp에 테이블을 생성하고 있습니다. 

blank.hwp (빈 hwp파일) 의 모든 칸에 공백을 만들어주지 않으면, 테이블을 삽입할때 paragraph.getText() 에서 null이 반환되어 에러가 발생합니다. (첫번째 테이블은 잘 생성되나, 두번째 세번째 부터는 null값 반환됨)
직접 공백을 만드는 방법외에 다른 방법이 있을까요?

**Comment by neolord0** [comment]
안녕하세요.

라이브러리 사용법에 대한 질문은 회사방침에 따라 유료 기술지원으로 처리하고 있습니다.
wiki 나 다른 샘플을 참고하여 찾아보시면 하실 수 있으리라 생각됩니다.
