### ISSUE TITLE
한글문서 읽어들일때

### ISSUE THREAD

**Issue by accforaus** [neolord0/hwplib#25]
일단 이런 엄청난 라이브러리를 개발해주셔서 정말 감사합니다.

다름이 아니라. 라이브러리를 빌드후 .jar로 라이브러리를 불러들여와 사용하려고 하는데

HWPReader.fromFile()에서 오류가 발생합니다.

`Exception in thread "main" java.io.FileNotFoundException: no such entry: "Section1", had: [Section0]`
`Exception in thread "main" java.lang.Exception: List header must be located.`

jdk7, 8로 해보아도 결과는 같았습니다. 혹시 읽히지 않는 한글파일의 조건이 있나요. 몇시간 씨름하고 있는데, 답답한 마음에 올려봅니다.

한글 버전은 NEO사용중입니다.

문서버전은 5.0.2.5.1, 프로그램 버전은 7.5.12.721 입니다.

계속 테스트중이긴 한데, sample_hwp에 들어있는 파일들은 읽고 쓰는 것이 가능한데, 제가 보유하고 있는 한글 파일들은 대부분 열지 못합니다.

**Comment by neolord0** [comment]
neolord@hanmail.net으로  파일을 보내주세요.  
버전에 따라 파일의 저장형태가 약간씩 달라지는 데 서 오는 현상인거 같습니다. 
분석해 보겠습니다.

**Comment by neolord0** [comment]
보내주신 파일로 테스트 하여 수정했습니다.
받아서 테스트 해보세요.

**Comment by accforaus** [comment]
감사합니다. 현재 30여개 이상 테스트중인데 아무 이상없이 잘 읽힙니다.

잘 사용하고 라이브러리 사용한 깃헙 프로젝트 열면 말씀 드리겠습니다.
