### ISSUE TITLE
폰트 색상 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by stgulaa** [neolord0/hwplib#250]
안녕하세요, 현재 한글 파일의 데이터 중 테이블 중 셀의 폰트 색상이 붉은 색일 때의 값을 조회하고 싶습니다.

하지만 현재 Paragraph에서는 텍스트의 위치나 글자모양은 가져오는 메서드는 존재하지만 색상에 대한 사항은 없습니다.
혹시 이 부분에 있어 현재 소스로 구현이 가능한지 여쭙고 싶습니다

**Comment by neolord0** [comment]
안녕하세요.
문의하신 "문단의 글자 색을 가져오는 기능"은 가능합니다. 
이 사이트에 wiki을 참고하셔서 작업하시면 가능할 거 같습니다.
회사의 방침상 더 자세한 기술지원을 유료로 진행해야 함을 양해해 주세요.
