### ISSUE TITLE
setCtrlHeaderRecord 함수에서 테이블이 여러개일 경우  테이블 높이를 계산해서 y좌표 지정을 하고 싶은데 테이블 높이를 계산하는 방법이 있을까요?

### ISSUE THREAD

**Issue by rlarmstn71** [neolord0/hwplib#253]

**Comment by neolord0** [comment]
안녕하세요.
테이블 높이를 구하고 싶다고 하셨는데요. 이는 파일에 저장되는 정보가 아닙니다.  
테이블에 설정된 정보, 셀에 포함된 내용이나 글자속성 등을 적용해서 테이블을 그려야 알 수 있는 정보입니다.
한글은 문단안에 테이블이 들어가고,  테이블 셀안에 문단이 들어가는 계층적인 순환구조이기 때문에, 
테이블을 그린다는 것은 한글 파일을 그린다는 것과 동일입니다. 

제가 실험적으로 해봤는데, 혼자하기엔 무리였습니다. 
이 기능이 필요하다면 한컴이나 뷰어 업체에 문의해 보세요.
