### ISSUE TITLE
안녕하세요. 질문이 있어 방문하게 되었습니다.

### ISSUE THREAD

**Issue by rlarmstn71** [neolord0/hwplib#254]
안녕하세요. 우선 제공해주신 오픈소스를 잘 사용하고 있는 사람으로써 감사합니다.
htmltohwp소스를 기반으로 사용하고 있는데 테이블 태그를 이용하여 표를 만들어 데이터를 넣었습니다.
근데 줄변경을 하고 싶어서 br,&nbsp;,\r\n 등 다양하게 넣어서 사용하여 봤는데 인식이 되지 않아 질문을 드리게되었습니다.
그리고 테이블안에 이미지를 넣어야 하는데 img태그는 혹시 인식이 되지 않는 것일까요???

**Comment by neolord0** [comment]
안녕하세요..
htmltohwp 는 일종의 예제입니다.  html을 이렇게 파싱하고 hwp로 변경하려면 이렇게 할 수 있다는 예제입니다.
html의 출력결과를 완벽히 hwp로 변경하는 건 엄청난 일입니다.
html 분석 등은 html 관련 라이브러리를 이용하여야 합니다.
