### ISSUE TITLE
안녕하세요. 질문드립니다.

### ISSUE THREAD

**Issue by keamy-eun** [neolord0/hwplib#255]
sample안에 컨트롤러 실행시 '손상된 스크립트가 포함되어 있습니다.'라는 문구가 뜹니다.
내용은 반영이 잘 되지만 저 문구가 왜 뜨는걸까요?

**Comment by neolord0** [comment]
안녕하세요.
어떤 파일에 어떤 컨트롤인지.. 좀 더 자세히 말씀해주세요..

**Comment by keamy-eun** [comment]
kr/dogfoot/hwplib/sample에 있는 컨트롤러들 전부 같은 현상입니다. 
예를 들어 Inserting_CharShape.java를 실행하고자하면 
![화면 캡처 2024-06-13 100203](https://github.com/neolord0/hwplib/assets/77378816/d4ebf76e-dcd4-4cb3-9420-0c432390e55a)
이런 현상이 발생합니다.

라이브러리 내려받고 jsoup, lombok 인식을 못해서 디팬던시 추가만 했습니다.

**Comment by keamy-eun** [comment]
앗 네,, 컨트롤러 전체 같은 현상입니다.
코드를 간소화해서 blank.hwp를 가져다 새로 생성만 하는 로직으로 실행해도 같은 현상이더라구요.
의심이 가는건 버전문제인데,, 제가 한글2020을 써서 그런걸까요?
오피스뷰어로 하면 현상이 안나타납니다.

그리고 라이브러리 잘 쓰고 있습니다. 너무 감사합니다.

**Comment by neolord0** [comment]
음.. 제가 2020버전이 없어서.. 테스트 해보진 못 했지만..
오류의 원인일거라 추측되는 부분을 수정하였습니다.
아래의 첨부파일 받아서 테스트 해주시고 결과를 알려주셨으면 합니다.
감사합니다.

[hwplib-1.1.6.jar.집.zip](https://github.com/user-attachments/files/15860304/hwplib-1.1.6.jar.zip)

**Comment by neolord0** [comment]
그리고, 혹시 모르니.. 한컴 사이트에서 보안패치를 받아서 설치 해보세요.
한글버전 관련 오류의 대부분이 보안패치를 설치하는 것 만으로도 사라집니다.

**Comment by keamy-eun** [comment]
보안패치 설치 없이 첨부해주신 내용으로 해보니 해결됐습니다!
kendo grid를 한글 문서로 변환하는데 일주일 걸린것같습니다..
덕분에 완벽한 결과물이 나왔습니다. 감사합니다 !! ^^

**Comment by neolord0** [comment]
음..그렇군요. 
수정한 소스는 push 했고요.. 메이븐 리포지토리에는 조망간 올리겠습니다.
테스트 및 결과 보고 감사합니다.
