### ISSUE TITLE
현재 문단에 위치

### ISSUE THREAD

**Issue by sgh9196** [neolord0/hwplib#257]
안녕하세요. 우선 제공해주신 오픈소스를 잘 사용하고 있습니다. 감사합니다.

hwplib 라이브러리를 사용하여 대상 문서에 문단이 어느 위치에 있는지 파악하고싶습니다.

BodyText 안에 있는 getSectionList를 활용하여 문서에 생성된 구역을 순회하며 특정 텍스트를 가진 문단을 찾으려고 합니다.

하지만 여기서 궁금한 점이 생겼습니다.

 getSectionList는 구역을 가지고 오는 API로 해석되는데 쪽을 가지고 오는 API가 제공이 되고 있는지 궁금합니다.

**Comment by neolord0** [comment]
안녕하세요

hwp 파일 포맷에는 쪽(page)이라는 개념은 없습니다.
한글 프로그램을 통해 그려지는 과정에서 쪽(Page)이 생성된다고 생각하시면 됩니다.
hwplib는 지원하지 않는 기능입니다. 한글 뷰어 업체와 협의해 보세요.

감사합니다.
