### ISSUE TITLE
HWP 내용의 각 문단에서 줄바꿈 문자(개행문자)가 있는지 어떻게 확인이 가능한가요.

### ISSUE THREAD

**Issue by wavor** [neolord0/hwplib#258]
hwplib를 통해서 각 paragraph에 대한 text를 추출해보면,
 hwp파일의 각 문단에 대한 텍스트가 추출되는데,
 문단 중간에 있는 개행문자(shift + enter)를 무시하고 문단의 모든 텍스트가 나오고 있어서, 문단 텍스트 내용을 나눌 수가 없습니다. 
1. 개행문자가 있으면 개행문자를 중심으로 문단을 나누거나
2. 아니면, paratext 내에 개행문자를 찾을 수 있는 방법이 있으면 좋겠습니다

**Comment by neolord0** [comment]
안녕하세요

아래 코드와 같이 TextExtractOption 객체에 withControlChar() 속성을 true로 넣어주면
탭, 개행 등의 제어문자가 표현됩니다.
  
...java
        TextExtractOption option = new TextExtractOption(TextExtractMethod.OnlyText, false);
        option.setWithControlChar(true);
        String text = TextExtractor.extract(hwpFile, option);
...java
