### ISSUE TITLE
문단번호 모양이 글머리표로 설정되어 있는 문서인 경우 문서정보 이상함

### ISSUE THREAD

**Issue by wavor** [neolord0/hwplib#259]
HWP문서의 문단모양에서 글머리표로 지정된 문단이 1개라도 있으면,
DocInfo 의 정보가 이상합니다.

DocInfo.getParaShapeList()
DocInfo.getStyleList()
DocInfo.getCharShapeList()

모두 빈 상태로 나옵니다.

해결할 수 있는 방법이 있을까요?

**Comment by neolord0** [comment]
안녕하세요.
글머리표가 설정된 문단을 포함하는 파일을 읽을 때 말씀하시는 건가요?

파일을 업로드 해 주시면 살펴보겠습니다.

**Comment by wavor** [comment]
P {margin-top:2px;margin-bottom:2px;} 나. 분할지급 부분의
 내용에 글머리표가 적용되어 있습니다...확인부탁드립니다. --- Original Message ---
From    :  "박성균(Park.sung.kyun)"
To      :  "neolord0/hwplib"
Date    :  2024/07/27 토요일 오전 12:00:14
Subject :  Re: [neolord0/hwplib] 문단번호 모양이 글머리표로 설정되어 있는 문서인 경우 문서정보 이상함 (Issue #259)


안녕하세요.

글머리표가 설정된 문단을 포함하는 파일을 읽을 때 말씀하시는 건가요?
파일을 업로드 해 주시면 살펴보겠습니다.

?
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: @github.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/neolord0/hwplib/issues/259#issuecomment-2252949950",
"url": "https://github.com/neolord0/hwplib/issues/259#issuecomment-2252949950",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wavor** [comment]
hwp파일은 첨부로 업로드가 되지 않아서 메일로 보냈습니다

**Comment by neolord0** [comment]
메일에 파일이 첨부되지 않았습니다.
다시 보내주세요.

**Comment by wavor** [comment]
[매뉴얼_정기예금(글머리).zip](https://github.com/user-attachments/files/16405776/_.zip)
글머리표 관련해서 위의 첨부파일 압축해제 해서 보시면 됩니다...

**Comment by neolord0** [comment]
올려주신 파일을 살펴봤는데, 
일반적으로 문단모양 정보들을 파일의 헤더부분에 저장하고 각 문단에서 링크하여 사용하는데, 
이 파일은 한글의 옵션이나 특정기능으로 인해 프로그램 기본값으로 저장하고 있는 문단모양 정보들을 사용하는 거 같습니다.
파일을 보면 각 문단이 가리키는 문단모양 아이디(인덱스)가 음수로 설정되어 있는데, 이럴 경우 프로그램에 저장된 기본값으로
설정하는게 아닐까 추측됩니다.  이럴 경우 음수값의 문단모양 아이디(인덱스)이  가리키는 문단모양 정보를 추측해야 하는데...
한컴 개발자가 아닌 이상은 힘들 거 같습니다.

**Comment by wavor** [comment]
네 답변감사합니다.
그러면 해당 문서에서 글머리표로 문단모양이 지정된 문단만 제거하면,
DocInfo.getParaShapeList()
DocInfo.getStyleList()
DocInfo.getCharShapeList()
들이 모두 정상적으로 들어오는데, 
문단모양 인덱스값이 음수로 지정된 특정 글머리표 때문에 발생하는 거라고 보면 될까요?

**Comment by neolord0** [comment]
저도 한컴관계자가 아니라.. 정확하게는 모르지만 제가 테스트해 보기로는..
문단모양에 포함된 속성(가로정렬, 왼쪽 여백 등)에 새로운 값이 설정되지 않고..
프로그램 기본값 대로 사용하면, 문단모양 속성들이 파일에 안 생기고(DocInfo.getParaShapeList())
문단에 문단모양 아이디값(Paragraph.getHeader().getParaShapeID()) 이 음수로 되는 거 같습니다.
이런 상황이 되면 문단모양에 연결된 글머리표 정보도 파일에 저장되지 않는 거 같습니다.
올려주신 파일에서 보면, 
DocInfo.getParaShapeList() 문단모양
DocInfo.getStyleList() 스타일
DocInfo.getNumberingLIst() 문단  번호
DocInfo.getBulletList() 글머리표 
이 저장이 안되어 있습니다. 
이 부분이 모두 문단/문단모양/글머리표 등과 관련된 부분입니다.

**Comment by wavor** [comment]
한글문서에서 문단번호모양 글머리표 관련해서 테스트해보니,
문서내 전체 문단에서, 
1. 문단번호모양에 글머리표는 1개의 글머리표로 통일해서 사용하면,
    -> docinfo에서 정상적으로 문단모양이 들어오고,
2. 문단번호모양 글머리표를 2종류 이상으로 사용하면,
    -> docinfo.getParaShapeList() 가 빈값으로 들어오네요...

특이한건, 표에서는 각 셀마다 다른 글머리표를 사용해도 문제가 없습니다.

어떤 기준인지 잘 모르겟네요

**Comment by neolord0** [comment]
제가 추측하기로는... 문단 모양에 포함된 왼쪽 여백 등의 속성을 변경하면..
프로그램이 처음 가지고 있는 문단 모양과 달리지기 때문에.. 문단 모양의 정보를 hwp 파일에 저장하는 게 아닐까 생각됩니다.
문단 모양을 수정하지 않고 프로그램에서 제공한 것을 그대로 사용하는 경우...
파일 내부에 저장할 필요가 없다는 생각을 할 수 있지 않을까 생각됩니다.
