### ISSUE TITLE
how to auto break or warp text line in table cell?

### ISSUE THREAD

**Issue by zuoliang0** [neolord0/hwplib#26]
how to make the cell content auto warp for cell width.
look like this :
![image](https://user-images.githubusercontent.com/8434253/42870788-592756d6-8aab-11e8-957e-e05a6ed1f0e0.png)

i watch the file use `한워드 2018` create file they have two `lineSegItem`

![image](https://user-images.githubusercontent.com/8434253/42870771-486ff460-8aab-11e8-959f-507ed41fc0c6.png)
and it have a `textStartPositon`
![image](https://user-images.githubusercontent.com/8434253/42870880-909be550-8aab-11e8-88b5-a1f7869837a3.png)
i want sure the `textStartPositon` is control the cell content line warp or maybe have other way ?

thank you .

**Comment by neolord0** [comment]
Hangul supports Text Wrapping by LineChange property in ListHeaderForTextBox Object.
The value of this attribute can be obtained as follows.

Section s = hwpFile.getBodyText().getSectionList().get(0);
Paragraph firstParagraph = s.getParagraph(0);
ControlRectangle rect = (ControlRectangle) firstParagraph.getControlList().get(2);
System.out.println(rect.getTextBox().getListHeader().getProperty().getLineChange());

If This property value is Normal, Texts have warpped. 

And, I think LineSeqItem seems to store a pre-calculated value to draw a Hangul file quickly.
The text is drawn well without the LineSeqItem, except for the text line's space function.

LineSeqItem.textStartPosition is the text start position of the line represented by LineSeqItem in the full text of the paragraph. The figure above shows that the second line starts at index 2( zero-based).

**Comment by zuoliang0** [comment]
ok, i find the cell's listHeader also have the `ListHeaderPropertyForCell` same `setLineChange` method .
i check the property is `Normal` 
![image](https://user-images.githubusercontent.com/8434253/42915343-f85e64b6-8b31-11e8-8a9e-7cac9ee0552f.png)

the file open look like:
![image](https://user-images.githubusercontent.com/8434253/42915427-70a7b6d4-8b32-11e8-9969-f153284e0423.png)
i'am not use the text box just use the cell for contain text.

maybe i should be send the .hwp file and code for you ?

**Comment by neolord0** [comment]
yes. I want you to send them.

**Comment by zuoliang0** [comment]
i test the text sure warped,but some word not show full
![image](https://user-images.githubusercontent.com/8434253/42922360-d7d05760-8b52-11e8-9645-b497cbad7e55.png)

**Comment by zuoliang0** [comment]
i find the problem, when i set the `ParaShape` for  Paragraph the cell content will be not warp.
```
                ParaShape paraShape = hwpFile.getDocInfo().addNewParaShape();
		paraShape.getProperty1().setAlignment(Alignment.Left);
		int id = hwpFile.getDocInfo().getParaShapeList().size() - 1;
		ph.setParaShapeId(id);
```

but i don't know how fix it, 
the new code has send for you mail.

**Comment by zuoliang0** [comment]
hello ，do you receive my email? if you have any question you can give me feedback.
thank you

**Comment by neolord0** [comment]
[TestMakingTableTextWarp.zip](https://github.com/neolord0/hwplib/files/2221612/TestMakingTableTextWarp.zip)

According to my testing, we need a LineSegItem object for each line segmented for text-wrapping. However, the value of the TextStartPositon property in the LineSegItem object is hard to compute. So, I did not create any LineSegItem objects. And I set the value of the LineSpace property on the ParaShape object that is not in your code.

If you save this file again from Hangul, LineSegItem is automatically created.
Look at my attachment.

**Comment by zuoliang0** [comment]
thank you.
i try you code ,it's work for auto text-wrapping.

you say 
> the TextStartPositon property in the LineSegItem object is hard to compute

it mean if i need set text wrapping by hand then must be compute the `LineSegItem's TextStartPositon ` property ?

**Comment by zuoliang0** [comment]
in my program i'm use the `\n` to mark break line,
so i just easy compute the postion.
![image](https://user-images.githubusercontent.com/8434253/43113661-d688863c-8f2d-11e8-988c-0fb17885c39a.png)

this is my code:

```
private  void setLineBreak(String text,Paragraph firstParagraph, int width){
        ParaLineSeg lineSeg = firstParagraph.getLineSeg();
        if (text.contains("\n")) {
            int i =-1;
                while ((i=text.indexOf("\n", i+1 ))!=-1){
                LineSegItem lineSegItem = lineSeg.addNewLineSegItem();
                lineSegItem.setTextPartHeight(1000);
                lineSegItem.setStartPositionFromColumn(0);
                lineSegItem.setDistanceBaseLineToLineVerticalPosition(850);
                lineSegItem.setLineSpace(100);
                lineSegItem.setSegmentWidth(width);
                lineSegItem.setTextStartPositon(i);
                lineSegItem.getTag().setFirstSegmentAtLine(true);
                lineSegItem.getTag().setLastSegmentAtLine(true);
            }
        }

    }
```

thank you for you answer.

**Comment by zuoliang0** [comment]
if you receive any donate, i wish do it.
such as digital cash: eth or bitcoin ete.
