### ISSUE TITLE
안녕하세요. 라이브러리 관련되어 질문이 있습니다.

### ISSUE THREAD

**Issue by kwonhyun** [neolord0/hwplib#260]
hwp를 사용하는 라이브러리와 hwpx를 사용하는 라이브러리가 있는데 이를 같이 사용할 수 있는 건가요?
즉,  hwpx를 사용하면서 hwp라이브러리에 있는 api들을 사용할 수 있는지 궁금합니다.
일단, hwpx github에는 예제가 없고 소스도 hwpx에 관련된 것들만 있는 것 같아서 의문점이 들어 여쭤봅니다~^^

**Comment by neolord0** [comment]
안녕하세요.
hwplib 와 hwpxlib는 완전히 독립적인 라이브러리 입니다.
hwp와 hwpx는 기술적으로는 완전히 다른 포맷이며 이를 위한 라이브러리 또한 그렇습니다.
hwplib에 포함된 기능 중에 문단 추가하기(ParagraphAdder)를 제외한 모든 기능이 hwpxlib에 있습니다.
hwpxlib에는 sample이 없는 대신에.. test한 소스가  있어서 그 부분을 참고하시면 사용법을 익히는 데 도움이 될 거 같습니다.

**Comment by kwonhyun** [comment]
네 감사합니다~
