### ISSUE TITLE
[질문]Picture의 binItemId로 binary data구하기

### ISSUE THREAD

**Issue by nahooni0511** [neolord0/hwplib#261]
텍스트와 사진이 포함된 hwp파일을 html태그로 변환하려고 합니다.

ControlPicture(GsoControl) 객체의 pictureInfo.binItemID가 1,2,3,4,, 이렇게 증가하는데 이 값이
hwpFile.getBinData().getEmbeddedBinaryDataList() 배열의 몇번째 요소인지를 나타내는 값이라고 생각해도 되는걸까요?

```java
byte[] imageData = hwpFile.getBinData().getEmbeddedBinaryDataList().get([ controlPicture.pictureInfo.binItemId - 1 ]).data
```

이게 맞을까요?
EmbeddedBinaryData 객체에 name만 있고 binItemId가 없는것 같아서요.

좋은 소스로 기여해주셔서 감사합니다.

**Comment by neolord0** [comment]
안녕하세요.
회사 정책상 사용법에 대한 질문은 무상으로 할 수 없음을 양해 부탁드립니다.
깃허브 사이트에 wiki에 관련된 내용이 있으니 참고하세요.
