### ISSUE TITLE
표 데이터 추출 관련해서 문의 드립니다.

### ISSUE THREAD

**Issue by deokh-Lee** [neolord0/hwplib#262]
안녕하세요. 아래한글 문서 라이브러리를 사용하던 중에, 표 데이터에 대한 추출관련해서 질문을 드립니다.

문서에서 표가 있고, 한 셀안에 또 다른 표가 있을 경우, Inner Table에 대한 Text 추출은 어떻게 해야 할까요?

 hwp 문서, hwpx 문서 모두 inner 표에 대한 Text 추출은 안되는 듯 합니다.

혹시, 방법이 있을까요?

**Comment by neolord0** [comment]
안녕하세요.
한글 파일 내부에 text를 추출하려면 
kr.dogfoot.hwplib.sample.Extracting_Text
샘플을 참조하세요..
셀안에 있는 컨트롤도 추출됩니다.
