### ISSUE TITLE
안녕하세요. 텍스트 추출관련 문의드립니다.

### ISSUE THREAD

**Issue by giho-choi** [neolord0/hwplib#263]
샘플을 통해 텍스트를 추출하면, 맨 윗 줄? 아니면 3번째 줄? 랜덤하게 한 줄이 사라져서 나오는 현상이 있습니다. 

그리고 혹시 특수문자 같은 경우는 추출할 수 없나요??

**Comment by neolord0** [comment]
안녕하세요.
글 만으로는 정확히 알 수 없습니다.
hwp 파일을 올려주세요.

**Comment by giho-choi** [comment]
[test.zip](https://github.com/user-attachments/files/16606511/test.zip)

테스트로 작성한 한글 파일입니다.
샘플로 작성해주신 텍스트 추출 샘플 코드를 활용하여 추출 시,

- 출력 - 
안녕하세요
한글 라이브러리 테스트입니다.

으로 두 줄만 출력됩니다. 혹시 추출 옵션 3가지 모두 다 똑같은 현상이 발생합니다.

**Comment by neolord0** [comment]
안녕하세요..
제가 실수한 거 같습니다.
수정해서 올렸으니. 다시 받아서 테스트 해보세요.

**Comment by giho-choi** [comment]
감사합니다. 수정된 것 확인하였습니다.
훌륭한 패키지를 잘 사용하고 있는데, 혹시... 테이블 내에 텍스트를 변경할 수 있는 예제가 있을까요?

**Comment by giho-choi** [comment]
앗.. 하다보니까 됬네요! 감사합니다 ^_^
