### ISSUE TITLE
안녕하세요 hwp파일 변환 시 오류 확인부탁드립니다.

### ISSUE THREAD

**Issue by HYOBINKIM1** [neolord0/hwplib#264]
java.util.concurrent.ExecutionException: kr.dogfoot.hwplib.org.apache.poi.poifs.filesystem.NotOLE2FileException: Invalid header signature; read 0x6C6D783F3CBFBBEF, expected 0xE11AB1A1E011CFD0 - Your file appears not to be a valid OLE2 document

hwp파일 작업 시 해당 오류가 나타나는데 해당 문서에서 다른이름으로 저장 시 에 정상적으로 동작하고있습니다.
해당 문제가 어떤것일까요?
[확인자료.zip](https://github.com/user-attachments/files/16667916/default.zip)
[확인자료.zip](https://github.com/user-attachments/files/16667918/default.zip)

**Comment by neolord0** [comment]
안녕하세요..
보내주신 파일들은 hwpxml 파일 입니다. 
이 형식의 파일은 hwplib로 열 수 없습니다.

**Comment by HYOBINKIM1** [comment]
hwpxml파일이라는게 어떤건지 잘모르겠네요.. 한글자체에서 hwpxml 파일을 hwp로 변경가능하나요?

**Comment by neolord0** [comment]
간단히 말해서.. 한글 파일의 내용을 xml 형태로 저장한 파일입니다.
위에 에러 난 파일을 텍스트 에디터로 열면 xml이 보입니다.
자세한 정보는 한컴 사이트를 참조하세요.

https://www.hancom.com/etc/hwpDownload.do
