### ISSUE TITLE
셀병합된 정보를 가지고 올수 있을까요?

### ISSUE THREAD

**Issue by deokh-Lee** [neolord0/hwplib#266]
안녕하세요. 라이브러리를 활용하여 잘 사용하고 있습니다. 항상 감사함을 느낍니다.

Text를 추출할때 병합된 셀의 정보를 알아올수 있을까요?

![image](https://github.com/user-attachments/assets/b6ddbbf3-6aea-4531-8ec3-135e62e3605a)

이와 같은 표가 있다고 할때... 

첫번재 열은 두행 혹은 세개의 행이 병합된 셀입니다.

이걸. 각 셀별로 추출된 Text를 찍어보면, 아래와 같이  출력됩니다.

<표>
|[0,0]설비구분|[0,1]접지장소|[0,2]접지선 굵기(mm²)|
|[1,0]맨홀전력구관로|[1,1]맨홀, 전력구, 교량첨가|[1,2]95이상|
|[2,0]배수, 환기, 조명설비 분전반|[2,1]35이상|
|[3,0]통신용 원방접지|[3,1]25이상|
|[4,0]케이블|[4,1]접속부 및 접속부 가대|[4,2]95이상|
|[5,0]경보설비|[5,1]단자함, 발수신기 외함|[5,2]35이상|
|[6,0]통신관 및 통신케이블 차폐층|[6,1]25이상|
|[7,0]방식설비|[7,1]외부 전원방식의 외함|[7,2]35이상|
|[8,0]유전양극 방식|[8,1]95이상|
|[9,0]내뢰설비|[9,1]공통접지, 병행지선|[9,2]95이상|
|[10,0]방식층 보호장치(C.C.P.U)|[10,1]35이상|
|[11,0]피뢰기|[11,1]120~240|
|[12,0]피뢰침|[12,1]개별검토|
</표>

여기서 의문이 드는건, "배수, 환기, 조명설비 분전반" 이라는 문구는 표에서 보면, [2,1]  이 되어야 할거 같은데, 찍힌걸 보면, [2.0] 에서 출력이 되었습니다.

표를 순회하면서 텍스트를 찍을때 표의 Position 을 잃어 버리게 되는지요??
정확하에 표의 셀의 위치를 출력하고 싶습니다.
어떻게 해야 하나요?? 

셀 병합시에는 각 셀의 위치에서  병합이 되는것으로 보이는데요. 텍스트를 가져올때는 그렇게 셀 좌표를 가져오지 못하는 듯 하여 문의 드립니다.

**Comment by neolord0** [comment]
안녕하세요.

앞에 대문에서 말씀드렸듯이 무료 사용자에게는 사용법에 대한 질문은 받지 않습니다. 
 
감사합니다.
