### ISSUE TITLE
단순 줄글 hwp 파일 작성 문의

### ISSUE THREAD

**Issue by academey** [neolord0/hwplib#267]
안녕하세요 라이브러리 너무 잘 사용하고 있습니다. 큰 작업 해주셔서 너무 감사하다는 말씀 드리고 싶습니다

다름이 아니라 해당 라이브러리를 사용해 hwp 파일에 여러 줄의 텍스트를 작성하려고 하는데, 아래와 같이 코드를 작성하면 다음과 같은 결과가 반환이 됩니다.

텍스트 양이 많을 경우 한 줄에 텍스트를 계속 작성해서 문제가 생기는 것 같은데, 이런 경우는 어떻게 코드를 작성해야 할까요?
Sample 코드들을 봐도 어떤 걸 사용해야 할지 모르겠어서 문의드립니다

감사합니다

 ```kotlin
        val hwpFile = BlankFileMaker.make()
        val s = hwpFile.bodyText.sectionList[0]
        val firstParagraph = s.getParagraph(0)
        firstParagraph.text.addString(fileContent)

        HWPWriter.toFile(hwpFile, fileName)
```

<img width="891" alt="image" src="https://github.com/user-attachments/assets/4cc825ce-9660-4a75-86a6-f31821481459">

**Comment by neolord0** [comment]
안녕하세요.

문자열을 추가한 문단 개체(Paragraph).deleteLineSeg() 함수를 실행 시켜면 해결됩니다. 

HWP 문단을 그릴 때 속도를 높이기 등의 목적으로 미리 라인을 잘라낸 정보를 가지고 있는 거 같습니다.
이  정보가 있으면 이 정보에 의해 그려지는 거 같습니다. 

아울려, 이 라이브러리는 상용으로 판매중이며, 무료 사용자에게는 사용법에 대한 질문은 회사규정에 의해 받지 않습니다.

감사합니다.
