### ISSUE TITLE
AutoNumber 로 생성된 텍스트는 어디에 저장이 되어 있을까요?

### ISSUE THREAD

**Issue by MrHa-Developer** [neolord0/hwplib#268]
안녕하세요.
만들어주신 라이브러리를 너무 유용하게 잘 사용하고 있어서 감사의 말씀부터 전합니다.
저는 hwplib를 이용해서 HWP에서 텍스트를 추출하는 작업을 하고 있습니다.
AutoNumber 기능으로 생성된 텍스트 (예를 들어 아래와 같습니다) 에서
자동생성된 "1.", "2.", "3." 이런 텍스트는 어디에 저장이 되어있는지 궁금해서 글 남겨봅니다.

 1. 이것은 1번줄입니다
 2. 이것은 2번줄입니다
 3. 이것은 3번줄입니다

**Comment by neolord0** [comment]
안녕하세요.

문단 번호 등은.. 저장되는게 아니라.. 한글 프로그램에 의해 문단을 출력할 때 만들어 집니다.

**Comment by MrHa-Developer** [comment]
> 안녕하세요.
> 
> 문단 번호 등은.. 저장되는게 아니라.. 한글 프로그램에 의해 문단을 출력할 때 만들어 집니다.

안녕하세요. 답변 감사합니다.
한글프로그램이 문단을 출력할때 만들어 내려면, 이것이 "자동으로 번호가 생성된 것이다" 라는 내용(플래그)과 그 번호가 (가.나.다와 같은 것이 아니고) 1,2,3 숫자로 되어있다. 라는 정보를 어디다가 보관해놨을텐데 그것을 찾지를 못하겠습니다.

hwplib 자체에서 제공하는 텍스트추출함수에서는 1,2,3을 추출하던데,
제가 직접 구현해서 추춣하려니 잘 되지 않아서 이슈글 남겼습니다.

감사합니다.

**Comment by neolord0** [comment]
회사의 방침에 따라, 버그나 간단한 질문이외에는 상용 라이센스 사용자에게만 기술지원을 하고 있습니다.

**Comment by MrHa-Developer** [comment]
p{margin-top:0;margin-bottom:0}
    


    안녕하세요.
저는 구글 검색해서 github 통해서 hwplib를 처음 접촉했기 때문에 회사에 소속된 제품인지 몰랐습니다.
메일 보내주신데로 상용라이센스를 구매할 경우 비용, 라이센스 활용기간, 기술지원 방식 등을 보내주시면 검토후 라이센스 구매 추진해보겠습니다.
Daum 메일앱에서 보냈습니다.
 

--------- 원본 메일 ---------
보낸사람:"박성균(Park.sung.kyun)" ***@***.***>
받는사람:neolord0/hwplib ***@***.***>
참조:MrHa-Developer ***@***.***>,Author ***@***.***>
날짜:Wed Oct 02 08:46:19 GMT+09:00 2024
제목:Re: [neolord0/hwplib] AutoNumber 로 생성된 텍스트는 어디에 저장이 되어 있을까요? (Issue #268)


회사의 방침에 따라, 버그나 간단한 질문이외에는 상용 라이센스 사용자에게만 기술지원을 하고 있습니다.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/neolord0/hwplib/issues/268#issuecomment-2387274290",
"url": "https://github.com/neolord0/hwplib/issues/268#issuecomment-2387274290",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by neolord0** [comment]
안녕하세요. 한컴이노스트림 박성균입니다.

담당자와 협의를 하느라 답변이 늦었습니다.
저희는 hwplib 라이브러리를 기반으로 제작된 상용제품인 한글로젠를 영업 파트너인 라움소프트를 통해 판매하고 있습니다.
한글로젠을 구입하시면 hwplib라이브러리에 대한 기술지원을 받으실 수 있습니다.
기술지원은 질문/답변, 샘플작성 등의 서비스를 포함합니다.

가격이나 라이센스 비용 등은 라움소프트 최영재 영업대표를 통해 연락을 하시면 됩니다.
영업대표 : 라움소프트 최영재 팀장 
                cyj@raumsoft.co.kr
                010-5094-0112

감사합니다.
