### ISSUE TITLE
문단 복사관련

### ISSUE THREAD

**Issue by accforaus** [neolord0/hwplib#27]
현재 문단을 복사하여 새로운 파일로 옮기려고 하는데 현재는 옮기고자 하는 문단을 ArrayList에 저장하고 새로운 파일을 열어 저장을 해보았는데 파일이 손상되었다는 오류가 발생하네요..
혹시 문단을 그대로 카피하려면 paragraph객체에 옮기고자하는 모든 정보들을 카피해 주어야 하나요? 
헤더도 그대로 설정해주고 텍스트나 컨트롤도 대입이 아닌 하나하나 생성후 원본의 정보를 넣어주어야 하나요?

<pre><code>ArrayList<Paragraph> paragraphs = getParagraphs(2, 3);  // 이런식으로 가져오고나서
Section s = hwp.getBodyText().getSectionList().get(0);
Paragraph p =  s.addNewParagrsph();
p.createText();
p.getText().addString("Hello world!");
HWPWriter.toFile(hwp, 'somewhere'); // 이렇게 하면 저장은 됩니다. 하지만 한글 파일을 열면 손상된 파일이라고 나오네요..</code></pre>

혹시나 해서 setHeader, setControl, setText등의 메소드를 만들어 일일이 하나하나 대입해보아도.. 손상된 파일이라고만  뜹니다. 제 생각엔 docInfo나 fileHeader에서 설정을 해주어야 겠는데, 잘 모르겠어서 질문드립니다. 요점은, 자바상에서 복사, 붙혀넣기를 하려면 어떻게 해야하는가에 입니다.

**Comment by neolord0** [comment]
hwp 파일에서 문단을 복사하려면, Paragraph내의 모든 객체를 복사해 줘야 하고, 또한 문단과 연결된 DocInfo 내에 문서내부에서 사용하는 공통 객체(예, 글자모양, 문단 모양 등)도 옴기실 파일에 이동하고 새로 만든 문단에 연결해 줘서 합니다.  복사한다고 생각하기엔 좀 난해한 부분이 있는데요, 차라리 한 쪽에서 내용을 읽어서, 다른 쪽에 다시 만든다고 생각하시고 프로그래밍하는게 좀 더 이해하는데 편할 듯 합니다. 
문단 만드는 부분은 TestMakingCharShape.java을 참고하세요. 이 샘플은 문단에 필요한 글자모양 객체을 설정하는 부분인데요. 이런 방식으로 문단에 필요한 문단모양 객체 등을 DocInfo에 추가헤서 문단과 연결해줘야 합니다.

**Comment by accforaus** [comment]
네 그래서 새로운 문단을 생성하고, 기존문단에 해당하는 모든 Header, Text, Control, LineSeg등을 대입해주는 함수식을 만들어 주었는데, 손상된 파일이라고 오류를 뿜길래 DocInfo에 추가 해주어야 하는것이 무엇인가요..?

**Comment by neolord0** [comment]
DocInfo 안에는 바이너리 데이터(BinData), 언어별 폰트이름(FaceName), 테투리/배경(BorderFill), 글자모양(CharShape), 탭 정의(TabDef), 문단 번호(Numbering), 글머리표(Bullet), 문단모양 정보(ParaShape)에 대한 정보를 가지고 있습니다. 문단은 기본적으로, 문단 모양,  글지 모양을 연결해서 사용하고, 문단 모양은 탭 정의, 문단 번호, 글머리표 등을 연결해서 사용하고 있습니다. 또한 글자 모양도 폰트이름을 연결해서 사용하고 있습니다. 또한 문단에 배경이 설정되어 있다면, 테투리/배경 객체를,  배경에 이미지로 설정되어 있다면  바이너리 데이터를 각각 연결되어 있습니다. 문단 안에 컨트롤들도 이와 같이 DocInfo 안에 객체들과 연결되어 있고요.  거의 모든 DocInfo 안에 객체를 옴겨야 할 거 같습니다. 

한글은 문단이 컨트롤들을 가지고 있는 구조라서, 컨트롤까지 복사하시려면, 컨트롤를 생성해서 새로운 문단에 넣고, 컨트롤의 속성과 하위 객체를 설정한 후, 컨트롤에 연결된 DocInfo 객체를 문단과 같은 방법으로 처리해야 합니다. 

이 부분은 굉장히 복잡할 수 있고, 한글 파일에 전체적은 구조를 파악해야 구현할 수 있을 거 같습니다. 
한컴에서 제공하는 스팩 문서를 보시고, 문서의 구조를 파악한 후, 작업을 해야 할 듯 합니다.

**Comment by accforaus** [comment]
새 한글파일 만든후에, 문단을 전부 복사하려면

<pre><code>
HWPFile writeHwp = HWPReader.fromFile("somewhere");
HWPFile readHwp = HWPReader.fromFile("somewhere");
ArrayList<Paragraph> = getParagraphList("readHwp") // 구현한 getParagraphMethod
copy(writeHwp, readHwp); // 구현한 copy
modifyDocInfo(writeHwp, readHwp); // DocInfo를 수정하는 메소드
HWPFile.toFile(writeHwp, "somewhere"); //저장
</code></pre>

위의 코드처럼 해주어야 하는 건가요? HWPFile.toFile을 보면 Autoset이라는 메소드가 있던데 이 HWPFile에서 처리하는 로직과는 다른 DocInfo를 처리해주어야 하는건가요?

**Comment by accforaus** [comment]
[HWP.zip](https://github.com/neolord0/hwplib/files/2221971/HWP.zip)

제가 지금 짜놓은 코드를 올려두는게 이해가 쉬울거 같아 코드를 드립니다..

<pre><code>

EChar.java // paratext안에 있는 문자를 분석하는 클래스입니다.
EControl.java // 콘트롤을 분석후 추출하는 클래스입니다.
EParagraph.java // 문단을 추출하는 클래스입니다.
EParaType.java // 이건 신경안쓰셔도 될거 같아요.
HWPExtractor.java // 한글파일을 추출하는 클래스입니다.

HWPFileUtils.java // Question 객체를 생성하기위한 유틸 클래스입니다.
HWPHandler.java // 문단복사를 위한 문단 복사 클래스 입니다. (헤더, 컨트롤, 텍스트.. 등등)
HWPQuestion // HWP파일을 프로그래밍하기 쉽게 해주는 클래스입니다.
</pre></code>

한글 문서파일 구조 다운받아 출력후 확인하면서 코딩하고 있습니다. 하지만, 문단까진 일일이 복사가 가능해도, DocInfo에 무엇을 추가해야 되는지 모르겠네요..
번거로우실텐데 감사합니다.

**Comment by neolord0** [comment]
요즘 회사일이 좀 바뻐서 시간이 좀 걸리겠지만, 보내주신 코드는 살펴보겠습니다.

**Comment by accforaus** [comment]
네 감사합니다 :) 천천히 봐주셔도 됩니다.

혹시 Paragraph Header에 있는 ParaShapeId가 DocInfo안에 있는 ParaShapeList의 인덱스 번호인가요?

연결해주는 코드를 작성해 주고 있는데, ParaShape만 연결해주면 될까요??

**Comment by neolord0** [comment]
네 Paragraph Header 안에 있는 ParShapeID가 DocInfo안에 ParaShapeList의 인덱스 번호, 맞습니다.
문단에 사용한 CharShape도 비슷한 작업을 해주셔야 합니다. ParaShape 내부나 CharShape 내부에도 DocInfo 안에 있는 객체를 사용한 부분이 있습니다. 이 부분도 같은 작업을 해주서야 합니다.

**Comment by accforaus** [comment]
네! 답변 감사합니다.

현재 Facename, CharShape, ParaShape, Style이 서로 연결되어 있어서 전부다 하나하나 연결해주는 작업을 하고 있습니다.

아 혹시 BinData들도 전부 연결해 주어야 되나요? 

위의 코드는 Paragraph만 복사하는 거 밖에 없어서, 전부 연결하는 코드 구현하고 다시 업로드 드리겠습니다.

**Comment by neolord0** [comment]
BinData의 목적이 대부분 이미지 파일을 연결하는 건데요.. 문단에 포함된 컨트롤에서 이미지를 사용 했다면 DocInfo 안에 BinData와  BinData에 연결된 실제 바이너리를 HwpFile.BinData에 복사해 줘야 합니다.

**Comment by accforaus** [comment]
네 답변 감사합니다. 

하나 하나 확인하면서, 참조된것까지 신경써야해서, 복잡하긴 하네요

계속 구현해보고 질문 드리겠습니다.

**Comment by accforaus** [comment]
안녕하세요. 오랜만에 다시 연락드립니다.

모든 문단에 관련된 객체들을 연결해주는 코드를 작성하고, 테스트 하는중에 

'파일을 읽거나 저장하는데 오류가 있습니다.' 라는 오류가 발생하는데, 혹시 이 오류는 어느 부분에서 나오는 것인지 아시면 알려주실 수 있나요?

'손상된 파일입니다' 라는 오류는 IDMappings를 업데이트 하는 로직을 구현하니 해결 되었는데, 새로운 문제가 발생하네요. 감사합니다. 

그리고 혹시 DocInfo의 BinData에서 Ref하는 ID가 BinData 리스트의 인덱스번호 + 1 인가요? 0부터 시작이 아니라 1부터 시작이길래 + 1 해서 인덱싱해주고 있는데, 맞는지 확신이 안서서 여쭤봅니다.

감사합니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    네, 안녕하세요. 오랫만이네요.

한글 프로그램은 파일을 읽다가 예상했던 형태가 아니면 무조건 "손상된 파일입니다" 오류가 발생됩니다.
이 오류에서 어떤 부분이 잘 못 되었는지는 알 수가 없습니다.

DocInfo의 BinData에서 Ref하는 ID가 BinData 리스트는 인텍스 + 1이고, 1번부터 시작됩니다. 

제가 지난주에 잠깐 해볼려고 했는데, 내용이 방대해서 다 일단 문단안에 컨트롤을 뺀 글자만 복사하는 기능을 
추가해보려고 합니다. 되는데로 올릴 생각입니다. 이 부분을 참조하시면 대부분의 문제가 해결되리라 생각됩니다.

﻿
--------- 원본 메일 ---------

    
        보낸사람: accforaus <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 18.08.03 14:13 GMT +0900
        제목: Re: [neolord0/hwplib] 문단 복사관련 (#27)
        
        
    
    
        안녕하세요. 오랜만에 다시 연락드립니다.
모든 문단에 관련된 객체들을 연결해주는 코드를 작성하고, 테스트 하는중에
'파일을 읽거나 저장하는데 오류가 있습니다.' 라는 오류가 발생하는데, 혹시 이 오류는 어느 부분에서 나오는 것인지 아시면 알려주실 수 있나요?
'손상된 파일입니다' 라는 오류는 IDMappings를 업데이트 하는 로직을 구현하니 해결 되었는데, 새로운 문제가 발생하네요. 감사합니다.
그리고 혹시 DocInfo의 BinData에서 Ref하는 ID가 BinData 리스트의 인덱스번호 + 1 인가요? 0부터 시작이 아니라 1부터 시작이길래 + 1 해서 인덱싱해주고 있는데, 맞는지 확신이 안서서 여쭤봅니다.
감사합니다.

**Comment by accforaus** [comment]
답변 감사합니다.

현재 DocInfo내의 모든 객체들을 연결해주고 테스트 해주고 있는데 (BinData)도 포함해서요~

Outline, 개요는 어디서 참조하는지 찾아보고 있는데 컨트롤에 있는 Outline을 참조하는 건가요?

또한 각 개체들의 Instance ID는 그 객체의 고유한 ID일 뿐인가요? 참조하는 값은 리스트내의 인덱스 값인가요? 감사합니다.

https://github.com/accforaus/hwplibv2 제가 현재 구현하고 있는 복사관련 기능 추가된 저장소 입니다.. 한번 코드를 봐주시고, 조언부탁드립니다.

**Comment by accforaus** [comment]
방금 단순한 텍스트 문자 복사만 테스트 마쳤는데 잘 복사가 되는걸로 확인 되었습니다.

이젠.. 컨트롤하고 BinData만 옴겨지면 되는데, 일일히 하나하나 확인하면서 시도해 보아야 겠네요..

그런데, 다단 나누기는 복사본을 확인하면 다단이 풀리는데, 이것은 어디서 건들여 주어야 하나요?

**Comment by neolord0** [comment]
Instance ID는 그 객체의 고유한 ID입니다.

다단 부분은 저도 잘은 몰라요. 
아마도 ControlColumnDefine가 각 다단 갯수만큼 들어가지 않을까.. 하는 생각이 듭니다.
다단 정의한 첫 문단(Paragraph)에 ControlList에서  ControlColumnDefine 를 복사해야 할 듯 합니다.

저도 같은 기능을 구현하려고 작업중인데요. 
작업량이 엄청나고, 회사일이 있어서 하루하루 미루고 있었네요. --;
올리신 코드는 보고 참고해서..  작업해서 올리겠습니다. 
^^;

**Comment by neolord0** [comment]
다른 파일에 있는 문단 복사하는 기능을 추가했습니다.   
받아서 테스트 해 보세요.

**Comment by accforaus** [comment]
이제야 확인했습니다.

BorderFill Index도 BinData처럼 +1해서 인덱싱 하더군요..

다단은 Column Define 의 다단 개수를 늘려도 변함이 없어서 일일히 확인 해서 해봐야 될거 같습니다.

테스트 중이긴 한데, 왠만한 파일들은 전부 복사가 잘 되는것 확인 햇구요..

BinData와 다단 나누기좀 삽질좀 해봐야 겠습니다.

감사합니다!
