### ISSUE TITLE
안녕하세요 이미지 관련하여 질문이 있습니다.

### ISSUE THREAD

**Issue by codky** [neolord0/hwplib#272]
안녕하세요. 

먼저 이런 라이브러리를 제공해주셔서 감사하다는 말씀 드리고 싶습니다!

여쭤보고 점이 있어 이슈를 등록하게 되었습니다.

한글파일을 읽을 때 텍스트, 테이블, 첨부된 이미지 파일(bmp,jpg,png)이 있다고 할때,

텍스트와 테이블은 순서대로 읽는데에는 성공했지만 
사이사이에 이미지 파일이 있는 경우에는 그 이미지가 있는 위치를 찾거나 표시하는 부분에서 계속 해메고 있습니다.

아래의 코드를 이용하여
 텍스트와 테이블들을 콘솔로 출력해보았는데요.
hwpFile.getBodyText().getSectionList() {
...
...
section.getParagraphs()
 if (paragraph.getControlList() != null) {
                            for (Control control : paragraph.getControlList()) {
                                if (control.getType() == ControlType.Table && control instanceof ControlTable) {
                                    ControlTable table = (ControlTable) control;
                                    for (Row row : table.getRowList()) {
                                        for (Cell cell : row.getCellList()) {
..
..
..

이미지의 경우에는 아래처럼 추출해내는 것도 찾아보았습니다!
BinData binData = hwpFile.getBinData();
 ArrayList<EmbeddedBinaryData> list = binData.getEmbeddedBinaryDataList();
list.get(0).getData();

하지만 텍스트, 테이블, 이미지파일을 순서대로 콘솔에 표시하려면 어떻게 해야될지 모르겠습니다.
binID 같은 것을 hwpFile.getBodyText() 부분에서 얻을 수 있을까 싶어서 찾고 있는데 잘 안나오네요...

도움주시면 너무 감사드리겠습니다.

**Comment by neolord0** [comment]
안녕하세요..
앞 페이지에서 말씀드렸듯이..  기술적인 질문은 유료 서비스에 해당됩니다. 

다만, 힌트를 드리자면,  문서에 나온 이미지 순서대로 이미지를 나열하고 싶으시면...
hwpFile.getBody() 부분의 구조를 탐색하여 이미지가 들어가는 부분에 이미지 링크정보를 가져와서.. 찾아가는게 좋습니다.
물론, 이 부분의 구조가 문서가 출력되는 순서랑 정확히는 맞지 않습니만.. 대략적으로는 일치합니다.     
님이 찾아보신.. hwpFile.getBinData()에 순서는 문서의 순서가 아니라 생성순서라고 보는 게 더 정확합니다.
wiki page에 간단하게 설명이 있으니 참조하세요.

**Comment by codky** [comment]
감사합니다.
