### ISSUE TITLE
안녕하세요. 한글 파일 본문 내용을 가져와서 수정 후 저장하는데 문제가 있습니다.. 도움 부탁드려도 될까요?ㅠㅠ

### ISSUE THREAD

**Issue by kimjinho16** [neolord0/hwplib#274]
안녕하세요. 

hwp 파일에서 본문 내용을 추출하여 문자열을 치환하고 다시 hwp 파일로 저장하고 싶은데요..
(협정서에 기관명, 계약 기간, 금액, 주소 등을 기관별로 치환하여 저장이 기능이 필요합니다.)

첨부한 스샷처럼 손상된 스크립트가 포함되어 있습니다라는 alert 창이 뜹니다. 

소스 코드는 아래와 같습니다.

		HWPFile hwpFile = null;
		String hwpText = null;
		String fileNm = "sample.hwp";

		try { 

			hwpFile = HWPReader.fromFile("D:"+File.separator+ fileNm); 
			hwpText=TextExtractor.extract(hwpFile,TextExtractMethod.InsertControlTextBetweenParagraphText).replace("학생의", "테스트의");
					
		} catch (Exception e) { // TODO Auto-generated catch block e.printStackTrace();
			File file = new File("D:"+File.separator+"sample"+File.separator+ fileNm);
			logger.debug("err",e);
			if (file.exists() && file.canRead()) {
				System.out.println("file check ok");
			} else {
				System.out.println("exists=" + file.exists() +"./"+ file.canRead());
			}
		}
		

		try {
			HWPFile hwpFile2 = BlankFileMaker.make( );
			Section s = hwpFile2.getBodyText( ).getSectionList( ).get(0);
			Paragraph firstParagraph = s.getParagraph(0);
			firstParagraph.getText( ).addString(hwpText);
			HWPWriter.toFile(hwpFile2, "d:/hwpFile4.hwp" );
		} catch( Exception e ) {

		}

1. 손상된 스크립트가 포함되어 있습니다. alert 창이 안 뜨게 저장이 가능한가요? 
2. String 객체에 담아 치환 후 저장하는 방법 말고 한글의 찾아 바꾸기와 같은 메소드가 있는지 
   알려주시면 감사하겠습니다.

![스크린샷 2024-12-16 091918](https://github.com/user-attachments/assets/fbba09c4-e65c-462e-b5cc-588a683fddbd)

**Comment by neolord0** [comment]
안녕하세요..

1. 혹시 메이븐 레포지토리에서 다운 받았다면, 최신 버전인지 확인 해 주세요.  전에 이 문제를 수정한 기억이 있습니다.
   최신 버전이나 github 소스를 받아서 테스트 해보세요. 그래도 문제가 있으시면, 테스트한 HWP 파일을 올려주세요.

2. 보통, 이런 경우에는 누름틀 필드를 사용합니다. 변경될 부분에 누름틀 필드를 만들어 놓고, HWPlib에 관련 함수를 호출하면 됩니다.

**Comment by kimjinho16** [comment]
메이븐 최신 버전으로 사용해도 본문 내용을 수정 후 저장하면 

스크립트 오류가 발생하여 누름틀 필드를 사용하여 구현하였습니다.

감사합니다!
