### ISSUE TITLE
글머리 조회 시 개수가 이상하여 문의 드립니다.

### ISSUE THREAD

**Issue by unhas01** [neolord0/hwplib#276]
[한글_test.zip](https://github.com/user-attachments/files/18161261/_test.zip)

첨부한 파일에는 글머리가 총 3개가 있음에도, hwpFile.getDocInfo().getBulletList() 값에는 2개만 나오고 있습니다.

![image](https://github.com/user-attachments/assets/e711a345-6bb9-444c-a28a-f3b5c7abbdeb)

**Comment by neolord0** [comment]
안녕하세요..

저도 이 부분은 정확한 매커니즘은 모릅니다만,
예제를 보니, 문단 헤더에 숫자인 경우가 있던데, 이 경우에는 Bullet에 추가되지 않습니다.
Bullet은 글머리표만 저장됩니다.

**Comment by unhas01** [comment]
안녕하세요. 
아래 이미지처럼 숫자도 글머리 서식에 잡혀서 문의드렸던 거였습니다. 답변 감사합니다.

![image](https://github.com/user-attachments/assets/1a73c0a2-0ff9-4c4d-9d81-b241f75a2aaf)
