### ISSUE TITLE
혹시 글씨 크기 data는 알 수 없을까요?

### ISSUE THREAD

**Issue by lmalma2004** [neolord0/hwplib#3]
혹시 글씨 크기 data는 알 수 없을까요?
크기를 읽어오거나 크기를 설정하고싶은데 크기부분은 못찾겠네요 ㅠㅠ

**Comment by neolord0** [comment]
글씨 크기 같은 정보는 문단 내용(Paragraph)과 별도로 저장되어 아이디만 저장됩니다.
Paragraph에 포함된 ParaCharShape 객체에서는 글자 모양 객체의 아이디와 그 글자 모양을 적용하기 시작할 위치를 가지고 있습니다. 여기서 글자 모양 객체의 아이디를 얻어서  DocInfo의 CharShape List에서 이 아이디 번째의 CharShape를 얻어서 이 객체에서 글자 크기를 구할 수 있습니다.

**Comment by lmalma2004** [comment]
아하. 감사합니다.!!!
