### ISSUE TITLE
안녕하세요 만들어주신 오픈소스 이용 잘하고 있습니다.

### ISSUE THREAD

**Issue by pasudo123** [neolord0/hwplib#30]
우선 이렇게 유용한 오픈소스 라이브러리 만들어주셔서 감사합니다.

혹시 hwp 파일을 word 의 docx 혹은 doc 타입으로 저장할 수 있는 모듈이 따로 존재하는지 알 수 있을까요?

**Comment by neolord0** [comment]
음.. 글쎄요..
그 기능은 오픈소스 오피스나 워드프로세서 쪽을 찾아보시는 게 좋을 듯 합니다.
..

**Comment by pasudo123** [comment]
답변 감사드립니다

**Comment by pasudo123** [comment]
저 한가지 더 여쭙고 싶은데 그리기 객체 내부의 텍스트는 따로 추출할 수 있을까요? 컨트롤이 그리기 객체라는 것만 인식하고 텍스트 추출이 안되서 질문합니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    그리기 객체를 찾는 부분은 샘플 중에.. kr.dogfoot.hwplib.test.TestFindControl 를 참고하시면 될 거 같고요..

찾은 그리기 객체에서 텍스트를 추출하는 부분은 ﻿kr.dogfoot.hwplib.textextractor.ForControl.extract() 함수를 이용하시면 될 거 같습니다.

.﻿
--------- 원본 메일 ---------

    
        보낸사람: SUNG DONG PARK <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, State change <state_change@noreply.github.com>
        
        날짜: 18.08.30 10:58 GMT +0900
        제목: Re: [neolord0/hwplib] 안녕하세요 만들어주신 오픈소스 이용 잘하고 있습니다. (#30)
        
        
    
    
        저 한가지 더 여쭙고 싶은데 그리기 객체 내부의 텍스트는 따로 추출할 수 있을까요? 컨트롤이 그리기 객체라는 것만 인식하고 텍스트 추출이 안되서 질문합니다.

**Comment by pasudo123** [comment]
감사합니다 !!

**Comment by pasudo123** [comment]
저 한가지 여쭤보고 싶은게 더 생겼는데 특문으로 들어오는 문자가 깨져서 표현되는데 그러한 경우는 어떻게 올바르게 추출할 수 있을까요??

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    저도 문제는 알고 있습니다.
한글에 특수 문자 코드가 윈도우즈 특수 문자 코드랑 다릅니다.
심지어, 윈도우즈 특수 문자로 표현하지 못하는 문자도 있습니다.
일대일로 바꿔야 하는데.. 코드량에 많아서.. 못 하고 있습니다.
급하신 대로, 필요한 특수 문자만 바꿔서 사용하시길 권장합니다.


--------- 원본 메일 ---------

    
        보낸사람: SUNG DONG PARK <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, State change <state_change@noreply.github.com>
        
        날짜: 18.09.07 10:45 GMT +0900
        제목: Re: [neolord0/hwplib] 안녕하세요 만들어주신 오픈소스 이용 잘하고 있습니다. (#30)
        
        
    
    
        저 한가지 여쭤보고 싶은게 더 생겼는데 특문으로 들어오는 문자가 깨져서 표현되는데 그러한 경우는 어떻게 올바르게 추출할 수 있을까요??

**Comment by pasudo123** [comment]
안녕하세요 여러분 질문드려 죄송합니다. 라이브러리를 사용하면서 현재 문서가 텍스트에 볼드 여부를 사용했다던가 혹은 상대적인 글꼴 크기를 어느정도 했는지 알 수 있었습니다. docInfo 를 통해서 말이죠..  

저는 근데 어느 특정한 문단의 텍스트가 어느정도의 글꼴크기를 가지고 적혀있는지 알려고 하는데 가 부분이 현재 라이브러리 내에 존재하는지 여쭙습니다. 계속 찾아보았는데 안보여서 질문 올립니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    굵게(Bold), 글꼴 크기 등에 글자에 대한 정보는 DocInfo에 CharShape(글자모양) 객체에 있습니다.
이것도.. BodyText에 문단이랑 연결되어 있는데, 문단(Paragraph)에 ParaCharShape라는 객체이 있는데.
이 객체가 글자의 위치와 CharShape(글자모양)에 대한 인덱스의 쌍을 여러 개 가지고 있습니다.
문단은 이 객체를 사용하여 문단 내의 글자들의 글자모양을 변경할 수 있습니다.
--------- 원본 메일 ---------

    
        보낸사람: SUNG DONG PARK <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, State change <state_change@noreply.github.com>
        
        날짜: 18.09.17 09:58 GMT +0900
        제목: Re: [neolord0/hwplib] 안녕하세요 만들어주신 오픈소스 이용 잘하고 있습니다. (#30)
        
        
    
    
        안녕하세요 여러분 질문드려 죄송합니다. 라이브러리를 사용하면서 현재 문서가 텍스트에 볼드 여부를 사용했다던가 혹은 상대적인 글꼴 크기를 어느정도 했는지 알 수 있었습니다. docInfo 를 통해서 말이죠..
저는 근데 어느 특정한 문단의 텍스트가 어느정도의 글꼴크기를 가지고 적혀있는지 알려고 하는데 가 부분이 현재 라이브러리 내에 존재하는지 여쭙습니다. 계속 찾아보았는데 안보여서 질문 올립니다.

**Comment by pasudo123** [comment]
아하 감사합니다 찾았습니다!!
