### ISSUE TITLE
페이지 표시에 관련해서 궁금한게 있어서 남깁니다.

### ISSUE THREAD

**Issue by hope9405** [neolord0/hwplib#31]
https://github.com/neolord0/hwplib/blob/f04b23d8e5d271b3b08219cd3d2cab441096fabd/doc/kr/dogfoot/hwplib/object/docinfo/DocInfo.html#L728

오타 :  한자 긍꼴 리스트 -> 한자 글꼴 리스트

안녕하세요.
한글파일을 HTML파일로 변환하는 프로그램을 만들고 있는 학생입니다.
먼저 이렇게 좋은 모듈을 만들어 주셔서 감사합니다.

현재의 문단이나 표가 어느 페이지(쪽)에 속해 있는지 알아낼 수 있는 방법을 찾지 못해 이렇게 문의를 드립니다.

밑에는 좀더 자세한 설명을 적어 두었습니다.
-------------------------------------------------------------------------------------------------
HTML로 변환 할 시 표가 hwp파일에서 출력된 순서가 아닌 다른 순서로 출력이 되어 확인 해 본 결과,
표가 글자처럼 취급이 되어 있으면 paragraph에 저장된 순서와 일치 하지만,
글자처럼 취급이 되어 있지 않으면 저장된 순서가 일치하지 않는 다는 사실을 알게 되었습니다.

그래서 HTML로 변환 했을 때 hwp 파일에서 보이는 화면과 HTML의 화면이 일치 하게 만들기 위해서 전 처리 후 출력을 할 생각입니다. 

문단 같은 경우는
몇 번쨰 페이지인지, 그리고 그 위치(y축 값)를 알아낸 뒤,
LineSegItem의 lineVerticalPosition의 값을 이용하여 페이지 내에서의 문단의 위치를 더해서 문단의 위치를 알아내고, 

표 같은 경우는
몇 번쨰 페이지에 속한 표인지 알아내어, 그 페이지의 위치(y축 값)을 알아내어,
CtrlHeaderGso의 yOffset값을 더해서 표의 위치를 알아내려고 생각했습니다.

그리고 문단과 표에 instanceID으로 어느 페이지(쪽)에 속해 있는지 알아낼 수있을 것이라 생각했습니다.
하지만 현재의 문단이나 표가 어느 페이지(쪽)에 속해 있는지 알아낼 수 있는 방법을 찾지 못해 이렇게 문의를 드립니다.

혹시 더 좋은 방법을 알고계신다면 알려 주셨으면 합니다.

밑의 덧글이나 (hope9405@naver.com) 로 회신을 해주시길 바랍니다.
감사합니다.

**Comment by neolord0** [comment]
페이지는 파일 구조에서 알아낼 수는 없고 컨트롤이 어떤 페이지에 속하는지도 알 수 없습니다.
워드 프로세스는 문단을 중심으로 구성됩니다. 페이지는 문단을 그리는 과정에서 문단을 그릴 영역이 부족할 경우 추가됩니다.  문단을 글자들과 컨트롤들로 구성되고요.   

hope9405님이 구현 하고자 하는 기능을 구현하려면,  결국 한글 뷰어에 모든 기능을 구현해서 "글자 처럼" 출력된 컨트롤의 위치를 파악해야 합니다. 문단의 속성과 글자의 속성을 모두 지원해서 글자와 문단의 위치를 추적해야만 하는데. 이 것은 너무 시간이 많이 걸리는 일이죠.  앞에 소개문에서 고지한 내용처럼 이 라이브러리는 아직 이 기능을 지원하지 않습니다.

**Comment by neolord0** [comment]
오타 지적은 감사합니다.

**Comment by hope9405** [comment]
도움이 많이 되었습니다.
감사합니다.
