### ISSUE TITLE
문서 내에서 컨트롤(이미지 또는 수식)의 위치를 알고 싶습니다.

### ISSUE THREAD

**Issue by kunok2** [neolord0/hwplib#34]
안녕하세요. 라이브러리 정말 잘 쓰고 있습니다.
한가지 궁금한 사항이 있어 문의 드립니다.

현재 제가 작업하고 있는 내용은 한글 문서안에 컨트롤을 찾아서 어느 위치(페이지, 줄, 칸)에 존재하는지 출력하는 것입니다.
그런데 이리저리 찾아봐도 제가 찾고자 하는 정보가 없네요vv

도움 부탁드립니다.

**Comment by neolord0** [comment]
문서 내에 컨트롤의 위치를 알려면, 문서를 그려야 합니다.
한글과 같은 워드 프로세서들은 문단을 나열하는 방식으로 문서 전체를 표현합니다.
파일 내부에는 페이지나 줄, 칸에 대한 내용이 없습니다. 어떤 컨트롤의 위치를 알려면, 이 컨트롤이 이전에 문단들의 크기를 구해서 더해야 합니다.

kunok2님이 요구한 기능을 구현하려면 한글 뷰어에 준하는 프로그램을 만들어야 합니다만, 이 기능은 시간/실적에 부족으로 지원하지 못 하고 있습니다.

**Comment by kunok2** [comment]
답변 감사드립니다.^^

**Comment by kunok2** [comment]
kr.dogfoot.hwplib.object.bodytext.paragraph.lineseg.LineSegItem 클래스를 이용하여 문서 내에서 라인의 수를 구했습니다.^^
그런데 문제는 몇번째 페이지에 속하는지 인데
혹시 어떤 클래스의 값을 이용해서 어찌어찌하면 되겠다는 힌트정도 얻을 수 있을까요?
부탁드립니다.

**Comment by neolord0** [comment]
음.. 한글과 같은 워드 프로세서들은 일반적으로 용지크기에 공간에 문단들을 채워 넣다가,  채워 넣을 공간이 부족하면 그 때, 새로운 페이지를 추가하는 방식으로 처리합니다. 

현재로써는 이 라이브러리로는 불가능하고요. hwp파일을 지원하는 오픈 오피스 쪽 라이브러리나,  사이넵 같은 뷰어 기술이 있는 상용 라이브러리로 사용해야 할 거 같습니다.
