### ISSUE TITLE
셀병합 문의 드립니다.

### ISSUE THREAD

**Issue by codeless73** [neolord0/hwplib#35]
안녕하세요. 
먼저 한글 생성 라이브러리 제공에 감사드립니다~~

제공하시는 라이브러리로 개발 중 문의 사항이 있서서 도움 요청드립니다.

단순 표는 작성에는 문제가 없으나 셀을 병합시 문서 생성이 되지 않습니다.(컴파일 오류는 없고 손상된 문서가 생성됩니다.)

제가 원하는 형태는 
____    포도
과일   딸기
____     수박
채소   호박
육류  소고기
____    돼지고기
( 이 편집기 에서는 여러 빈칸이 적용되지 않아 밑줄 넣었습니다.)

이런 식인데 셀 병합을 위해 
setListHeaderForCell 을 변경 하여 

setListHeaderForCellSpan(int colIndex, int rowIndex , int colSpan , int rowSpan)
으로 병합될  개수를 입력 받게 변경 후 

....
for.....
...
if( colnum ==0 && ... 
setListHeaderForCellSpan(colnum, rownum , 0 , 3);					
setListHeaderForCell(colnum, rownum);
....

이런 식으로 호출해서 사용 해 보았으나 (병합되는 첫  row에서 실행하거나 ,마지막에 실행 하거나, 병합되는 모든 행에서 실행 등등...)

문서 생성은 정상적이나 손상된 문서라 열리지가 않습니다...

도움 부탁드립니다.
감사합니다.

**Comment by neolord0** [comment]
codeless73님의 취지를 정확히 이해하기 힘드네요...
소스와 테스트 하신 hwp 파일을 올려주시면, 보고 분석해서, 샘플을 만들어 드리겠습니다.

**Comment by codeless73** [comment]
먼저 답변 주셔서 감사합니다.
 
말씀하신 대로 소스 코드와 샘플 파일 보내드립니다.
 
도움 부탁드립니다.
 
 
 
-----Original Message-----

**Comment by codeless73** [comment]
빠른 해결에 감사드립니다.
고맙습니다~~
