### ISSUE TITLE
필드설정시 값의 맨마지막이 줄바꿈 문자일경우 에러가납니다

### ISSUE THREAD

**Issue by parkms214** [neolord0/hwplib#37]
중간에 ₩n이 있을경우는 정상으로 멀티라인으로 설정되나
마지막에 ₩n이 있을경우 StringIndexOutOfBoundsExcption 에러가 발생합니다.
저는 임시로 FieldFinder.setFieldText메소드의 맨 윗줄에
for(int i = 0; i < textList.size();  i++){
 if(textList.get(i).charAt(textList.get(i).length()-1)=='₩n')textList.set(i, textList.get(i).substring(0, textList.get(i).length()-1));
}

를 삽입해서 임시방편으로 쓰고있습니다.
다만 맨마지막이 줄바꿈문자이면 맨마지막 줄바꿈문자만 잘라내는 소스라 제가 쓰는곳은 상관없지만 근본적인 해결책은 아닌거 같습니다.

맨마지막이 줄바꿈문자이면 제대로 맨마지막에 비어있는 줄이 생성되도록 하는 방법이 있을까요?

**Comment by neolord0** [comment]
네, 확인해서 수정하겠습니다.

**Comment by neolord0** [comment]
수정하여 push 했습니다.
