### ISSUE TITLE
컨트롤 찾기에 대한 아이디어

### ISSUE THREAD

**Issue by jic5760** [neolord0/hwplib#39]
안녕하세요. 좋은 라이브러리 공개해 주셔서 정말 감사드립니다.
이 라이브러리를 이용해 개발 중 아이디어가 있어 문의드립니다.
현재 Control을 찾는 방법은 하나의 Hwp문서에서 상하관계없이 무조건 단독의 객체에서 검색하는데
같은 내용이 여러군데 있거나 하나의 특정한 Control(예를들어 Table)안에서 또다른 Control을 찾는 등 계층형으로 검색이 불가합니다.
따라서 Find/Filter등을 HwpFile이 아닌 Control자체에서 찾을 수 있게 하면 이런게 가능하지 않을까 생각해봅니다^^

**Comment by neolord0** [comment]
그렇쿤요...  
하나 찾고 나머지를 찾지 않는게..  훨씬 효율적이라고 생각했는데..
이런 경우가 있군요..  
음.. 추가로 함수를 만들어서 올리겠습니다.

**Comment by neolord0** [comment]
시간이 좀 걸렸지만 기능을 추가했습니다.
받아서 테스트 해보세요.
