### ISSUE TITLE
한글파일을 url 로 여는방법은 없나요?

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#4]
한글파일을 url 로 여는방법은 없나요?

한컴 예제에 보면 
URL에서 HWP읽기
테스트로 'http://ocwork.haansoft.com/sample/sample.hwp'
이 파일이 있던데요.
hwplib 로도 가능한지요?

**Comment by neolord0** [comment]
음..URL에서 읽는 기능이 없어서.. 
추가 했습니다.. 다시 받아서 테스트 해보세요..

**Comment by osc91** [comment]
와~
빠른 답변,빠른 해결 감사합니다.
잘 쓰겠습니다 ^^
