### ISSUE TITLE
안녕하세요 text 파일을 추출하다보니 에러가 떠서 질문드려요

### ISSUE THREAD

**Issue by LeeYunSeop** [neolord0/hwplib#43]
Shape Component must come after CtrlHeader for gso control.

이런 에러가 뜨는데 혹시 이유를 알 수 있을까요?

**Comment by neolord0** [comment]
음.. 한글 프로그램의 버전에 따라.. 파일이 약간씩 다르게 저장됩니다.
파일을 보내주시면... 테스트 해보겠습니다.

**Comment by LeeYunSeop** [comment]
회사문서라서 보내드릴수가 곤란합니다..
일단은 안에 이미지 파일이 있는 경우에 저런 에러가 뜨는것 같습니다.
그리고 List header must be located 이런 에러도 뜨는데
소스를 보니 미주 컨트롤의 문단 리스트 헤더 레코드를 읽는다고 써있는데
해당 문서에는 미주 자체가 없는데
왜 뜨는걸까요.. 테스트 파일을 드릴수가 없으니 답답하네요 ㅠㅠ

**Comment by neolord0** [comment]
한글이라는 프로그램도.. 버전이 추가될 때마다. 기능이 추가/삭제 됩니다.
이것을 저정하는 파일의 변화가 있을 수 밖에 없습니다.
한컴에서 제공한 문서는 특정 시점(버전)의  파일 구조라.. 실제 파일과는 다를 수 있습니다. 

한글 파일은 파일을 구성하는 레코드가 반복되는 구조라 에러 메시지만으로 추측하기 힘듭니다. 
하위 버전에 추가된 내용들은 문서에 없어서.. 저도 추측해서 만드는 거라.. 더욱 그렇습니다.

파일을 보내주셔야 분석이 가능합니다. --;  
사내 보안 담당자 분이랑 협의해 보세요..

**Comment by neolord0** [comment]
파일에서 보안에 걸릴 만한 내용을 삭제하고, 같은 에러가 발생하는 파일을 보내주시면.... 어떨런지. ??

**Comment by madang77** [comment]
안녕하세요. 저도 동일한 문제가 발생합니다. 해결을 해 보려고 했는데... 잘 안되내요.
neolord 님의 hanmail.net 메일로 한글 문서를 보내드립니다.

많은 노력을 한 것을 배포주셔서 감사합니다.
