### ISSUE TITLE
질문이 있습니다.

### ISSUE THREAD

**Issue by kwonhyun** [neolord0/hwplib#44]
안녕하세요.
먼저 Cell field에 관련된 사항 추가해주셔서 감사합니다.^^;
질문이 하나 있어서 글 올립니다.
현재 파일형식이 hwp인 파일만 읽어서 할 수 있는 거죠?
이 외 HWPML형식의 파일(확장자 hml)을 읽어서 할 수 있는 방법도 있는건지 궁금합니다.
만약 할 수 있다고 해도 현재 개발하신 것을 수정하는게 아니라 새로 개발해야 되는 것인지 궁금합니다.

감사합니다^^

**Comment by neolord0** [comment]
hwp 와 hwpml은 완벽히 다른 파일입니다..겹치는 부분이 거의 없어서, 새로 개발해야 합니다.
그리고, hwpml은 한글에서 사용하는 기능을 완벽히 담은 파일구조가 아닙니다. 
많은 부분이 빠진.. 미완성 파일구조 라.. 생각됩니다. 

hwpml은 xml파일이라, 편하기 생성/수정할 수 있으나, 보안이나 웹서버의 mime 타입등에서 문제가 될 수 있습니다.
요즘에는  owpml(xml파일을 zip으로 압축한) 파일이 대세입니다. 
xml파일로 하시려면 이쪽을 보시는 게 좋을듯 합니다.

**Comment by kwonhyun** [comment]
아~그렇군요~
답변 감사합니다.
많은 도움 되었습니다. 그럼 좋은 하루 되세요~^^
