### ISSUE TITLE
안녕하세요. 문의가 있어 올립니다.

### ISSUE THREAD

**Issue by tkm01b** [neolord0/hwplib#46]
좋은 라이브러리 만들어 주셔서 감사합니다.
혹시 문자열 치환이 가능할까요?
특정한 문자열을 찾아서 ㄷ른 문자열로 치환한다거나 아니면 이미지로 치환한다거나 하는게 가능할까요?
감사합니다.

**Comment by neolord0** [comment]
글자를 치환하는 방식 중에 ... 지금 라이브러리에서 제공하는 기능은 ..
한글의  누름틀 또는 필드를 사용하여.. 미리 지정한 후.. 
지정된 누름틀 이나 필드를 찾아.. 그 내용을 치환하는 방식입니다.
/test/TestSetField.java, /test/TestSetClickHereFieldText.java를 참고해 보세요..
 
이미지 부분도 치환 조건이 문제데요.. 
단순히 모든 이미지를 변경하고 싶으시면..
/test/TestChangeImage.java 를 참조하시면 될 거 같습니다.

치환할 문자열을 검색하는 방법에 대해 원하는 방식이 있으시면.. 구체적으로 애기해 주세요..
