### ISSUE TITLE
표 정보 읽어오기 예제 소스

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#5]
한글 파일 안에 있는 표를 찾아서 표의 각 셀에 있는 텍스트 정보를 얻어오고 싶습니다.
HwpCtrl.ocx 를 이용할때는 CtrlID 값을 이용해서 테이블을 찾고 MovePos 등을 사용하여 이동하면서
텍스트 정보를 얻어왔었는데요.
hwplib 를 사용해서 같은 기능을 구현해보고 싶은데 어렵네요.

혹 간단한 예제 좀 부탁드려도 될까요?
수고하세요 ^^

**Comment by neolord0** [comment]
표 객체를 찾는 건 별로 어렵지 않은데요. 
문제는 문서에 포함된 여러 개의 표 중에 원하는 표를 어떻게 찾을지가 고민입니다.
HwpCtrl을 사용하실 때는 어떻게 찾으시는지요 ??
알려주시면 필요한 기능을 추가해 보겠습니다.

**Comment by osc91** [comment]
p{margin-top:0;margin-bottom:0}
    


    HwpCtrl 를 이용해서 원하는 표 하나를 찾는 기능을 만든게 아니구요.
한글파일 안에서 control 을 찾아서 
표일경우 전체를 다확인하는겁니다.
전체 테이블의 셀들을 이동하며 텍스트를 읽어서 제가 원하는 특정단어가 있는지 찾고
있을경우 그 셀의 오늘쪽이나 하단의 셀들의 값을 찾아오는 기능을 만들﻿려고 하거든요.
이름금액장소10010,000100100100100
위와 같이 테이블이 있을때 금액 이라는 단어를 찾고 
최종적으로 ﻿10,000 값을 찾는 기능을 만들려고 합니다.

근데 hwplib 를 사용해서 control 리스트를 찾고 Type﻿ 이 table인 놈을 찾고

거기서 어떻게 진행을 해야할지 모르겠더라구요 ^^;;

제 질문이 이해가 되셨는지요?

되셨으면 예제 소스 좀 부탁드리겠습니다.
수고하세요 ^^﻿
--------- 원본 메일 ---------

    
        보낸사람: park.sung kyun <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: osc91 <osc91@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 17.08.30 20:32 GMT +0900
        제목: Re: [neolord0/hwplib] 표 정보 읽어오기 예제 소스 (#5)
        
        
    
    
        표 객체를 찾는 건 별로 어렵지 않은데요.
문제는 문서에 포함된 여러 개의 표 중에 원하는 표를 어떻게 찾을지가 고민입니다.
HwpCtrl을 사용하실 때는 어떻게 찾으시는지요 ??
알려주시면 필요한 기능을 추가해 보겠습니다.

**Comment by neolord0** [comment]
음.. 필터링 인터페이스에 조건을 java 코딩으로 입력할 수 있도록 찾기 기능을 추가하였습니다.
받아서 사용해 보세요.

**Comment by osc91** [comment]
답변 감사합니다.
예제 java 파일도 잘 봤습니다.

수고하세요 ^^
