### ISSUE TITLE
안녕하세요 질문 있습니다.

### ISSUE THREAD

**Issue by kwon1148** [neolord0/hwplib#53]
단이 있는 문서를 읽고 그대로 새로 저장했는데 단이 빠져있더군요. 단을 읽어오거나 다단 설정은 불가능한가요?? TestInsertImage예제를 보고 단을 넣어봤는데 HWPWriter로 .hwp파일로 만들면 단이 빠지네요.. 또 한가지는 해당하는 누름틀에 이미지를 넣을 수 있을까요??

**Comment by neolord0** [comment]
테스트 해 보니.. "다단" 대화상자에서 "단 너비 동일하게"를 선택했을 경우에 
위와 같은 오류가 발생하더군요..
수정하여 올렸습니다.
받아서 테스트 해보세요..

**Comment by neolord0** [comment]
누름틀 안에 이미지 넣는건 아마도  누름틀 컨트롤 안에 이미지를 추가하는 게 아니라.
누름틀 안쪽에 문단에 이미지를 넣으면 될 거 같습니다.

누름틀이 시작 컨트롤과 끝 컨트롤이 있는데.. 그 사이에 이미지를 넣으면 되지 않을까 생각됩니다.

**Comment by kwon1148** [comment]
감사합니다 덕분에 해결했습니다.
