### ISSUE TITLE
스타일 추출 및 비교 관련 문의

### ISSUE THREAD

**Issue by skruaths** [neolord0/hwplib#54]
스타일에 맞게 작성된 문서인지 확인하고싶습니다.
예를 들어.. 한글문서가 아래의 조건을 만족하는지
----------------------------------------------
구분 : 본문 내용
정렬 : 혼합
글꼴 : 신명조
글자크기 : 11pt
행간 : 160
장평 : 100
자간 : -2
들여쓰기 : 0
----------------------------------------------

라이브러리에서 위의 내용을 추출할 수 있는지 궁금합니다.

**Comment by neolord0** [comment]
한글과 같은 워드프로세서는 위에 나열된 속성이 문서 전체가 아닌, 문서의 특정 부분에 적용됩니다. 한글에서는 이 속성들을 문단모양과 글자모양으로 나누고 있으며, 문단모양에 속하는 속성들은 문단마다 설정이 가능하며, 글자모양에 속하는 속성은 글자마다 설정할 수 있습니다.

이와 같은 상황에서, skruaths 님의 요청하신 대로 문서가 특정 속성으로 작성된 문서인지 확인하려면 "문서가 하나의 속성 들로 작성되었다"는 전제하에서 첫 문단의 문단모양과 첫 글자의 글자모양 속성을 비교하거나, 아니면 문서에 모든 문단에 설정된 문단 모양과 글자에 설정된 글자모양을 다 비교해야 합니다.

위의 설명에서, 제가 스타일이라는 용어 대신 속성이라는 용어를 사용한 것은 한글의 스타일 기능과의 혼란을 피하기 위해서 입니다. 한글의 스타일 기능은 한글에서 문서내에서 사용될  문단모양/글자모양 등을 미리 설정하고 이름을 붙임으로써, 편하기하게 재사용 할 수 있게 하는 기능입니다. 이 스타일도 문단마다 설정할 수 있습니다.
이 또한, 문서가 특정 스타일이 작성된 문서인지 확인하려면, 위에  문단모양/글자모양 속성의 경우과 같이 처리해야 합니다.

위에 내용들은 이 라이브러리에서 가능한 기능입니다.
