### ISSUE TITLE
버전호환성관련문의

### ISSUE THREAD

**Issue by imjcpark** [neolord0/hwplib#57]
노고가많으십니다.
다르이 아니라 올려주신 테이블 생성 소스로 파일을 만들어 봤는데.
한컴오피스네오 버전(버전 9.6.0.2518) 에서는 열리는데
한컴오피스 2010 SE (8.5.5.1092) 에서는 시계 아이콘이 계속돌아가며 열리지 않습니다.
올려주신 test-making-table.hwp 과 hex 비교를 해보니 일부 다른부분이 있어서요.
다른환경이라면
hwplib 2019.01.28 버전이고
MAVEN poi3.16을 참조하여 쓰고 있습니다.
파일 첨부하여 문의드립니다.
[test_hwp.zip](https://github.com/neolord0/hwplib/files/3328245/test_hwp.zip)

**Comment by neolord0** [comment]
제 생각엔.. 사용하고 계신 한글 2010SE를 업데이트를 해 주시면 될 듯 합니다.
한글은 기능이 추가될 때마다 파일에 특정 레코드에 내용이 약간씩 추가되고, 한글 파일 자체에 버전도 증가합니다.
그런데, 고객들은 기존에 사용중인 한글 프로그램에서도 변경된 파일을 읽기를 원하기 때문에..
2010SE 나 오피스네오 등에 한글 프로그램의 버전과 관계 없이 최신 버전의 파일을 읽을 수 있도록
업데이트를 통해 이를 처리하고 있는 것으로 알고 있습니다.

한컴 사이트에서 업데이트 또는 패치를 받아서 테스트 해보세요.
