### ISSUE TITLE
내용에 html tag 입력 문의드립니다.

### ISSUE THREAD

**Issue by hyoseon1012** [neolord0/hwplib#58]
안녕하세요. 
좋은 라이브러리 개발해 주셔서 감사합니다.
우연히 검색하게 되어 잘 사용중에 있습니다. : )

hwp 파일에 내용을 write 하다보니, 에디터로 작성된 내용을 입력해야되는 경우가 있습니다.
에디터로 작성 된 내용에 html tag 등이 포함되어있어서, 작성할 때 변환을 해줘야되더라구요.

write 시  html tag(글자색, 밑줄 등) 처리를 위한 방법은 없을까요?

**Comment by neolord0** [comment]
html 태그를 파싱하여 필요한 테그(글자색, 밑줄)을 찾아낸 다음에.  문단 모양(ParaShape)나 글자 모양(CharShape)에 대응하는 속성을 찾아서 설정해야 합니다.
html  태그를 파싱하는 것은 기존에 있는 HTML  Parser 를 사용하면 될 거 같고요.. 문단 모양 이나 글자모양 속성을 설정하는 부분은 샘플 소스인 TestMakingCharShape 등을 참조하시면 될 거 같습나다.
다만, html 태그중에 어떤 태그를 한글의 어떤 속성으로 변환해줘야 하는지 하는 문제가 숙제로 남아 있는데, 이 문제는 시간을 투자하여 테스트를 많이 해야 하는 부분입니다. 간단한 태그 부터 차근차근 해 나가시면 될 듯 합니다.

**Comment by hyoseon1012** [comment]
네~ 답변 감사합니다.
