### ISSUE TITLE
안녕하세요. 

### ISSUE THREAD

**Issue by iocwr19** [neolord0/hwplib#59]
멋진 프로젝트를 만들어 주셔서 감사합니다.
이 프로젝트를 사용하면서 몇가지 읽기 오류나 이미지 바이너리파일에 관한 이슈가 있어서 
이렇게 글을 올립니다.
이미지 헤더 혹은 캡션 헤더 등에서 발견된 처리되지 않은 비트가 있거나 이미지 바이너리파일 목록을 읽어 BinItem으로 형성할 때 바이너리파일을 이름 순으로 읽지 않아 생기는 오류 등이 있습니다.
해당 이슈에 관해서 저도 수정하고 보완하여 이 기트프로젝트에 새로운 브런치로 포크해 참여하고 싶은데
가능할까요?
또 maven 프로젝트로 포팅해서 새로운 프로젝트를 만들어도 되는지 문의드립니다^^

**Comment by neolord0** [comment]
오픈 프로젝트에 참여하는 건.. 본인의 자유입니다. 저한테. 허락받을 필요는 없는 듯 합니다.
 
처리 안된 비트 등의 부분은   문서에 언급되지 않았고, 알지 못하는 부분입니다.   
iocwr19님이 알고 계시는 부분이 있으면.. Pull Requests 를 보내주시면 확인하고 반영하겠습니다. .

그리고,  이미지 바이너리파일 목록은 아마도, 한글에서 저장된 순서대로 읽어 오는 부분이지라..
특정 순서대로 정렬하는 게 어떤 의미인지.. 무슨 이유에서 파일 이름 순대로 정렬하려 하시는 지요 ?

maven 프로젝트로 만들어서,  Pull Requests을 보내는 건  자제해 주시길 바랍니다.
제가 회사 업무로 인해.. 시간이 많이 없어서, 전체적인 틀을 바꾸는 Pull Requests는 확인 할 수 없습니다.
정 maven 프로젝트로 프로젝트를 포팅하고 싶으시면, 별로도 포크해서 운영하시면 될 듯 합니다.

이상입니다.

**Comment by iocwr19** [comment]
한글에서 바이너리파일을 BIN0001, BIN0002, ... 로 순차 저장하지만 선생님께서 작성하신 모듈을 그대로 사용하면 저 순서가 바뀌어서 나와 오류가 발생하는 경우가 있었습니다. 그래서 이름순으로 정렬하여 사용하였습니다. 
그 외 하신 말씀은 잘 이해했습니다 감사합니다 ^^

**Comment by neolord0** [comment]
음.. 말씀해주신 부분은 확인하겠습니다.
문서 스펙 상으로는 별 상관이 없을 거라 생각되는데.. 
한글 프로그램에서 저의 예상대로 처리되지 않는 부분은 있는지도 모르겠군요..
