### ISSUE TITLE
안녕하세요. 질문이 있습니다.

### ISSUE THREAD

**Issue by KimJason8557** [neolord0/hwplib#61]
안녕하세요.

올려주신 소스 감사드리며 예제를 보며 여러가지 테스트를 해보고 있습니다.
다양한 예제가 있긴 한데 제가 필요한 기능이 잘 안되어서 여쭈어봅니다.

예제에 TestEditingHWPFile.java 를 참고 하여 기본적인 문단 추가를 해보고 있지만 답을 찾을수 없어서 여쭈어 보겠습니다.

해당 소스에서 
Paragraph p2 = s.addNewParagraph();
p2.createText();
p2.getText.addString("문단 추가테스트");

딱 이렇게 추가를 시켰는데 에러는 없는데 손상된 파일이라고 나오네요.

addNewSection
addNewParagraph

이 2개 메소드를 쓰면 손상된 파일이라고 뜨는걸 보면 뭔가 필수적으로 들어가야할 로직이 있는것 같은데 찾지를 못하겠습니다.

Paragraph 같은 경우는 ParagraphAdder 클래스를 보고 추가시켜보려 했으나 잘 되지 않았습니다.

**Comment by neolord0** [comment]
새로 문단을 만들 경우, Paragraph 아래에 다양한 객체를 생성하고 설정해야 합니다.
s.addNewParagraph() 이 함수는 단지 Paragraph 객체만을 추가합니다.
예제 소스인 TestMakingTable.java에..  setParagraphForCell()을 보시면 도움이 될 거 같습니다.
한글은 셀 안의 문단과 페이지의 문단 구조가 동일하기 때문에.. 동일하게 설정하면 됩니다.

보시고 또 다른 의문사항이 있으시면 말씀해 주세요.

**Comment by KimJason8557** [comment]
감사합니다. 바로 해결이 되었습니다. 
이걸로 응용을 많이 하게 될 것 같은데 궁금한 점이 또 생기면 여쭤보겠습니다.
즐거운 하루 보내세요 !
