### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by ngs0932** [neolord0/hwplib#62]
안녕하세요. 이제 막 개발자가 된 신입 웹 개발자입니다.
현재 웹 브라우저에서 보고서형태의 한글파일을 동적으로 생성해야 하는데 선생님이 개발해주신 라이브러리를 사용하고자 합니다.

질문이 두가지가 있는데, 너무 개념없고 초보적인 질문일 수 있어 미리 양해를 부탁드립니다..

1. 새로운 문서를 만드는 코드.
 - 깃허브와 프로젝트를 다운받아서 test패키지의 내용을 이것저것 보다가 새로운 문서를 만드는 
   코드는 없는 것 같아서 폴더에 빈문서를 하나 넣어놓고 해당 파일을 수정하는 방식으로 진행하
   고 있는데 구글링을 하다가 hwplib가 새로운 문서를 만드는 기능도 있다고 해서 질문드립니다.
2. 동적 테이블 생성
 - 웹 페이지에서 보고서 형태로 한글파일을 다운로드 해야하는데, HTML의 table, img의 
   내용을 그대로 가져와서 테이블을 동적으로 생성할 수 있는지, 있다면 어느부분을 참고하고 
   사용하면 되는지가 궁금합니다.

저는 몇일동안 여러가지 시도를 해보고 고민끝에 이렇게 질문을 남기지만 라이브러리를 사용해본 경험이 많지 않아서 개발자님은 질문이 어이없게 느껴지실 수 있을 것 같습니다. 죄송합니다ㅠㅠ..

이상 시간이 되신다면 답변 부탁드리겠습니다!

**Comment by neolord0** [comment]
1. 새로운 문서를 만드는 코드
; 너무 많은 부분을 설정해야 하기 때문에, 코드량이 꽤 많은 거라 생각됩니다. 
예제가 없는 건 순전히 제가 게을러서 입니다. 예제 코드를 조망간 올리도록 하겠습니다.
; 원하는 형태의 hwp 파일을 읽어서, Debug 상태에서 객체의 속성값을 확인하고 동일하게 만드는 방식으로도
진행할 수 있습니다.
<img width="550" alt="스크린샷 2019-08-01 오후 8 29 53" src="https://user-images.githubusercontent.com/24711108/62290036-44e06d00-b49b-11e9-8244-9b7a210426c3.png">
위에 그림은 인텔리J에서 디버그 모드에서 hwp 파일을 읽은  hwpFile파일의 구조를 파악한 부분입니다.
이클립스에도 이런 기능이 있으니, 이 기능을 활용하면 어느 정도 파악하실 수 있으실 거라 생각됩니다.

2. HTML파싱해서  table 이나, image를 만드는 건 가능할 거라 생각됩니다.
html 파싱하는 부분은 다른 코드를 참고하시면 될 거 같고, 한글에서  table이나  image를 만드는 부분은 
예제 코드인 TestMakingTable.java 와 TestInsertImage.java 를 참고하시면 될 듯 합니다.

**Comment by ngs0932** [comment]
답변 감사합니다!
일단 현재 빈 문서를 놓고 수정하는 방식으로 말씀하신 것 처럼  MakingTable과 InsertImage를 한줄 한줄 따라가면서 분석중입니다. 
html을 파싱하는 부분은 다른 코드를 참고하면 된다고 해주셨는데, 혹시 그 코드가 hwplib-master 내부에 있는 코드를 말씀하시는 건가요?

**Comment by neolord0** [comment]
이 라이브러리 내부에는 html 파싱하는 부분이 없습니다. 
html parsing / drawing  부분은 저보다 더 많이 알고 있는 분들이 많고, 그 분들이 올리신 다른 코드도 많이 있습니다. 
찾아보시길 바랍니다.

**Comment by ngs0932** [comment]
바쁘신 시간 내서 답변 감사드립니다. 유용하게 잘 써보겠습니다.
