### ISSUE TITLE
혹시 특정위치의 문단을 삭제할 수 있는 법은 없을까요?

### ISSUE THREAD

**Issue by kamsi76** [neolord0/hwplib#64]
안녕하세요. 다시 질문이 있어 이렇게 문의합니다.

템플릿처럼 특정 문서를 만들어 놓고 필요하면 추가하고 없으면 삭제하고 싶은데...

삭제할 수 있는 방법을 몰라서 질문 드립니다.

혹시 특정 위치의 문단을 삭제할 수 있을까요?

감사합니다.

**Comment by neolord0** [comment]
문의한 기능을 수행하려면,  특정 위치에 있는 문단을 찾고, 그 문단을 삭제해야 합니다.
문단을 삭제하는 건 어려울 게 없는데, 문제는 특정 위치에 문단을 찾는 방법입니다.
보통에 경우, 몇번째 페이지에 몇번째 문단을 찾으려고 하는데.. 이건 파일 구조를 파악하는 것 만으로는  불가능합니다. 한글과 같은 워드 프로세서들은 일반적으로 파일로 저장할 때는 페이지를 나눠서 저장하지 않습니다. 그려질 때 페이지가 만들어지는 방식이기 때문에, 페이지의 구조를 정확히 알려면 그려봐야(계산해 봐야) 합니다. 이 라이브러리는 이 부분을 아직 지원하지 않습니다.   그래서, 몇 번째 페이지에 몇번째 문단을 찾는 방식은 불가능합니다. 

파일에서 다른 조건을 만들 수만 있다면 가능할 거 같습니다. 가령, 문단에 첫번째 단어가 "그러므로"로 시작된다 던지, 문단의 첫번째 글자의 폰트가 "맑은 고딕"인 문단을 찾는다는 등은 가능할 것 같습니다. 이처럼 파일로 저장되는 조건을 찾아야 검색이 가능합니다.위와 같은 검색 조건을 찾아보시길 바랍니다.

**Comment by kamsi76** [comment]
답변 감사합니다.

Text 또는 문단 위치 찾는 것은 만들었었습니다.

                Section section = null;
		Map<String, Object> resultMap = null;

		for (int s = 0; s < hwpFile.getBodyText().getSectionList().size(); s++ ) {
			section = hwpFile.getBodyText().getSectionList().get(s);

			for( int i = 0; i < section.getParagraphCount(); i++ ) {

				logger.debug("'" + findText + "' : '" + section.getParagraph(i).getNormalString() + "'");

				if( findText.equals(section.getParagraph(i).getNormalString()) ) {

					if(resultMap == null ) {
						resultMap = new HashMap<String, Object>();
					}

					resultMap.put("section", section);
					resultMap.put("sectionIndx", s);
					resultMap.put("paragraph", section.getParagraph(i));
					resultMap.put("paragraphIndx", i);

					return resultMap;
				}
			}
		}


궁금한건 예전 Tabel에서 Row를 삭제할 때는 그냥 List를 remove하면 문서에 오류가 발생하였었는데

문단은 그냥 remove하니까 정상적으로 삭제가 되네요.

다시한번 답변 감사합니다.
