### ISSUE TITLE
안녕하세요. 질문이 있습니다.

### ISSUE THREAD

**Issue by KimJason8557** [neolord0/hwplib#65]
안녕하세요.

이제 모든 로직을 다 짜고 파일을 클라이언트에서 받을수 있게끔 스트림으로 보내주고 싶은데 toFile 외에 기능이 있는지 궁금합니다.

HWPFile이 File클래스 상속을 받은게 아니라 FileInputStream 을 쓸 수가 없겠더라고요.
방법이 있다면 가르쳐주십시요

즐거운 주말 보내시기 바랍니다. 감사합니다.

**Comment by neolord0** [comment]
답변이 늦었네요.. ;

음. 이 기능이 앞으로도 사용될 거 같아서.. 추가하였습니다.
새로 받으신 후에,  HWPWriter.toStream() 함수로.. 실행하시면 될 듯 합니다.

**Comment by KimJason8557** [comment]
감사합니다! 답변 해주신줄도 모르고 끙끙 앓고 있었는데 정말 감사드립니다.
좋은 하루 보내세요!
