### ISSUE TITLE
오랜만에 다시 궁금한게 있어서 왔습니다

### ISSUE THREAD

**Issue by KimJason8557** [neolord0/hwplib#66]
안녕하세요.
그동안 한글 라이브러리 통해서 여러가지를 만들었습니다. 
정말 감사드립니다.

한가지 안되는 부분이 있어서 다시 방문했습니다.
지금 소스에 글자모양을 가져오는 부분은 있는데 문단모양을 가져오는 부분이 없는것 같습니다.

좌측, 중앙, 우측정렬을 하고 싶어서 소스를 임의 수정하여 테스트를 해봤는데 잘 안됩니다.

ParaShape 클래스를 호출해서 Alignment 로 정렬을 지정할수 있는것 같은데 호출하는 부분이 없는것 같아
Paragraph 클래스에서 createCharShape, getCharShape 메서드와 동일하게 ParaShape를 설정하게 만들고 
getProperty1().setAlignment(Alignment.Right)
로 설정을 해보았는데 적용이 되지 않는것 같네요.

혹시 문단정렬을 하는 방법이 잘못 되었을까요?

**Comment by neolord0** [comment]
문단의 가로 정렬은.. 
위에서 말씀해주신 대로, ParaShape에 getProperty1().setAlignment() 함수로 설정하면 가능합니다만..
문단에 설정되기 위해서는 한가지 더 작업을 해주셔야 합니다.
Paragraph 객체에 getHeader().setParaShapeId() 함수로 문단에 문단모양 객체를 연결해줘야 합니다.

한글에서는 여러 문단이 하나의 문단 모양을 공통으로 사용할 수 있습니다.
그래서, 문단 모양 객체를 글로벌 객체처럼 선언하고, 각각의 문단에서는 이 문단 모양객체를 링크해서 사용합니다.
문단 모양 객체는 HwpFile.DocInfo.paraShapeList에 저장되는데요.
이 리스트에서 문단모양 객체의 인덱스를 아이디로 설정해 주어야 합니다.

ParaShape ps = HwpFile.DocInfo.addNewParaShape();
... 문단 모양 설정...
int paraShapeId= HwpFile.DocInfo.getParaShapeList().size() - 1;
Paragraph.getHeader().setParaShapeId(paraShapeId);

이런 식으로 설정하시면 될 겁니다.
