### ISSUE TITLE
테이블 테두리만 넓게 하는 방법에 대해 질문드리고자 합니다.

### ISSUE THREAD

**Issue by kamsi76** [neolord0/hwplib#67]
테이블의 테두리를 두껍게 하고 싶은데...
보통 그냥 테이블은 loop 돌면서 처리 하면 됩니다.

그런데 문제가 rowspan 되어 있는 경우에 rowspan 되어 있는 첫번째 row 말고 두번째 row 부터가 문제가 됩니다.

첫번째 cell이 rowspan 되어 있다고 할 때 
첫번째 row에서 두번째 cell의 index가 1인데 
두번째 row에서 두번째 cell의 index가 0으로 시작을 하게 되네요.

그래서 태두리를 그리려고 하는데 자꾸 두번째 row 테두리가 정상적으로 그려지지 않는 문제가 생깁니다.

말이 어렵네요..

혹시 테두리를 두껍게 하고자 하는데 방법이 있는지 문의 드립니다.

즐거운 명절 되세요~

**Comment by neolord0** [comment]
Cell 에  column index 를 구하고 싶으신 거 같은데..  구하는 함수가 잘 못 된 게 아닌가 생각됩니다.
2 행 2열에서 0행, 0열 셀과 1행 0열 셀이 병합되었다면,   
0행 에는 2개의 셀이 들어가고, 0열의 셀(병합된 셀)에는 row span=2로 되어 있고요..
1행 에는 1개의 셀이 들어가고,   그 셀은 row index = 1로 시작됩니다.
이 메커니즘은 HTML에  TABLE 태그와 유사합니다.

만약, 이런 식으로 들어가지 않았다면, 잘 못 만들어진 것일 확률이 있습니다.  아래와 같은 코드로 
전체 테이블의 셀에  row index, col index를 확인해 보시면 명확히 알 수 있으실 겁니다. 

       ControlTable table = (ControlTable) c; 
        for(Row r : table.getRowList()) {
            for (Cell cell : r.getCellList()) {
                System.out.print("   " + cell.getListHeader().getRowIndex() + ";" + cell.getListHeader().getColIndex());
            }
            System.out.println("");
        }
  
그리고, 표의 라인을 설정하는 부분은 약간 까다로운 부분이 있습니다.
셀과 셀  사이에 겹치는 부분에서 어떤 셀의 선이 그려지는 지를 알아야 합니다.
예를 들어, 1행 2열에서 셀 중간에 선을 설정 하려면,
0행 0열 셀의 오른쪽 라인을 설정해야 할지, 0행 1열에 왼쪽 선을 설정해야 할지를 선택해야 합니다.
병합이 된 셀 에서는 약간 더 복잡한 알고리즘이 있으므로, 이 부분은 
한글에서 동일한 표를 만들어서 테스트 해 보신 후에 설정해야 합니다.
