### ISSUE TITLE
손상된 파일의 경우 프로세스가 계속 잡혀 있는 것 같습니다.

### ISSUE THREAD

**Issue by LeBronPark** [neolord0/hwplib#68]
파일이 2005년도 처럼 구버전이나 손상된 파일인 경우등은 exception 이라도  떨어지면 차라리 괜찮을 것 같은데, 헤더 정보를 읽지 못해서 인지 계속 잡고 있는 경우가 있는 것 같습니다.

혹시 헤더 정보 읽기에 실패 하면 차라리 null로 리턴 하면 좋을 것 같습니다.

**Comment by neolord0** [comment]
음. 무한 루프에 빠지는 경우인 데요.   
파일 포맷을 공개한 시점 보다 이른 버전에서 만든 파일에서 오류가 발생하는 경우가 있습니다. 
한글 프로그램도 이상한 파일을 읽다 보면..  비정상 종료하는 경우가 있는데,  
파일 읽기에 특성상, 정상적인 오류처리를 하는 게  어려운 부분이 있습니다. 

읽기 오류나는 파일을 모두 보내주시면 테스트 해보겠습니다. 정상적인 오류처리 부분은 고민해 보겠습니다.

**Comment by LeBronPark** [comment]
안녕하세요. 회신 주셔서 감사 합니다.

첨부해드린 것 처럼 2005년도 버전 문서나 아니면 파일이 깨져서 안열리는 경우등의 문서에서 발생 하는 문제 입니다.

확인 해주시면 감사 드리겠습니다.


Windows 10용 메일에서 보냄

보낸 사람: park.sung kyun
보낸 날짜: 2019년 9월 16일 월요일 오후 4:48
받는 사람: neolord0/hwplib
참조: LeBronPark; Author
제목: Re: [neolord0/hwplib] 손상된 파일의 경우 프로세스가 계속 잡혀 있는 것 같습니다. (#68)

음. 무한 루프에 빠지는 경우인 데요.
파일 포맷을 공개한 시점 보다 이른 버전에서 만든 파일에서 오류가 발생하는 경우가 있습니다.
한글 프로그램도 이상한 파일을 읽다 보면.. 비정상 종료하는 경우가 있는데,
파일 읽기에 특성상, 정상적인 오류처리를 하는 게 어려운 부분이 있습니다.
읽기 오류나는 파일을 모두 보내주시면 테스트 해보겠습니다. 정상적인 오류처리 부분은 고민해 보겠습니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    파일이 첩부되지 않았습니다.
다시 보내주세요.. 

--------- 원본 메일 ---------

    
        보낸사람: LeBronPark <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 19.09.16 16:54 GMT +0900
        제목: Re: [neolord0/hwplib] 손상된 파일의 경우 프로세스가 계속 잡혀 있는 것 같습니다. (#68)
        
        
    
    
        안녕하세요. 회신 주셔서 감사 합니다.



첨부해드린 것 처럼 2005년도 버전 문서나 아니면 파일이 깨져서 안열리는 경우등의 문서에서 발생 하는 문제 입니다.



확인 해주시면 감사 드리겠습니다.





Windows 10용 메일에서 보냄



보낸 사람: park.sung kyun

보낸 날짜: 2019년 9월 16일 월요일 오후 4:48

받는 사람: neolord0/hwplib

참조: LeBronPark; Author

제목: Re: [neolord0/hwplib] 손상된 파일의 경우 프로세스가 계속 잡혀 있는 것 같습니다. (#68)



음. 무한 루프에 빠지는 경우인 데요.

파일 포맷을 공개한 시점 보다 이른 버전에서 만든 파일에서 오류가 발생하는 경우가 있습니다.

한글 프로그램도 이상한 파일을 읽다 보면.. 비정상 종료하는 경우가 있는데,

파일 읽기에 특성상, 정상적인 오류처리를 하는 게 어려운 부분이 있습니다.

읽기 오류나는 파일을 모두 보내주시면 테스트 해보겠습니다. 정상적인 오류처리 부분은 고민해 보겠습니다.

**Comment by LeBronPark** [comment]
메일로 보내드려서 확인 못하신것 같습니다. 파일을 첨부해드려요

[hwp.zip](https://github.com/neolord0/hwplib/files/3615309/hwp.zip)

**Comment by neolord0** [comment]
이 파일은 압축된 부분을 풀다가 손상된 부분에서 무한루프에 빠지는 오류입니다. 
Exception이 발생하게 수정하였습니다.

**Comment by LeBronPark** [comment]
안녕하세요. 올려주신 소스 확인 하여 손상 파일  exception 처리는 확인을 하였습니다. 감사 합니다.
그런데 한가지 유형의 파일중 2005년도 경에 생성된 오래된 파일도 마찬가지로 무한루프에 빠지는 경우들이 있는데. 이부분도 혹시 가능하시다면 확인 부탁 드리겠습니다.
[2005.zip](https://github.com/neolord0/hwplib/files/3640613/2005.zip)

**Comment by LeBronPark** [comment]
네. 감사 합니다.
