### ISSUE TITLE
텍스트 replace 기능 문의

### ISSUE THREAD

**Issue by humblemh** [neolord0/hwplib#69]
안녕하세요 좋은 라이브러리를 공개해 주셔서 감사합니다.

hwp 문서 상에 있는 텍스트만 replace하려고 합니다.

예를 들면 아래와 같이 변경하려고 합니다
안녕하세요 처음뵙겠습니다 -> hello how are you

현재 라이브러리 버전에서 가능한지요?

감사합니다.

**Comment by neolord0** [comment]
파일 전체에 포함된 특정 문자열을 다른 문자열로 변환하는 기능을 말씀하시는 건가요 ??

그 기능은 가능하긴 한데.. 아직 구현되지 않았습니다.

**Comment by humblemh** [comment]
> 파일 전체에 포함된 특정 문자열을 다른 문자열로 변환하는 기능을 말씀하시는 건가요 ??
> 
> 그 기능은 가능하긴 한데.. 아직 구현되지 않았습니다.

**Comment by humblemh** [comment]
빠른 답변 감사합니다
혹시 계획이 있으신가요?

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    정확한 기능이... 
파일 전체에 특정 문자열을 찾아서 다른 문자열로 변환하는 거 말씀이신거죠??  
언제라곤 정확히 말씀드리기 힘들지만, 업데이트 기능 목록에 넣어 두겠습니다.
의외로 간단할 거 같기도 하고요..
   

--------- 원본 메일 ---------

    
        보낸사람: humblemh <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 19.09.25 18:53 GMT +0900
        제목: Re: [neolord0/hwplib] 텍스트 replace 기능 문의 (#69)
        
        
    
    
        빠른 답변 감사합니다

혹시 계획이 있으신가요?

**Comment by humblemh** [comment]
특정 문자열을 찾아서 교체한다기 보다는 한 paragraph 단위로 문장을 교체하려고 합니다.
해당 기능을 쓰려는 이유는 한글에 있는 한글은 영어번역된 문장으로 교체하려는 의도입니다.

아래한글 내부적으로 그것을 어떻게 표현하지는 모르겠는 데 paragraph 단위 즉 사용자가 문장입력해서 **개행**되기 전까지의 문장을 가져와서 번역시킨 후 번역된 문장으로 교체하려고 합니다

감사합니다

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    이 기능을 추가하려고 고민해 보니.. 문서마다 특수한 상황이 너무 많아서..
샘플로 추가하기로 했습니다.   

첨부 파일을 보시면 아시겠지만..

한 문장이  "이것은 빨간색 입니다." 처럼 글자모양(글자색 등)이 하나 이상일 경우, 
변경하는 텍스트의  글자모양이 어긋나는 것을 방지하기 위해  
문장에 첫번째 글자모양을 제외한 모든 글자모양을 삭제하였습니다..

이점을 유의하시길 바랍니다.
 

--------- 원본 메일 ---------

    
        보낸사람: humblemh <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 19.09.26 09:40 GMT +0900
        제목: Re: [neolord0/hwplib] 텍스트 replace 기능 문의 (#69)
        
        
    
    
        특정 문자열을 찾아서 교체한다기 보다는 한 paragraph 단위로 문장을 교체하려고 합니다.
해당 기능을 쓰려는 이유는 한글에 있는 한글은 영어번역된 문장으로 교체하려는 의도입니다.
아래한글 내부적으로 그것을 어떻게 표현하지는 모르겠는 데 paragraph 단위 즉 사용자가 문장입력해서 개행되기 전까지의 문장을 가져와서 번역시킨 후 번역된 문장으로 교체하려고 합니다
감사합니다

**Comment by humblemh** [comment]
> p{margin-top:0;margin-bottom:0} 이 기능을 추가하려고 고민해 보니.. 문서마다 특수한 상황이 너무 많아서.. 샘플로 추가하기로 했습니다.    첨부 파일을 보시면 아시겠지만.. 한 문장이  "이것은 빨간색 입니다." 처럼 글자모양(글자색 등)이 하나 이상일 경우,  변경하는 텍스트의  글자모양이 어긋나는 것을 방지하기 위해   문장에 첫번째 글자모양을 제외한 모든 글자모양을 삭제하였습니다.. 이점을 유의하시길 바랍니다.  
> […](#)
> --------- 원본 메일 --------- 보낸사람: humblemh <notifications@github.com> 받는사람: neolord0/hwplib <hwplib@noreply.github.com> 참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com> 날짜: 19.09.26 09:40 GMT +0900 제목: Re: [neolord0/hwplib] 텍스트 replace 기능 문의 (#69) 특정 문자열을 찾아서 교체한다기 보다는 한 paragraph 단위로 문장을 교체하려고 합니다. 해당 기능을 쓰려는 이유는 한글에 있는 한글은 영어번역된 문장으로 교체하려는 의도입니다. 아래한글 내부적으로 그것을 어떻게 표현하지는 모르겠는 데 paragraph 단위 즉 사용자가 문장입력해서 개행되기 전까지의 문장을 가져와서 번역시킨 후 번역된 문장으로 교체하려고 합니다 감사합니다 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

감사합니다!
