### ISSUE TITLE
kr.dogfoot.hwplib.reader.HWPReader.fromURL 관련 문의 입니다

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#7]
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170819620::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170816654::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170825669::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170826379::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170828596::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170830049::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170903637::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170904764::00::1::1

위 주소 파일이 안열립니다.

확인 부탁드립니다.
수고하세요 ^^

**Comment by neolord0** [comment]
수정 완료 했습니다.

**Comment by osc91** [comment]
감사합니다.
자꾸 귀찮게 해드려 죄송하네요 ^^;;

수고하세요.

**Comment by neolord0** [comment]
괜찮습니다. 제가 밥벌이 하는 일이 있어서.. 빨리 고쳐드리진 못하지만..
버그를 잡아서. 프로그램이 좀 더 완전해 질 수 있다면. 저도 보람됩니다.
