### ISSUE TITLE
문단 텍스트 변경시 이슈

### ISSUE THREAD

**Issue by humblemh** [neolord0/hwplib#72]
안녕하세요 문단텍스트 변경 예제를 잘 사용하고 있습니다.

해당 코드를 이용해서 문단을 번역된 문장으로 교체하면 한글로 파일오픈시 아래와 같은 오류화면이 발생합니다

![image](https://user-images.githubusercontent.com/15937052/66635098-6bfcad00-ec49-11e9-82ff-fd0d56d26f45.png)

몇 가지 테스트를 해보면 문단 추출후 replace시 번역문 대신 원문을 다시 삽입하면 위의 화면과 같은 에러가 발생을 안합니다.
길이때문인가 싶어서 번역된 문장을 원문 길이만큼 짤라서 넣어주어도 동일한 에러가 발생합니다.

11.hwp 원문이고 11_changed.hwp은 변경된 파일입니다

[sample.zip](https://github.com/neolord0/hwplib/files/3716359/sample.zip)

그리고 이런 에러 포맷이 뭔가 안맞아서 그러는 것 같은 데 디버깅하려면 어떻게 해야 하는 지요?

감사합니다.

**Comment by neolord0** [comment]
변경된 문단이랑 저장된 레이아웃이 맞지 않아서.. 그런 거 같습니다.
한글(HWP)는 출력속도를 높이기 위해서.. 문단을 출력할 때 만들어진 레이아웃 데이타를 저장하고
다음에 출력할 때 이를 사용합니다. 이 부분을 문단에서 삭제하면 될 거 같습니다..

 private static void changeParagraphText(Paragraph paragraph) throws UnsupportedEncodingException {
        ArrayList<HWPChar> newCharList = getNewCharList(paragraph.getText().getCharList());
        changeNewCharList(paragraph, newCharList);
        removeLineSeg(paragraph);
        removeCharShapeExceptFirstOne(paragraph);
}

private static void removeLineSeg(Paragraph paragraph) {
        paragraph.deleteLineSeg();
}

위에 코드와 같이 문단별로.. removeLineSeg() 함수를 호출하여.. 저장된 레이아웃을 삭제하고 저장하면 될 듯 합니다. 문단에 레이아웃이 없으면, 처음에 그려질 때 다시 레이아웃을 계산하는 듯 합니다.

아마도 이런 문제가 아닐까 생각됩니다.

**Comment by humblemh** [comment]
감사합니다! 말씀하신 대로 하니깐 정상적으로 작동됩니다
