### ISSUE TITLE
특정 페이지에만 쪽번호 감추기를 하고 싶은데... 

### ISSUE THREAD

**Issue by kamsi76** [neolord0/hwplib#73]
특정 페이지에만 쪽번호 감추기를 하고 싶은데..

어떻게 하면 되는지 알수 있을까요??

다른건 알겠는데 CtrlHeaderSectionDefine 이넘을 어떻게 접근하는지를 모르겠어요..ㅜㅜ;;

늘 감사합니다.

**Comment by neolord0** [comment]
특정 페이지만 쪽 번호를 감추는 건 불가능합니다.
다만.. 한글은 구역(섹션)이라는 단위를 넣어서, 비슷한 기능을 하는 데요.
하나의 한글파일은 여러 개의 섹션으로 구성되어 있고요, 또, 하나의 섹션은 여러 개의 문단으로 구성됩니다.
파일 내부에는 페이지라는 객체가 존재하지 않습니다. 
페이지는 섹션 또는 문단 들을 그려서 나온 결과로 만들어집니다. 그래서, 특정 페이지만 쪽 번호를 감추는 것은 불가능합니다. 다만, 섹션을 고정시켜서, 페이지가 만들어지는 것을 예측할 수 있게 한글 파일을 만들 수 있다면, 
페이지에 해당되는 섹션에 첫번째 문단에 포함된 ControlPageNumberPosition 컨트롤 객체를 설정하여 가능할 수 있지 않을 까 생각됩니다.  
CtrlHeaderSectionDefine 이라는 객체는 ControlSectionDefine(섹션 정의 컨트롤)에 포함된 객체인데..
섹션에 첫번째 문단은, ControlSectionDefine(섹션 정의 컨트롤)과 ControlColumnDefine(단 정의 객체)를 꼭 포함하고 있어야 합니다. 

파일을 만들어서 읽어서, 디버그 정보들을 통해 파일 구조를 파악해 보시면 도움이 될 겁니다.
