### ISSUE TITLE
페이지가 틀렸을때와 똑같은 제목이 문서내에 나왔을때 stop해버리는 현상

### ISSUE THREAD

**Issue by kangyongseog** [neolord0/hwplib#74]
hwplib를 공유해 주셔셔 너무나 잘쓰고 있습니다.
해당 부분을 다운받아서 분석/수정하고 있는데 페이지번호가 1,2,3,5이렇게 나오는 부분은 

 private static void paragraph(Paragraph p, TextExtractMethod tem,
                                  StringBuffer sb) throws UnsupportedEncodingException {
        ParaText pt = p.getText();
        System.out.println("getText출력!");
        if (pt != null) {
            int controlIndex = 0;

            for (HWPChar ch : pt.getCharList()) {
                switch (ch.getType()) {
                    case Normal:
                        normalText(ch, sb);
                        break;
                    case ControlExtend:
                        if (tem == TextExtractMethod.InsertControlTextBetweenParagraphText) {
                            sb.append("\n");
                            try {
                                ForControl.extract(
                                        p.getControlList().get(controlIndex), tem, sb);
                                controlIndex++;
                            }catch(NullPointerException ex){
                                System.out.println("getCharList="+controlIndex+"|||"+ex.getMessage());
                               continue;//////////////////수정한 내용
                            }
                        }
                        break;
                    default:
                        break;
                }
            }
            sb.append("\n");
        }
        if (tem == TextExtractMethod.AppendControlTextAfterParagraphText) {
            controls(p.getControlList(), tem, sb);
        }
    }
이렇게 강제로 continue하게 처리를 했지만
제목이 중간에 동일하게 나오는 부분에서 reading이 멈춰버리는 부분은 찾을수가 없네요
조언좀 해주시면 정말 감사하겠습니다. 고맙습니다.

[20010_sample.zip](https://github.com/neolord0/hwplib/files/3741819/20010_sample.zip)

**Comment by neolord0** [comment]
이 코드는 텍스트 추출하는 코드네요.. 근데, 읽기에 멈춰버리는 다는 것은 이 코드랑 상관없이 읽기 부분에서 오류가 나는 것 같습니다
한글 파일이 파일의 세부 버전에 따라 약간씩, 추가/삭제가 된 부분이 있는데 한컴에서 공개한 문서에는 특정 버전의 구조만 표현되어 있습니다. 공개한 문서 이전/이후 버전에는서 오류가 날 수 있고, 라이브러리 사용자 분들이 보내주시는 오류 파일을 분석하여 수정하고 있습니다.

에러나는 파일을 보내주시면 분석해 보겠습니다.

**Comment by kangyongseog** [comment]
에러나는 올려드렸습니다. 시간되시면 한번 봐주시면 감사하겠습니다.

**Comment by neolord0** [comment]
아.. 이거... 깜빡했네요.. 답변이 늦어서 죄송합니다. 

늦었지만...  보내주신 파일을 테스트 해보니.. 이상 없는 거 같은데요..
수정하신 소스를 보니.. 
  p.getControlList().get(controlIndex)이 NULL 인 경우가 있는 거 같습니다.
일반적인 경우,  null이 나오면 안되는 부분입니다. 
이게 null 이 나왔다는건...  파일을 잘 못 읽었거나, 잘 못 만들어진 파일일 확률이 있습니다.
kangyongseog님이 올리신 파일을 받아서.. 테스트 해보니.  문제가 없던데.. 

혹시, 파일을 잘 못 보내주신 게 아닐지요.. ?? 
아니면, hwplib가 최신 버전에서 이미 수정된 부분일 수도 있고요..

확인해보세요..

다시 한번 늦어서 죄송합니다.
