### ISSUE TITLE
문서 중간에 [쪽 번호 제어]가 들어가 있으면 페이지 번호가 일그러 지며 페이지도 다 읽히지가 않습니다.

### ISSUE THREAD

**Issue by kangyongseog** [neolord0/hwplib#75]
19번째 이슈는 제가 진단을 잘못한듯 합니다. 죄송합니다.
정확히 페이지를 분석해 보니 법률..제..호 앞에 [누름틀 시작]이 있으며 그 앞에 [쪽 번호 제어]가 있네요.ㅠㅠ 이놈이 오면 더이상 내용이 없는걸로 판단해서 여기까지만 출력이 됩니다.
시간되시면 확인좀 부탁드립니다.
참고 : 해당 사항은 한컴 오피스가 설치되어 있지 않으면 안보이더라구요.
[20010_sample.zip](https://github.com/neolord0/hwplib/files/3748725/20010_sample.zip)

**Comment by neolord0** [comment]
찾아보니까.. 제가 라이브러리 만들때, 쪽 번호 제어 컨트롤을 안 만들었네요.
추가 해서.. 보내주신 파일을 읽어보니 잘 동작하네요.

**Comment by kangyongseog** [comment]
오늘 개발자님의 소스를 clone해서 해보았는데  아무래도 
ForControlPageOddEvenAdjust Class에 read메소드가 빠진것 같습니다.
그래서
  private static void pageOddEvenAdjust(Control c, StreamReader sr) throws IOException {
        ForControlPageOddEvenAdjust.read((ControlPageOddEvenAdjust) c, sr);
    }
아래의 구문에서 read메소드가 없다는 오류가 나타납니다. ㅠㅠ
시간되시면 한번만 더 확인 좀 부탁드리겠습니다. 고맙습니다.

**Comment by kangyongseog** [comment]
오늘 개발자님의 소스를 clone해서 해보았는데 아무래도
ForControlPageOddEvenAdjust Class에 read메소드가 빠진것 같습니다.
그래서
private static void pageOddEvenAdjust(Control c, StreamReader sr) throws IOException {
ForControlPageOddEvenAdjust.read((ControlPageOddEvenAdjust) c, sr);
}
아래의 구문에서 read메소드가 없다는 오류가 나타납니다. ㅠㅠ
시간되시면 한번만 더 확인 좀 부탁드리겠습니다.  매번 정말 고맙습니다. 
언제 시간되면 고기라도 대접해 드리고 싶네요..
-----Original Message-----

**Comment by neolord0** [comment]
급하게 올리다 보니, 빠졌군요.  죄송...
빠진 부분 다시 올렸습니다.

**Comment by kangyongseog** [comment]
고맙습니다. 굉장히 잘되네요 잘쓰겠습니다.~ 꾸벅~
