### ISSUE TITLE
총페이지 수를 알고 싶습니다.

### ISSUE THREAD

**Issue by rijachung28** [neolord0/hwplib#77]
검색 엄청하다가 여기에 들어오게 되었습니다.

좋은 소스 공개해주셔서 정말 정말 대단히 감사합니다.

질문글을 여기에다가 올리게되어 민망하고 죄송스럽지만, 코드를 살펴봐도 이해가 안되는 점이 있어서 질문드립니다.

혹시 파일의 총 페이지수를 확인하려면 

hwpFile.getBodyText().getSectionList();

이 sectionlist 가 각 페이지라고 생각하면 되는걸까요 ?

감사합니다..

**Comment by neolord0** [comment]
페이지수는 지금 단계에서는 구할 수 없습니다.
section은 구역입니다. 구역은 여러개의 문단으로 구성되는데.. 
한글은 아마도 그 문단을  하나하나씩 그려나가다 그릴 공간이 부족할 때마다 페이지가 추가되는 방식으로 페이지를 처리하는 것 같습니다. 
그릴 수 있어야 페이지를 나눌 수 있다는 건데요.. 그리는 방법에 대해서는 아직  잘 모릅니다.

**Comment by rijachung28** [comment]
덕분에 많이 알게되네요.. doc 와 같은 포맷을 공유하므로 poi-ooxml 의 기본 속성기능으로 확인이 가능할거 같기는 합니다. 저녁에 한번 해봐야 겠네요. 만약 성공하면 이곳에 공유하겠습니다.

**Comment by rijachung28** [comment]
답변을 토대로 궁금증이 생기어 한컴 공개문서와 poi 자체로 진행해봤는데 말씀대로 관련정보가 없네요.
아 정말 아쉽습니다.
댓글 남겨주셔서 감사드립니다.
