### ISSUE TITLE
안녕하세요. 문단번호 이슈관련 문의드립니다.

### ISSUE THREAD

**Issue by Chunsjun** [neolord0/hwplib#79]
안녕하세요! 좋은 라이브러리를 개발해주셔서 감사합니다. 항상 감사한 마음으로 사용하고 있습니다.

한글2018 [문서버전 5.1.0.1.1] [프로그램버전 10.0.0.8223]에서 문단번호 관련 이슈가 있어서 문의드립니다.

문단번호가 있는 한글2018 문서를 sample패키지에 있는 ReWriting_HWPFile.java 를 사용하여 파일을 읽어서 다시 쓰게되면 입력한 문단번호와 정렬 등이 사라지는 이슈가 있습니다.
이상하게도 문단번호 단독으로 작성되어있으면 문단번호와 정렬들이 사라지는데 글머리표와 같이 있게되면 사라지지 않습니다.

해당현상을 해결해보려고 디버깅을 시도해봤는데... 한계에 부딪혀서 이렇게 문의를 드립니다.

해당현상이 있는 샘플 파일도 첨부합니다.

[sample_hwp.zip](https://github.com/neolord0/hwplib/files/4028586/sample_hwp.zip)

감사합니다.

**Comment by neolord0** [comment]
제가 보내주는 파일로 테스트 해보니.. 
HWP_2018_문단번호글머리표.hwp  파일은 잘 되는데.. 
HWP_2018_문단번호.hwp 파일은 문단 모양이 초기화되던데..
두 파일에 차이점은 뭔가요 ??

**Comment by Chunsjun** [comment]
안녕하세요! 

두 파일의 차이점은 단순히 글머리표가 있고없고 차이입니다. 버전정보나 쓰여져있는 내용은 전부 동일합니다... 

HWP_2018_문단번호.hwp 를 Reader로 읽어올때 Style정보나 ParaShape정보를 읽어오지 못하는것까진 파악을 했지만 원인을 찾지 못하였습니다...

**Comment by neolord0** [comment]
수정 했습니다.
5.0.2.5 버전 이전에는 1-7 수준으로 문단 번호가 저장되나.
5.0.2.5 버전 이후에는 8-10수준이 추가되어.. 1-10 수준으로 저장 되더라고요..

**Comment by Chunsjun** [comment]
정상동작 확인하였습니다!

기존에 제가 한글2014로 잘 사용하다가 2018로 바꾼 이후로 생긴 현상이었는데.. 한글 버전업이 되면서 수준 범위가 추가가 되서 생긴 현상이였군요..

빠른 응답과 대응 정말 감사합니다. 
좋은 라이브러리 감사히 잘 사용하겠습니다.

2020년 새해 행복하시고 복 많이 받으시길 바랍니다.
