### ISSUE TITLE
kr.dogfoot.hwplib.reader.HWPReader.fromURL 추가 문의 입니다.

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#8]
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170530919::01::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170912965::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170902821::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170902821::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170819116::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170823794::00::1::1

또 올리네요 ^^; 

위 주소 파일이 안열립니다.
확인 부탁드립니다.

그리고 혹시 위 파일을 열면 자바 실행이 거기서 멈춰버리는데요
안 멈추고 다음 진행으로 넘어갈순 없을까요?

그럼 수고하세요 ^^

**Comment by neolord0** [comment]
수정했습니다. 
받아서 테스트 해보세요.

그런데, 무슨 사이트에서 사용하시는지요 ?? 알고 싶습니다. 
나중에 라이브러리 소개할때.. 사용 사례 같은게 있으면 좋을 것 같아서요..

**Comment by neolord0** [comment]
에러나면 ... 음.. .try catch로 잡으면 되지 않을 까요 ??

**Comment by osc91** [comment]
답변 감사합니다 ^^

사이트는 제가 개인적으로 말씀드리기가 좀 곤란하네요. 죄송 ^^;;
