### ISSUE TITLE
용지여백 조정은 가능할까요?

### ISSUE THREAD

**Issue by KimJason8557** [neolord0/hwplib#80]
안녕하세요 
3달쯤 전에 만들어주신 라이브러리로 개발을 다했었는데
또 문제가 있는 부분이 조금 있어서 질문 드립니다.

용지여백을 좌우 부분을 좀 줄이고 싶은데 제가 찾아보니

ControlSectionDefine
PageDef
이 2개의 클래스를 잘 이용하면 조정이 가능할 것 같은데 예제에 없어 적용하기가 어렵습니다.

제가 해본 방법은 paragraph.getControlList() 받아서 해당 리스트에 
ControlSectionDefine를 담아봤더니 Null 에러가 생깁니다.

어떻게 해결하면 좋을지 부탁드립니다.

---------------------------------------------------------------
그리고 용지방향 가로, 세로에 대해서도 찾아봤는데

PageDef.getPageDefProperty()로 받아서 
PaperDirection 을 Landscape 로 설정하면 되는지도 부탁드립니다.

**Comment by neolord0** [comment]
ControlSectionDefine이 객체를 찾는 방법은 ... sample/Changing_PaperSize.java 를 참고 하시면 될 거 같고요..
용지방향은 그 함수가 맞습니다.
