### ISSUE TITLE
개행 제거 가능할까요??

### ISSUE THREAD

**Issue by jmj909** [neolord0/hwplib#81]
AppendControlTextAfterParagraphText 메소드를 사용해서
한글내의 엑셀 형식의 데이터를 읽고있는데요
칸별로 개행이 되었으면 하는데
칸 내에 개행 문자가 있을경우 읽어서 엔터가 먹더라구요.
혹시 개행문자를 제거하는 함수도 따로 만들어져 있을까요??

답변해주시면 정말 감사하겠습니다 :)

**Comment by neolord0** [comment]
엑셀 형식의 데이터라는 것이 표 컨트롤을 사용했다는 뜻인가요 ? 
표에 셀 별로만 개행되고, 표의 내부에서는 개행되지 않았으면 좋겠다는 건가요?

맞는다면 .. 

문단 별로 개행이 들어가는 부분은 
kr.dogfoot.hwplib.tool.textextractor.ForParagraphList 클래스에  paragraph() 입니다.

    private static void paragraph(Paragraph p, TextExtractMethod tem,
                                  StringBuffer sb) throws UnsupportedEncodingException {
        ParaText pt = p.getText();
        if (pt != null) {
            int controlIndex = 0;
            for (HWPChar ch : pt.getCharList()) {
                switch (ch.getType()) {
                    case Normal:
                        normalText(ch, sb);
                        break;
                    case ControlExtend:
                        if (tem == TextExtractMethod.InsertControlTextBetweenParagraphText) {
                            sb.append("\n");
                            ForControl.extract(
                                    p.getControlList().get(controlIndex), tem, sb);
                            controlIndex++;
                        }
                        break;
                    default:
                        break;
                }
            }
            sb.append("\n");    // ==> 이 부분이 문단 별로 개행을 넣어주는 부분입니다. 이 부분을 삭제. 
        }
        if (tem == TextExtractMethod.AppendControlTextAfterParagraphText) {
            controls(p.getControlList(), tem, sb);
        }
    }

이 부분을 삭제하면 아마도, 셀 별로 개행되지 않을 겁니다.  
셀 별로 개행을 추가해 주실려면..
 
kr.dogfoot.hwplib.tool.textextractor.ForControl 클래스에 table() 함수에.. 

    private static void table(ControlTable table, TextExtractMethod tem,
                              StringBuffer sb) throws UnsupportedEncodingException {
        for (Row r : table.getRowList()) {
            for (Cell c : r.getCellList()) {
                  ForParagraphList.extract(c.getParagraphList(), tem, sb);
                  sb.append("\n"); // ==> 여기에 추가..
            }
        }
    }

이렇게 고치시면 원하는 데로 될 거 같습니다.
요점만 설명해 드렸는데 요 ForParagraphList.extract() 함수 같은 경우는 
표 컨트롤 이외에 다른 데서도 사용하니,다른 부분에서는 지금과 같이(문단 별로 개행하여) 처리하고 싶으시면 
클래스 나 함수를 별로도 만들거나 옵션 처리를 하는 게 좋을 거 같습니다.
