### ISSUE TITLE
POI 라이브러리 관련 문의드립니다.

### ISSUE THREAD

**Issue by sinn232** [neolord0/hwplib#82]
좋은 라이브러리 제공해주셔서 감사드립니다.

해당 라이브러리에서 Apache POI 라이브러리 4.1.0을 사용하고 있는데요

제가 개발중인 기존 프로젝트에서 엑셀 파싱을 위해 POI 라이브러리 3.9를 쓰고 있습니다..

버전을 바꾸니 한글파싱이 안되고 4.1.0에 맞추니 엑셀 파일을 못읽어들여서 그런데요.

혹시 해결방법이 있을까 한번 여쭤봅니다.

**Comment by neolord0** [comment]
음... 테스트 해보니.. 파일 처리하는 부분이 약간 다르군요..
아마도 살짝 수정하면 될 거 같습니다.
다음 중으로 수정하여 올리겠습니다.

**Comment by neolord0** [comment]
3.9 로 바꿔보면.. kr.dogfoot.hwplib.util.compoundFile.reader.CompoundFileReader 와.
kr.dogfoot.hwplib.util.compoundFile.writer.CompoundFileWriter에서 에러가 발생하는데요..
아래 파일과 같이 고치시면 돼지 않을까 생각됩니다.

제가 3.9 버전에 대해서..  정확히 알지 못하기 때문에.. 대강의 답만 드립니다.  
사용하기전에.. 테스트를 해보시고..  좀 더 정확한 답을 찾아보심이 좋을 듯 합니다. 

[fixit.zip](https://github.com/neolord0/hwplib/files/4058580/fixit.zip)
