### ISSUE TITLE
파일열기가 안되는 파일들입니다.

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#85]
파일열기가 안되는 파일들입니다.
확인 부탁드립니다.
수고하세요.
[공고문.zip](https://github.com/neolord0/hwplib/files/4126246/default.zip)

**Comment by neolord0** [comment]
수식 부분이 문제가 있었던 거 같습니다.
수정했습니다.

**Comment by osc91** [comment]
감사합니다.
수고하셨습니다 ^^
