### ISSUE TITLE
파일열기가 안되는 파일입니다.

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#87]
또 올리네요 ^^;;

확인부탁드립니다.
수고하세요.

[공고문.zip](https://github.com/neolord0/hwplib/files/4138135/default.zip)

**Comment by neolord0** [comment]
수정 했습니다. 
받아서 테스트해보세요..

**Comment by osc91** [comment]
파일이 잘여립니다. ^^

**Comment by osc91** [comment]
파일이 잘열립니다.
감사합니다 ^^
