### ISSUE TITLE
안녕하세요 한가지 질문이 있습니다!

### ISSUE THREAD

**Issue by LeeYunSeop** [neolord0/hwplib#88]
안녕하세요 개발자님
만들어주신 라이브러리 정말 감사하게 잘 쓰고있습니다.

한글파일을 텍스트로 추출할 때 혹시 페이지 단위로 추출을 하거나 아니면
일부분씩 끊어서 추출이 가능한지 여쭤봅니다.
용량이 큰 파일일 경우에 한꺼번에 추출을 하면 OutOfMemory가 날 경우가 있어서 페이지 단위로 끊어서 처리를 하고 싶은 마음에 글을 남겨봅니다.

**Comment by neolord0** [comment]
지금 라이브러리는 전체를 읽어서.. 메모리에.. 올려놓고.. 다른 작업(텍스트 추출  등)을 합니다
문제를 해결하려면.. 전체 파일을 읽고 텍스트로 추출하는 게 아니라.. 한 문단 씩 읽고 저장하는 구조로 바꿔야 할 거 같습니다.  
그리고, 한글은 파일 구조 내에서는 페이지를 알 수 없어서.. 페이지 별로 저장하는 것을 불가능합니다.
전체 파일의 내용에서 텍스트를 추출하길 원하시면.. 어느 정도 수정하면 가능할 거 같습니다.

사내 보안 등에 문제가 없다면, 파일을 올려주세요. 테스트 하는데. 도움이 될 거 같습니다.

**Comment by LeeYunSeop** [comment]
답변 감사드립니다.
테스트할 수 있는 문서 찾아서 월요일에 메일로 보내드려도 될까요?
​
-----Original Message-----

**Comment by neolord0** [comment]
네 그러세요..

**Comment by LeeYunSeop** [comment]
대용량 첨부 파일은 30일간 보관 / 100회까지 다운로드 가능




테스트용 문서입니다.hwp 10MB


  다운로드 기간: 2020/02/24 ~ 2020/03/25






안녕하세요
회사 문서를 보내드리려고 했는데 거절당해서..부득이하게 제가 좀 만들어봤습니다.
16000페이지정도 글자랑 사진 하나 반복시켜서 만들긴했는데
성의가 없어 보이거나 부족하시다면 다시 만들어서 보내드리겠습니다.
감사합니다. 
-----Original Message-----

**Comment by neolord0** [comment]
그런데요.. 받을 수 있는 링크가 안 보입니다.
10M 정도면이고.. 테스트용 파일이면.. github에 올려도 될 듯 합니다.
글자 입력하는 에디터에 파일을 drag/drop 하시면.. 업로드 됩니다.

**Comment by LeeYunSeop** [comment]
네이버 대용량 첨부파일로 보냈는데 잘 안올라간거 같습니다.
github에 hwp 확장자가 첨부가 안되서 압축해서 올립니다.
감사합니다.
[테스트용 문서입니다.zip](https://github.com/neolord0/hwplib/files/4247565/default.zip)

**Comment by neolord0** [comment]
추가 했습니다.. 받아서.. 테스트 해보세요..
sample/Extracting_Text_From_Big_File.java 을 참고하시면 될 거 같습니다.

리스너를 만들어 넣어주면.. 파일을 읽으면서.. 문단 별로 텍스트를 추출하여 넘겨줍니다.
님이 원하는 기능을 제가 잘 못 이해했거나.. 오류/추가 사항 있으시면 남겨주세요..

**Comment by LeeYunSeop** [comment]
요구사항 수정해주셔서 정말 감사하고 고생하셨습니다.
아직 메이븐 레파지토리에는 안올라가있는거죠~?
따로 받아서 빌드해서 써야하는거죠?

**Comment by neolord0** [comment]
메이븐 레파지토리는 3월 초까지 업데이트하겠습니다.
