### ISSUE TITLE
kr.dogfoot.hwplib.reader.HWPReader.fromURL 추가 문의 입니다

### ISSUE THREAD

**Issue by osc91** [neolord0/hwplib#9]
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170202650::00::1::3
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170127713::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170405233::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170506114::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170705666::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170509742::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20170505081::00::1::1
http://www.g2b.go.kr:8081/ep/co/fileDownload.do?fileTask=NOTIFY&fileSeq=20160616587::00::1::1

또 올리네요 ^^;
위 주소 파일이 안열립니다.
확인 부탁드립니다.

위 파일들은 나라장터 전자입찰공고의 공고문인데요 제가 테스트해본거로는 이번거만 처리되면
거의 되는거 같네요..

그리고 지난 요청에서 말씀드린거는 

에러가 나지 않아 try catch 잡을수가 없더라구요

그냥 'kr.dogfoot.hwplib.object.HWPFile hwpFile = kr.dogfoot.hwplib.reader.HWPReader.fromURL(hwpurl);'
위 부분에서 프로그램이 중지가 되어버려서요

위 주소로 테스트 해보시면 확인이 가능할거 같습니다.

수고하세요 ^^

**Comment by neolord0** [comment]
보니까.. 위에 6개 부분은 메모가 들어가 있는데.. 이 부분은 문서에 없어서.. 시간이 걸릴거 같습니다.

**Comment by neolord0** [comment]
회사일이 바빠서.. 이제야 수정했네요.. 
받아서 테스트 해보세요.

**Comment by osc91** [comment]
잘 처리되네요 수고하셨습니다. ^^
