### ISSUE TITLE
본문 누름틀에 다른파일 내용을 넣을수 있나요?

### ISSUE THREAD

**Issue by BayabaMoon** [neolord0/hwplib#90]
a.hwp 에 본문 이라는 누름틀이 있습니다.
b.hwp 내용 (텍스트, 이미지, 표 등) 전체를 a.hwp 본문에 삽입할 수 있나요?

**Comment by neolord0** [comment]
가능할 거 같습니다 만... 내용을 넣은 후에... 문서의 형식이나 형태가 변경될 수 있는데...
이 부분은 문서마다 다른 방식으로 처리해야 할 수도 있습니다.

워드 프로세스에서 파일 내용이라고 것은 문단 리스트 입니다.
문단에 복사하여 붙이는 것과 동일합니다. 문단을 복사할때, 문단에서 포함된  컨트롤(표, 글상자등)과 
문단에서 사용한 속성(글자모양, 문단모양, 배경/선 모양 등)을 함께 복사해서 붙여 넣으면 됩니다.

파일 간에 문단을 복사하는 샘플(kr.dogfoot.hwplib.sample.Copying_Paragraph_Between_HWPFile 
)과  누름틀에 내용를 변경하는 샘플(kr.dogfoot.hwplib.sample.Setting_ClickHereFieldText)을 참고하시면
도움이 될거라 생각됩니다.

**Comment by philocent** [comment]
@neolord0 혹시 조금 더 자세히 설명 해 주실 수 없을까요. 저도 질문자님과 같은 상황에 있는데 현재 상태는 문단 복사 까지는 완료 했습니다. 그런데 누름틀 안으로 들어가는 것이 아니고 누름틀 뒤에 복사가 되었는데 어떻게 누름틀 안으로 해당 표를 넣을 수 있을까요?

**Comment by neolord0** [comment]
누름틀은 시작 객체와 끝 객체로 나눠서.. 문단에 삽입되어 있습니다.
예를 들어..
가나다라(누름틀 시작)마바사(누름틀 끝)아자카타 
이렇게요.. 

질문에서 누름틀 뒷쪽에 내용이 들어간다는 것은 아마도..(누름틀 끝) 객체를 찾아서 그 뒤에 넣은 게.. 아닐까 생각됩니다.
좀 더 정확한 답변을 원하시면 philocent 님  프로그램 소스와 hwp 파일을 보내주세요.

**Comment by philocent** [comment]
친절한 답변 감사합니다. 문단 객체 하나씩 다 찍어보면서 HWPChar 확인하다가 말씀하신대로 누름틀 끝 객체가 중간에 있는거 보고 끝으로 보내보니 잘 되네요! 

한가지 더 이슈가 있는데 문단 안에 ControlEquation 수식이 있을때 복사 하면 파일이 깨지네요. 소스 보니 ParagraphCopier 내에 ControlEquation 에 대한 복사 구현 부분이 없는데 해당 부분은 아직 To-Do 인걸 까요?

**Comment by neolord0** [comment]
문단 복사 기능에서.. 컨트롤의 복사 기능은 아직 하지 않았습니다.
만들 당시. 요청하신 분이 컨트롤은 사용하지 않는다고 하셔서 일단 공백으로 남겨뒀습니다.
작업량이 워낙 많은 모든 컨트롤을 한번에 하기는 힘듭니다. 
요청이 오는데로 처리하고 있습니다. 5월에는 표 컨트롤 복사 기능을 추가한 바 있습니다.
ControlEquation 복사는 그닥 어려울 게 없으니.. 직접 수정해 보셔도. 좋을 듯 합니다. 

안 되면 추가로 질문해 주세요.

**Comment by philocent** [comment]
다시한번 친절한 답변 감사드립니다. 직접 수정해보고 가능하다면 pull request 드리겟습니다.
