### ISSUE TITLE
copyControlList 메서드 문의

### ISSUE THREAD

**Issue by kimeuietae** [neolord0/hwplib#91]
안녕하세요, 먼저 제공 해 주신 라이브러리 덕분에 많은 공부가 되고 있습니다.
실례지만, ParapraphCopyer.Java 클래스 내에 copyControlList 메서드는 현재 제공 되지 않는다고 되어 있는데, 혹시 이미지, 표 만이라도 복사 가능한 기능이 추가 될 수 있을까요?
아니면 어떠한 복잡한 로직으로 인해 추가가 어려울 까요?
copyText 메서드를 참고로 추가 해 보고 있는데, 잘 되지 않아 여쭤 봅니다.
그럼 바쁘실텐데 답변 부탁 드리겠습니다. 감사합니다.

**Comment by neolord0** [comment]
음.. 구현 안 되어 있었군요... 지금 알았습니다. 
이 루틴을 작성할 때.. 요청하신 분이 문단 내에 text 만 사용한다고 하셔서 빨리 배포하려고 
그 부분은 작성하지 않았고 있다가.. 회사 업무다 뭐다 해서.. 그렇게 잊고 있었던 거 같습니다.

이 부분은 기술적으로 어려운 부분은 아니지만 엄청난 작업량을 요구하는 부분인데요.
전체를 구현하려면 좀 걸릴 거 같습니다만,  요청하신 이미지, 표 컨트롤 만 일단 하는 거라면, 
회사일이랑 병행해서 짬짬이 한달 정도 걸릴 거 같습니다.

더 급하게 사용하실 거라면.. 직접 만드셔야 할 거 같습니다.
이 부분은 조금만 신경 쓰시면 만드실 수 있는 부분입니다.

**Comment by kimeuietae** [comment]
네. 알겠습니다. 
​
답변 주셔서 감사합니다.
​
좋은 하루 되세요~
​
-----Original Message-----

**Comment by kimeuietae** [comment]
안녕하세요, 오랜만에 질문 드립니다.
위에 여쭤본 내용에 대해 답변대로 우선 표 컨트롤을 복사하는 기능을 구현 중에 있는데...
ListHeaderForCell.setBorderFillId() 메서드를 통해 테두리를 지정해도 지정이 되지 않는 현상이 있네요..
혹시 참고할 만한 샘플이나 아니면 작업 중이신 부분이 있으시면 답변 부탁 드리겠습니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    ListHeaderForCell.setBorderFillId() 이 함수는  cell에 BorderFill  객체의 id을 설정하는 함수 입니다.
실제 테두리에 대한 내용은 hwpFile.getDocInfo()에  BorderFill을 추가하고 거기에 선/배경에 대한 속성를 설정해야 합니다. 
한글은 폰트, 글자모양, 문단모양, 선/배경모양 같이 문서 전체에서 반복해서 사용하는 객체들을 글로벌 객체처럼  hwpFile.getDocInfo() 아래에 저장하고 
실제 문서에서는 객체의 아이디를 사용하여 그 객체를 링크하는 방식으로 처리합니다.
​​
kr.dogfoot.hwplib.sample.Inserting_Table.java 을 참고하시면 좋을 듯 합니다.
--------- 원본 메일 ---------

    
        보낸사람: kimeuietae <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 20.05.14 16:49 GMT +0900
        제목: Re: [neolord0/hwplib] copyControlList 메서드 문의 (#91)
        
        
    
    
        
안녕하세요, 오랜만에 질문 드립니다.
위에 여쭤본 내용에 대해 답변대로 우선 표 컨트롤을 복사하는 기능을 구현 중에 있는데...
ListHeaderForCell.setBorderFillId() 메서드를 통해 테두리를 지정해도 지정이 되지 않는 현상이 있네요..
혹시 참고할 만한 샘플이나 아니면 작업 중이신 부분이 있으시면 답변 부탁 드리겠습니다.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

    

kr.dogfoot.hwplib.sample.kr.dogfoot.hwplib.sample.kr.dogfoot.hwplib.sample.kr.dogfoot.hwplib.sample.

**Comment by kimeuietae** [comment]
먼저 바쁘신 와중에 답변 주셔서 감사합니다.

네. 안그래도 처음에 답변 주신 것처럼 제공해주신 소스를 분석하여 kr.dogfoot.hwplib.sample.Inserting_Table.java  를 참고하여 개발을 하고 있습니다.
한글문서파일형식_5.0_revision1.3.hwp 문서를 보면서 어느정도 한글문서파일의 큰 구조는 가늠이 되었구요.
말씀해주신 문서 정보 DonInfo Stream에 add한 borderfillid index를 ListHeaderForCell.setBorderFillId(index) 메서드에 아규먼트로 넘겨도 테두리가 변경이 되지 않아 문의 드렸습니다.
Inserting_Table.java 소스에서 사용되는 test-blank.hwp 파일에 표를 추가하면 테두리가 잘 지정이 되나, 한글2010 을 통해 빈문서를 하나 만들고 그 hwp 파일에 표를 추가하면 테두리가 설정이 되지 않네요.

제가 처음 질문을 드린 부분은ParapraphCopyer.Java 클래스 내에 copyControlList 메서드를 통해 표, 이미지를 복사하는 기능 구현에 대하여 문의를 드렸고, 조언 주신 것처럼 관련 샘플 소스들을 보면서 구현 중에 있는데 이 부분에서 막혀서 질문 드렸습니다.
혹시라도 copyControlList 메서드에 모든 컨트롤이 아닌 표 컨트롤에 대한 복사 부분이 추가 가능한지 조심스레 여쭤봅니다.
그럼 늘 감사드립니다.

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    한글은 2010,2015 등 프로그램의 버전과 상관없이.. 일률적으로 패치 하는 것으로 알고 있습니다.
패치 마다.. 약간씩 파일에 형식이나 내용이 변경됩니다. 그리고, 한글문서파일형식 문서는 패치 내용을 한데 묶어서 수정되기 때문에 문서의 내용과 실제 파일이 약간 다를 수도 있습니다.

문의를 보니, Inserting_Table 프로그램이 제가 만든 test-blank.hwp에서는 잘 동작하나 님이 만든(특정 서브 버전으로 패치된 한글에서 만든) 파일에서는 안 된다고 하셨는 데..
이 부분이 좀 의문이네요.  만드신 파일들(Inserting_Table 실행 전 파일, Inserting_Table 실행 후 파일) 파일을 보내주세요. 테스트 해보겠습니다.  
이 부분은 아마도 패치에서 문서형식이 변경 되었을 가능성이 있습니다. 
한컴에서 패치 하면서 잘 못할 수 있으니.. 최신 패치를 받아서 설치해서 거기서 만든 파일로 테스트 해 보세요.

저도 이 부분을 추가하려고 노력하고 있으나.. 회사일 등이 다른 일이 있기 때문에 시간을 내기 힘든 상황입니다.
확실히 언제까지 한다고는 약속드릴 수 없는 상황인지라 저만 바라보고 있다가 프로젝트를 망치지 않을까 두럽습니다. 

--------- 원본 메일 ---------

    
        보낸사람: kimeuietae <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 20.05.15 09:28 GMT +0900
        제목: Re: [neolord0/hwplib] copyControlList 메서드 문의 (#91)
        
        
    
    
        
먼저 바쁘신 와중에 답변 주셔서 감사합니다.
네. 안그래도 처음에 답변 주신 것처럼 제공해주신 소스를 분석하여 kr.dogfoot.hwplib.sample.Inserting_Table.java  를 참고하여 개발을 하고 있습니다.
한글문서파일형식_5.0_revision1.3.hwp 문서를 보면서 어느정도 한글문서파일의 큰 구조는 가늠이 되었구요.
말씀해주신 문서 정보 DonInfo Stream에 add한 borderfillid index를 ListHeaderForCell.setBorderFillId(index) 메서드에 아규먼트로 넘겨도 테두리가 변경이 되지 않아 문의 드렸습니다.
Inserting_Table.java 소스에서 사용되는 test-blank.hwp 파일에 표를 추가하면 테두리가 잘 지정이 되나, 한글2010 을 통해 빈문서를 하나 만들고 그 hwp 파일에 표를 추가하면 테두리가 설정이 되지 않네요.
제가 처음 질문을 드린 부분은ParapraphCopyer.Java 클래스 내에 copyControlList 메서드를 통해 표, 이미지를 복사하는 기능 구현에 대하여 문의를 드렸고, 조언 주신 것처럼 관련 샘플 소스들을 보면서 구현 중에 있는데 이 부분에서 막혀서 질문 드렸습니다.
혹시라도 copyControlList 메서드에 모든 컨트롤이 아닌 표 컨트롤에 대한 복사 부분이 추가 가능한지 조심스레 여쭤봅니다.
그럼 늘 감사드립니다.

**Comment by kimeuietae** [comment]
방금 위에 글을 올리고 나서 다시 테스트를 해보니 제가 잘못 설명 드린 부분이 있어서 글 남기네요.
한글2010을 통해 빈문서를 하나 만들고 그 hwp 파일에 표를 추가하면 테두리가 설정이 안되는게 아니라,
ParagraphCopyer.java 클래스, 현재 비어 있는 copyControlList() 메서드 내에 ArrayList<Control> controlList = source.getControlList(); 와 같이 컨트롤을 찾아와서
for (Control c : source.getControlList() 
{
  if (c.getType().equals(ControlType.Table))
 {
    이 부분에 Inserting_Table.java 클래스의 makeTable 메서드 동일하게 구현
}

위와 같이 적용 하였을 경우, 표는 추가가 되는데 테두리가 지정이 되지 않네요.

**Comment by kimeuietae** [comment]
제가 잘못 말씀 드린 부분에 대해서 정정한 글을 작성 중에 답변을 주셨네요.
한글 파일과는 관련이 없고, 제가 구현 한 로직에 대하여 위에 다시 질문 드렸습니다.

그리고 업무나 프로젝트와는 무관하며 제 개인적으로 활용을 위해서 제공해 주신 라이브러리와 소스를 바탕으로 이것 저것 테스트 해보고 구현 중에 있습니다.
저도 copyControlList() 메서드에 표나 이미지를 복사하는 기능을 구현하게 되면 이곳에 공유하도록 하겠습니다.
그럼 바쁘신 와중에 답변 감사드리며, 좋은 하루 되세요~

**Comment by neolord0** [comment]
표 컨트롤 복사기능 만 추가하였습니다. 받아서 테스트 해보세요..
kr.dogfoot.hwplib.tool.paragraphadder.control.TableCopier  참고하세요.

**Comment by kimeuietae** [comment]
추가 해 주신 클래스를 참고하여 궁금하였던 부분이 해결 되었습니다.
table, listheader 객체의 setBorderFillId 메서드 부분에서 막혀있던 부분이 해결 되었습니다.

진심으로 감사 드립니다.
그럼 오늘 하루도 좋은 하루 되시기를 기원합니다. ^^
