### ISSUE TITLE
hwp 파일의 전체페이지수를 읽어오려면 어떻게해야할까요?

### ISSUE THREAD

**Issue by hohomax** [neolord0/hwplib#92]
올려주신 소스 참고하여
\005HwpSummaryInfomation  스트림에서  hwp파일의 전체 페이지수를 구하고싶은데

현재는

`
DocumentEntry siEntry = (DocumentEntry) dir.getEntry("\005HwpSummaryInformation");
            if(siEntry == null)
                siEntry = (DocumentEntry) dir.getEntry("IHwpSummaryInformation");

            DocumentInputStream dis = new DocumentInputStream(siEntry);
            PropertySet ps = new PropertySet(dis);
            Property[] proper = ps.getProperties();

            StringBuilder sb = new StringBuilder();
            sb.append(proper[3].toString()); // 005HwpSummaryInformation 요약내용 출력
`

이런식으로 스트림 데이터를 읽어들여 proper안에 담긴내용을 짤라서 구하고있는데
해당영역에 페이지값을 가지고있는 파일이 있고 정보가 없는 파일도있네요;;

proper[3].toString()) 의 내용 ==>

Property[id: 20, type: 31 (VT_LPWSTR) , value: 2020년 3월 2일 월요일 오후 3:33:18
00000000 32 00 30 00 32 00 30 00 44 B1 20 00 33 00 D4 C6 2.0.2.0.D± .3.ÔÆ
00000010 20 00 32 00 7C C7 20 00 D4 C6 94 C6 7C C7 20 00  .2.|Ç .ÔÆ.Æ|Ç .
00000020 24 C6 C4 D6 20 00 33 00 3A 00 33 00 33 00 3A 00 $ÆÄÖ .3.:.3.3.:.
00000030 31 00 38 00 00 00 00 00                         **1.8.....** <- 이부분 추출
]

한글에서공개한 5.0 문서를 확인해보니 아래 내용이 페이지 수 관련 내용인듯한데 
어떤 방식으로 추출할수있을까요!? 조언부탁드립니다!
Name  :Number of Pages                
Property ID string : PIDSI_PAGECOUNT
Property ID : 0x0000000E

**Comment by neolord0** [comment]
문서를 보니.. "\005HwpSummaryInformation" 부문의 구조가 
The Summary Information Property Set로 되어 있다고 해서..
찾아보니. 이 구조는  Microsoft 에서 오피스 파일의 요약 정보를 위해 만든 것 입니다.

https://docs.microsoft.com/en-us/windows/win32/stg/the-summary-information-property-set

MS에서는 이 구조를 읽기 위한 API를 windows OS에서 동작하는 버전만  제공 하였고,
JAVA 로는 hohomax 님 셈플에서 사용한 PropertySet 클래스가 동일한 역할을 하는 것 같습니다.

위에 링크에 포함된 속성 표와 hohomax 님이 올리신 프로그램을 살짝 응용해서 만들어 봤습니다..


import org.apache.poi.hpsf.NoPropertySetStreamException;
import org.apache.poi.hpsf.Property;
import org.apache.poi.hpsf.PropertySet;
import org.apache.poi.poifs.filesystem.*;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Date;

public class TestGetInfo {
    public static void main(String[] args)  {
        String filename = "sample_hwp" + File.separator + "big_file.hwp";
        try {
            getInfo(filename);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (NoPropertySetStreamException e) {
            e.printStackTrace();
        }
    }

    private static void getInfo(String filename) throws IOException, NoPropertySetStreamException {
        System.out.println(filename);

        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream(filename));
        DocumentNode entry = (DocumentNode) fs.getRoot().getEntry("\005HwpSummaryInformation");
        if (entry != null) {
            DocumentInputStream dis = new DocumentInputStream(entry);
            PropertySet ps = new PropertySet(dis);
            for (Property p : ps.getProperties()) {
                switch ((int) p.getID()) {
                    case 0x2:
                        title((String) p.getValue());
                        break;
                    case 0x3:
                        subject((String) p.getValue());
                        break;
                    case 0x4:
                        author((String) p.getValue());
                        break;
                    case 0x5:
                        keywords((String) p.getValue());
                        break;
                    case 0x6:
                        comments((String) p.getValue());
                        break;
                    case 0x7:
                        template((String) p.getValue());
                        break;
                    case 0x8:
                        lastSavedBy((String) p.getValue());
                        break;
                    case 0x9:
                        revisionNumber((String) p.getValue());
                        break;
                    case 0xa:
                        totalEditingTime((Date) p.getValue());
                        break;
                    case 0xb:
                        lastPrinted((Date) p.getValue());
                        break;
                    case 0xc:
                        createTimeDate((Date) p.getValue());
                        break;
                    case 0xd:
                        lastSavedTimeDate((Date) p.getValue());
                        break;
                    case 0xe:
                        numberOfPages((Integer) p.getValue());
                        break;
                    case 0xf:
                        numberOfWords((Integer) p.getValue());
                        break;
                    case 0x10:
                        numberOfCharacters((Integer) p.getValue());
                        break;
                    case 0x11:
                        thumbnail(p.getValue());
                        break;
                    case 0x12:
                        nameOfCreatingApplication((String) p.getValue());
                        break;
                    case 0x13:
                        security((Integer) p.getValue());
                        break;
                }
            }
        }
    }

    private static void title(String value) {
        System.out.println("Title : " + value);
    }

    private static void subject(String value) {
        System.out.println("Subject : " + value);
    }

    private static void author(String value) {
        System.out.println("Author : " + value);
    }

    private static void keywords(String value) {
        System.out.println("Keywords : " + value);
    }

    private static void comments(String value) {
        System.out.println("Comments : " + value);
    }

    private static void template(String value) {
        System.out.println("Template : " + value);
    }

    private static void lastSavedBy(String value) {
        System.out.println("Last Saved By : " + value);
    }

    private static void revisionNumber(String value) {
        System.out.println("Revision Number : " + value);
    }


    private static void totalEditingTime(Date value) {
        System.out.println("Total Editing Time : " + value);
    }

    private static void lastPrinted(Date value) {
        System.out.println("Last Printed : " + value);
    }

    private static void createTimeDate(Date value) {
        System.out.println("Create Time/Date : " + value);
    }

    private static void lastSavedTimeDate(Date value) {
        System.out.println("Last saved Time/Date : " + value);
    }

    private static void numberOfPages(Integer value) {
        System.out.println("Number of Pages : " + value);
    }

    private static void numberOfWords(Integer value) {
        System.out.println("Number of Words : " + value);
    }


    private static void numberOfCharacters(Integer value) {
        System.out.println("Number of Characters : " + value);
    }


    private static void thumbnail(Object value) {
        System.out.println("Thumbnail : " + value);
    }


    private static void nameOfCreatingApplication(String value) {
        System.out.println("Name of Creating Application : " + value);
    }


    private static void security(Integer value) {
        System.out.println("Security : "  + value);
    }
}

실행 해 보니.. 테스트 해 본 모든 파일에서 페이지 수를 0으로 설정되어 있었습니다.
아마도, 한글 프로그램에서 이 값을 설정하지 않는 것 같습니다.

**Comment by hohomax** [comment]
답변감사합니다 
많은도움되었습니다!!
