### ISSUE TITLE
Copying_Paragraph_Between_HWPFile.java 문의

### ISSUE THREAD

**Issue by kimeuietae** [neolord0/hwplib#93]
먼저 답변 주신 부분들로 인해서 스터디에 많은 도움이 되고 있어서 감사 드립니다.

샘플 중에서 Copying_Paragraph_Between_HWPFile 클래스 내에
sourceHWPFile의 0번째 문단이 아닌 1번째 문단을 복사 하게끔 되어 있는데,
0번째 문단을 복사하면 해당 HWP 파일을 열면 손상된 파일이라고 메세지가 뜨면서 열리지가 않네요.

 이 부분이 혹시 한글 파일 특성상 각 구격의 첫 문단에 구역 정의 레코드가 저장되는데, 이 부분을 복사해서 오류가 발생하는 건가요?
아니면 다른 이유가 있는건가요?

그럼 시간 되실 때 답변 부탁 드리겠습니다.

**Comment by neolord0** [comment]
Copying_Paragraph_Between_HWPFile 는.. sourceHWPFile 뒤에다.. targetHWPFile 내용을 붙인다는 목표를 가지고 만든 겁니다. 그래서. sourceHWPFile에 문단 1개가 이미 있으면...  그 뒤에 복사됩니다.
아마도, 문단 리스트 중에 마지막 문단을 표시하는 부분이 잘 못된 게 아닐까 생각됩니다.

**Comment by kimeuietae** [comment]
답변 내용을 바탕으로 다시 확인 해 보았습니다.
해당 샘플은 source 뒤에 target을 붙이는게 아니라 target 뒤에 source를 붙이게끔 되어 있습니다.
결과물인 test-target-add.paragraph.hwp 파일을 확인 해 보면 아실 수 있습니다.
제가 궁금한 부분은 어떤 대상 뒤에 어떤 걸 붙이던
sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(1); 로 되어 있는 부분을
sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(0); 으로 수정해서 실행하면 소스상에 오류는 없으나 결과물인 해당 HWP 파일을 열면 "파일이 손상되었습니다." 라는 메세지가 나옵니다.
관련 된 ParagraphAdder 클래스를 살펴보아도 인덱스가 0번째인 문단을 add 하면 파일이 손상 되는지 알 수가 없어서 문의 드립니다.

**Comment by neolord0** [comment]
문단 리스트에서 중간에 끼워 넣을 때.. 처리가 되지 않은 거 같습니다.
문단 뒤쪽에.. 추가하는 부분만 처리한 거 같네요.
sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(1); 문단 리스트에서 끝 문단인 거 같습니다.  그래서.. 문제가 없었던 거 아닌가 생각됩니다. 
0은 문서 끝이 아니라서.. 리스트 중간에 삽입되는 거라서 문제가 된 거 같습니다. 

한글 프로그램으로 원하는 형태(복사 붙여넣기 된 문서)을 만드신 다음에.. 라이브러리로 읽어서.
파일의 구조를 살펴보시고 그렇게 만들어지게 끔 프로그래밍 해보세요.. 
라이브러리로 만든  파일이랑 비교해보면 어디가 잘 못됐는지 알 수 있을 겁니다. 

제가 생각하기로는 아마도, ParaHeader.lastInList 속성이 잘 못된 게 아닌가 생각됩니다. 문단 리스트에 마지막 문단을 표시하는 속성인데, 이 속성값이 제대로 설정 됐는지 살펴보세요.

**Comment by kimeuietae** [comment]
답변 주신 부분에 대하여 확인 후, 문의 드립니다.

sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(1); 는 끝 문단이 아닙니다.
해당 한글파일은 아래와 같은 내용을 담고 있습니다. (밑줄 부분 이후)
-----------------------------------------------------------------------------

이것은 원본 HWP 파일의 내용입니다. 1
이것은 원본 HWP 파일의 내용입니다. 2
이것은 원본 HWP 파일의 내용입니다. 3
이것은 원본 HWP 파일의 내용입니다. 4
이것은 원본 HWP 파일의 내용입니다. 5
-----------------------------------------------------------------------------
즉, sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(1); 는 끝 문단이 아니라 중간 문단입니다.
그리고 해당 샘플은 위에서 말씀 드린 것처럼  source 뒤에 target을 붙이는게 아니라 target 뒤에 source를 붙이게끔 되어 있습니다.

sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(0);
sourceHWPFile.getBodyText().getSectionList().get(0).getParagraph(1); 

소스를 디버깅하여 객체를 확인 해 보면 위 두 문단에 대한 차이점이 아래와 같습니다.
0 번째 문단은 controlList에 0 ControlSectionDefine, 1 ControlColumnDefine 두 개의 객체가 있고
1 번째 문단은 controlList가 null 입니다.

그래서 제가 처음 질문 드린 부분이 
한글 파일 특성상 각 구역의 첫 문단에 구역 정의 레코드가 저장되는데, 이 부분을 복사해서 오류가 발생하는 건가요?

문의 드린 부분이구요...
아마도 이 부분 copy 가 구현되어 있지 않아 0번째 문단을 복사하면 파일이 손상 되었다는 메세지와 함께 한글파일이 열리지 않는 듯 하여 문의 드립니다.

**Comment by kimeuietae** [comment]
위에 글에 밑줄을 넣었더니 폰트가 변경되서 등록이 되네요... ㅡㅡ;;

**Comment by neolord0** [comment]
0번 문단을 source로 사용하여 복사할 경우에 오류가 난다는 내용인가요 ??

**Comment by kimeuietae** [comment]
네. 맞습니다.
디버깅 해보니 0번 문단에 구역정의 컨트롤과 단정의 컨트롤이 있어서 그런듯 합니다..
​
-----Original Message-----

**Comment by neolord0** [comment]
어디가 문제인지 짐작은 가는데요... 테스트하고 수정해서 올리겠습니다.

**Comment by kimeuietae** [comment]
네. 감사합니다.
저도 문의드리고 나서 계속 수정해서 테스트 해보고 있습니다. 구역 정의 컨트롤 단 정의 컨트롤 부분에 이것저것 해보고 있는데 잘 되지는 않네요.
​
-----Original Message-----

**Comment by neolord0** [comment]
수정했습니다.. 받아서.. 확인하세요..

**Comment by kimeuietae** [comment]
네. 확인 해 보니 정상 작동 합니다.
빠쁘신 와중에도 답변 주셔서 진심으로 감사 드립니다.

좋은 하루 되세요~ ^^
