### ISSUE TITLE
안녕하세요. 전체 누름틀 정보 호출하는 과정에 오류가 발생하여 문의드립니다.

### ISSUE THREAD

**Issue by j2y0206** [neolord0/hwplib#94]
안녕하세요. 우선 만들어 주신 내용 아주 잘 활용하고 있음에 감사드립니다.
문서 내 누름틀록 작성된 텍스트 리스트를 구하려고 하는데, NullPointerException 이 발생하여 문의 드립니다.

#오류 내용
kr.dogfoot.hwplib.tool.objectfinder.forField.gettext.ForGsoWithAllField.textBox(ForGsoWithAllField.java:91)

#소스위치
ForControlWithAllField.getFieldText
->
 case Gso:
                    ForGsoWithAllField.getFieldText((GsoControl) c, fieldType,
                            fieldName, temInField, textList);
->
ForGsoWithAllField.getFieldText
->
 case Rectangle:
                rectangle((ControlRectangle) gc, fieldType, fieldName,
                        temInField, textList);
->
textBox(rectangle.getTextBox(), fieldType, fieldName, temInField, textList);
->
ForParagraphList.getAllFieldText(textBox.getParagraphList(), fieldType, fieldName, temInField, textList);

디버깅 해보니 위의 위치에서 "textBox.getParagraphList()" 가 null로 나타납니다.

감사합니다.

**Comment by neolord0** [comment]
정확한 오류를 체크하기 위해.. 
파일을 보내주셨으면 합니다.

**Comment by j2y0206** [comment]
안녕하세요.

이렇게 빨리 피드백이 올줄은 몰랐어요. 빠른 피드백 감사드립니다.

테스트 했던 파일은 첨부의 국회회의록 문서이고, 문서 내용 중 필드 이름이 "발언자"로 되어 있는 누름틀 목록을 가져오려고 하는
과정에서 문제가 발생하였습니다.
(누름틀 1개를 가져오는 경우 첫 발언자 정보를 정상적으로 얻을 수 있었습니다.)

감사합니다.

2020년 6월 15일 (월) 오전 8:28, park.sung kyun <notifications@github.com>님이 작성:

**Comment by neolord0** [comment]
첨부 파일이 없네요.. 다시 보내주세요.

**Comment by j2y0206** [comment]
보낸편지함에서 확인했는데, 첨부 파일이 없나요?

Gmail에서 회신으로 문서 첨부합니다. (혹여 전달 방식이 잘못되었다면 말씀해주세요)

감사합니다.

2020년 6월 15일 (월) 오후 7:00, park.sung kyun <notifications@github.com>님이 작성:

**Comment by neolord0** [comment]
p{margin-top:0;margin-bottom:0}
    


    파일에 대한 첨부나 링크가 없는데요..  --;  
Gmail에서 회신하여 파일을 첨부하는 방식으로는 파일이 전달되지 않은 것 같습니다.
github.com 이슈에 직접올리시거나. neolord@hanmail.net에  보내주세요.

--------- 원본 메일 ---------

    
        보낸사람: j2y0206 <notifications@github.com>
        받는사람: neolord0/hwplib <hwplib@noreply.github.com>
        
            참조: park.sung kyun <neolord@hanmail.net>, Comment <comment@noreply.github.com>
        
        날짜: 20.06.15 19:04 GMT +0900
        제목: Re: [neolord0/hwplib] 안녕하세요. 전체 누름틀 정보 호출하는 과정에 오류가 발생하여 문의드립니다. (#94)
        
        
    
    
        

보낸편지함에서 확인했는데, 첨부 파일이 없나요?







Gmail에서 회신으로 문서 첨부합니다. (혹여 전달 방식이 잘못되었다면 말씀해주세요)







감사합니다.







2020년 6월 15일 (월) 오후 7:00, park.sung kyun <notifications@github.com>님이 작성:

**Comment by neolord0** [comment]
파일 받아서 테스트 해봤습니다..
사각형 등에 그리기 객체에 textBox가 null일 수 있는데..  그걸 생각하지 못 했더군요..
github 코드는 수정했습니다. 다시 받아서 테스트 해보세요.

**Comment by j2y0206** [comment]
빠른 수정 감사드립니다.

더욱 더 열심히 사용해 보도록 하겠습니다.

감사합니다.

2020년 6월 16일 (화) 오후 5:09, park.sung kyun <notifications@github.com>님이 작성:
