### ISSUE TITLE
이슈는 아니고 Paragraph 속성 질문드립니다.

### ISSUE THREAD

**Issue by profile71** [neolord0/hwplib#95]
안녕하세요.
HWP 분석 중 궁금한 부분이 있는데 혹시나 답을 찾을 수 있을까 싶어서 질문드립니다.

"Paragraph"의 "LineSeg"를 구성하는 정보 중 "height"와 "height-baseline"이 있는데 어떤 차이점이 있는건지  알 수 있을까요?

**Comment by neolord0** [comment]
"의 를 구성하는 정보 중 와 이 있는데 어떤 차이점이 있는건지 알 수 있을까요?"
 
무슨 뜻 인가요?

내용이 빠진 거 같습니다.

**Comment by profile71** [comment]
특수문자("<")를 넣었더니 글이 빠졌네요.
수정했습니다. ㅎㅎ;

**Comment by neolord0** [comment]
아마도 이 내용이 아닐까 생각됩니다.

![baseline](https://user-images.githubusercontent.com/24711108/87731776-3d2deb80-c806-11ea-97e1-e5b0c166b617.png)

**Comment by profile71** [comment]
답변 정말 감사합니다. 
알고싶었던 내용인데 찾을 길이 없었네요.;

혹시 이런 정보를 따로 볼 수 있는 곳이 있을까요?
그림이 조금 작기도해서요.

**Comment by profile71** [comment]
그림과 관련해서는 그림에 사용된 단어들로 찾아보니 여러개가 있네요.
도움 감사합니다.~
