### ISSUE TITLE
해당 라이브러리로 만든 hwp 파일은 안드로이드 hwp viewer에서 지원하나요?

### ISSUE THREAD

**Issue by ingyeoking13** [neolord0/hwplib#97]
안녕하세요, library 파일을 android 프로젝트로 옮기고 나서 다음과 같은 소스로 작성하였습니다.

```java
public void onClick(View v)
{
                        HWPFile file  = new HWPFile();
                        Section s = new Section();
                        s.addNewParagraph();

                        Paragraph pp =  s.getParagraph(0);
                        if (pp != null) {
                            ParaText pt = pp.getText();
                            if (pt == null) {
                                pp.createText();
                                pt = pp.getText();
                            }

                            try { pt.addString("HELLO HWP!"); }
                            catch (Exception e) { e.printStackTrace(); }
                        }

                        file.getBodyText().getSectionList().add(s);

                        File f =  new File(getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS),
                                "testFile.hwp");

                        if ( f.exists())
                            f.delete();

                        try {
                            f.createNewFile();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }

                        try {
                            HWPWriter.toFile(file, f.getAbsolutePath());
                        }
                        catch (Exception e)
                        {
                            e.printStackTrace();
                        }
}
```
안드로이드 한컴오피스 viewer 로 열었을 때 "지원하지 않거나 알수없는 파일양식입니다" 의 에러가 출력됩니다.
안드로이드 hwp viewer 에서도 정상동작해야하는 거라 생각하는데, 문의 남깁니다.
해당 소스는 [SimpleEditing_HWPFile.java](https://github.com/neolord0/hwplib/blob/master/src/main/java/kr/dogfoot/hwplib/sample/SimpleEditing_HWPFile.java) 를 참조했습니다.

**추가**
안드로이드에서 생성한 hwp파일을 데스크톱으로 여니 "파일이 손상되었습니다" 라고 출력됩니다.

**Comment by neolord0** [comment]
안드로이드 에서.. 테스트를 안 해봐서... 정확히는 알 수 없지만...
에러 만으로 봐선... 파일이 제대로 만들어지지 안았다는 건데요.. 
만들어진 파일을 보내주시면, 어느 정도 감은 잡을 수 있지 않을까 생각됩니다.

**Comment by ingyeoking13** [comment]
@neolord0  그렇다면 소스코드로 먼저 blank.hwp 파일을 생성한 뒤 HWPReader.fromFile 로 읽어서 수행해야하나요? 
소스코드로 빈 파일을 생성한다더라도, 그 곳에 공통 부분(폰트, 문단 모양, 글자 모양)이 포함되지 않을 것 같은데, 수동적으로 추가하는 방법이 있나요?

**Comment by neolord0** [comment]
아무런 파일이 없는 상태에서.. 파일을 만들 수 있긴 한데요..
코딩 양이 꽤 돼서.. 샘플에서 간단하게. 읽어서.. 추가하고 다시 저장하는 코드만 넣었습니다.

blank.hwp  파일을 읽은 후 HWPFile 객체를 디버깅 툴로 살펴보시면.  HWPFile 객체안에.. 많은 객체가 포함되어 있습니다.

<img width="579" alt="스크린샷 2020-08-28 오후 1 34 18" src="https://user-images.githubusercontent.com/24711108/91521707-3df08c00-e933-11ea-89dc-d7b174c1a395.png">

 이 것과 동일하게 추가해야 비로소. blank.hwp 파일이 됩니다.

샘플을 올릴 때.. 시간이 없어서.. 그렇게 올렸는데..  
시간이 되면... blank.hwp 를 만드는 코드를 올리곘습니다.

**Comment by ingyeoking13** [comment]
@neolord0 감사합니다. new HWPFile()로 파일이 생성되는게 아니였군요. 이슈에 물어보길 잘 한 것 같습니다. 저는, 빈 한글 파일을 만드는 소스코드를 기다려야할 것 같네요.

빠른 답변 감사합니다!.

**Comment by neolord0** [comment]
빈 한글 파일을 만드는 소스코드  추가 했습니다.. 
받아서 테스트 해보세요.

**Comment by ingyeoking13** [comment]
@neolord0  감사합니다.
