### ISSUE TITLE
안녕하세요? 페이지번호 및 가운데 정렬된 문단 찾기 질문있습니다.

### ISSUE THREAD

**Issue by youaremytelos** [neolord0/hwplib#98]
먼저, 좋은 라이브러리 만들어 주셔서 감사합니다.

1.페이지번호
 Paragraph를 루트로 하위의 모든 객체의 모든 값을 검색해보아도 페이지 번호를 확인하지 못하고 있습니다.

2.가운데 정렬된 Paragraph 찾기
 Paragraph를 루트로 하위의 모든 객체의 모든 값을 검색해보아도 텍스트가 시작되는 위치가 가운데를 가리키는 데이터를 찾지 못했습니다.(paragraph.getLineSeg().getLineSegItemList().get(0).getTextStartPositon() 해보아도 0으로 나타납니다.)

바쁘시겠지만, 질문 답변 주시면 많은 도음될 것 같습니다.

감사합니다.

**Comment by neolord0** [comment]
1. 페이지 번호
; 페이지 번호는 파일 내뷰에 설정되는 값이 아니라 한글 프로그램이 계산하는 값 입니다. 추측컨데, 한글 프로그램은 현재 페이지를 문단으로 채우다 페이지에 공간이 부족하면 페이지를 추가하는 방식으로 페이지를 그려나가는 것 같습니다. 
페이지 수를 알려면 한글 파일을 그려야 하며 이 가능을 아직 구현하지 못 했습니다. 

2. 가운데 정렬인 문단 ...
대부분의 문단 속성은 문단 모양 객체(HWPFIle.DocInfo.ParaShape list)에 있습니다.
한글 파일은 파일 내부에서 여러 번 사용할 가능성이 있는 객체들(예, 문단 모양, 글자 모양)을  HWPFIle.DocInfo 에 모아서 관리합니다.
실제 문단에서는 이 객체들을 링크해서 사용합니다.  Paragraph.ParaHeader.paraShapeId을 참조하여  HWPFIle.DocInfo.ParaShape 리스트 안에 문단 모양 객체을 찾은 후 문단 모양 객체를 살펴보시면.. 정렬 속성이 있을 겁니다.

**Comment by youaremytelos** [comment]
답변 감사합니다. 말씀하신 부분 참조하여 적용해보도록 하겠습니다.^^
