### ISSUE TITLE
문의사항이 있습니다. 수학 수식 및 라텍스 관련

### ISSUE THREAD

**Issue by ryuhangyeong** [neolord0/hwplib#99]
좋은 오픈소스 만들어주셔서 감사합니다. 혹시 html에서 라텍스로 표현된 것도 한글로 변환이 가능한가요?

**Comment by neolord0** [comment]
한글에 수식 컨트롤이 있어서.. 테스트 해보니.. 라텍스 문법은 아닌 거 같습니다.
이미지로 변환해서 넣는 수 밖에 없는 거 같습니다.

**Comment by ryuhangyeong** [comment]
@neolord0 알려주셔서 감사합니다. 좋은 오픈소스 늘 감사드립니다.
